// Generated by tools/animations/pit-lord-specials.ts; regenerate instead of editing.
import { f32 } from "wisp/src/sim/f32";
import type { HeroClipTable } from "../../sim/heroes/hero";
export const PIT_LORD_SPECIAL_CLIPS = {
  neutralSpecial: { index: 57, seconds: f32(0.767), aligned: true }, neutralSpecialAir: { index: 57, seconds: f32(0.767), aligned: true },
  sideSpecial: { index: 58, seconds: f32(1.067), aligned: true }, sideSpecialAir: { index: 58, seconds: f32(1.067), aligned: true },
  upSpecial: { index: 59, seconds: f32(0.533), aligned: true }, upSpecialAir: { index: 59, seconds: f32(0.533), aligned: true },
  downSpecial: { index: 60, seconds: 1.0, aligned: true }, downSpecialAir: { index: 60, seconds: 1.0, aligned: true },
} as const satisfies HeroClipTable;
