


interface ClipBinding {

  readonly key: string;
  readonly index: number;

  readonly seconds?: number;
}

export interface ModelAssetInfo {

  readonly prefix: string;
  readonly modelPath: string;
  readonly clips: readonly ClipBinding[];
}


export function seconds(value: number): string {
  const literal = Number.isInteger(value) ? value.toFixed(1) : String(value);
  return Math.fround(value) === value ? literal : `f32(${literal})`;
}

export function typescriptAssetInfo(generator: string, models: readonly ModelAssetInfo[]): string {
  const lines = [
    `// Generated by ${generator} from the authored models; regenerate instead of editing.`,
    'import { f32 } from "wisp/src/sim/f32";',
    "",
  ];
  for (const { prefix, modelPath, clips } of models) {
    lines.push(`export const ${prefix}_MODEL_FILE = ${JSON.stringify(modelPath)};`);
    for (const clip of clips) {
      lines.push(`export const ${prefix}_${clip.key}_INDEX = ${clip.index};`);
      if (clip.seconds !== undefined) lines.push(`export const ${prefix}_${clip.key}_SECONDS = ${seconds(clip.seconds)};`);
    }
  }
  return `${lines.join("\n")}\n`;
}
