// The TypeScript presentation modules generated from each model's authored
// clips: the imported model path and each sequence index and duration.

interface ClipBinding {
  /** Constant-name fragment, such as GRAB_HOLD. */
  readonly key: string;
  readonly index: number;
  /** Present when presentation code owns this clip's clock. */
  readonly seconds?: number;
}

export interface ModelAssetInfo {
  /** Constant prefix, such as ARCHER. */
  readonly prefix: string;
  readonly modelPath: string;
  readonly clips: readonly ClipBinding[];
}

/** An exact binary32 value as a literal; other values round through f32(). */
export function seconds(value: number): string {
  const literal = Number.isInteger(value) ? value.toFixed(1) : String(value);
  return Math.fround(value) === value ? literal : `f32(${literal})`;
}

export function typescriptAssetInfo(generator: string, models: readonly ModelAssetInfo[]): string {
  const lines = [
    `// Generated by ${generator} from the authored models; regenerate instead of editing.`,
    'import { f32 } from "waygate/src/sim/f32";',
    "",
  ];
  for (const { prefix, modelPath, clips } of models) {
    lines.push(`export const ${prefix}_MODEL_FILE = ${JSON.stringify(modelPath)};`);
    for (const clip of clips) {
      lines.push(`export const ${prefix}_${clip.key}_INDEX = ${clip.index};`);
      if (clip.seconds !== undefined) lines.push(`export const ${prefix}_${clip.key}_SECONDS = ${seconds(clip.seconds)};`);
    }
  }
  return `${lines.join("\n")}\n`;
}
