// Foreign MDX/SYLK boundary: export authored sound cues without changing their timing.
// The cues and labels come from the original fighter models and the game's
// AnimSounds.slk, so the evidence stays in private storage outside the checkout.
// Usage: bun tools/animations/export-model-sounds.ts --assets PRIVATE_ASSETS --sounds AnimSounds.slk --out OUTPUT
import {join, resolve, relative} from 'node:path';
import {seconds} from './asset-info';
import {fighters, parseSource, ensure, hash} from './original-clips';
import {slkRows} from './slk';

const project = resolve(import.meta.dir, '../..');
const option = (name: string) => { const index = process.argv.indexOf(name); return index < 0 ? undefined : process.argv[index + 1]; };
const assetsOption = option('--assets'), tableOption = option('--sounds'), outputOption = option('--out');
ensure(assetsOption !== undefined && tableOption !== undefined && outputOption !== undefined,
    'usage: bun tools/animations/export-model-sounds.ts --assets PRIVATE_ASSETS --sounds AnimSounds.slk --out OUTPUT');
const assets = resolve(assetsOption), tablePath = resolve(tableOption), output = resolve(outputOption);
ensure(relative(project, output).startsWith('..'), 'Sound evidence derives from the original models: write it outside the checkout');
const tableBytes = await Bun.file(tablePath).arrayBuffer();
const table = slkRows(new TextDecoder().decode(tableBytes));
const byCode = new Map<string, Record<string, string>[]>();
for (const row of table) {
    const code = row.AnimationEventCode;
    if (code && code !== '_') byCode.set(code, [...byCode.get(code) ?? [], row]);
}
const sounds: Record<string, string>[] = [];
const records = [];
for (const [character, fighter] of fighters.entries()) {
    const bytes = await Bun.file(join(assets, fighter.source)).arrayBuffer();
    const source = parseSource(bytes);
    const cues = [];
    for (const event of source.EventObjects) {
        if (!event.Name.startsWith('SND')) continue;
        ensure(/^SND.[A-Za-z0-9]{4}$/.test(event.Name), `${fighter.name}/${event.Name}: unknown sound event name`);
        // This codec emits the non-global KEVT sentinel. parseSource's exact
        // byte round-trip rejects a source global event clock it cannot retain.
        const code = event.Name.slice(4);
        const rows = byCode.get(code) ?? [];
        ensure(rows.length === 1, `${code}: expected one stock sound definition, found ${rows.length}`);
        const row = rows[0];
        ensure(row.SoundName && row.FileNames && row.FileNames !== '_', `${code}: missing stock sound label/files`);
        let soundIndex = sounds.findIndex(sound => sound.AnimationEventCode === code);
        if (soundIndex < 0) { soundIndex = sounds.length; sounds.push(row); }
        for (const [keyIndex, time] of event.EventTrack.entries()) {
            const sequenceIndices = source.Sequences.flatMap((seq, index) => time >= seq.Interval[0] && time <= seq.Interval[1] ? [index] : []);
            ensure(sequenceIndices.length > 0, `${fighter.name}/${event.Name}@${time}: event is outside every source clip`);
            for (const sequenceIndex of sequenceIndices) cues.push({sequenceIndex,
                seconds: (time - source.Sequences[sequenceIndex].Interval[0]) / 1000,
                soundIndex, objectId: event.ObjectId, keyIndex, eventName: event.Name,
                sourceTime: time, sequenceName: source.Sequences[sequenceIndex].Name});
        }
    }
    cues.sort((a, b) => a.sequenceIndex - b.sequenceIndex || a.seconds - b.seconds || a.objectId - b.objectId || a.keyIndex - b.keyIndex);
    records.push({character, fighter: fighter.name, source: fighter.source, sourceSha256: hash(bytes), cues});
}
const typescript = [
    '// Generated by tools/animations/export-model-sounds.ts from the original fighter models\' sound events and AnimSounds.slk; regenerate instead of editing.',
    'import { f32 } from "wisp/src/sim/f32";',
    '',
    '/** A sound keyed at `seconds` into an original sequence. */',
    'export interface ModelSoundCue {',
    '  readonly sequenceIndex: number;',
    '  readonly seconds: number;',
    '  readonly soundIndex: number;',
    '}',
    '',
    '/** Stock sound labels by sound index; each owns its variants, pitch, channel and attenuation. */',
    'const LABELS: readonly string[] = [',
    ...sounds.map(sound => `  ${JSON.stringify(sound.SoundName)},`),
    '];',
    '',
    'const IS_3D: readonly boolean[] = [',
    ...sounds.map(sound => `  ${sound.Flags.split(',').includes('WANT3D')},`),
    '];',
    '',
    '/** Each character\'s cues, ordered as authored. */',
    'const CUES: readonly (readonly ModelSoundCue[])[] = [',
    ...records.flatMap(record => [`  // ${record.fighter}`, '  [',
        ...record.cues.map(cue => `    { sequenceIndex: ${cue.sequenceIndex}, seconds: ${seconds(Number(cue.seconds.toFixed(3)))}, soundIndex: ${cue.soundIndex} },`),
        '  ],']),
    '];',
    '',
    '/** The stock sound label, which owns its variants, pitch, channel and attenuation. */',
    'export function modelSoundLabel(soundIndex: number): string | undefined {',
    '  return LABELS[soundIndex];',
    '}',
    '',
    'export function modelSoundIs3D(soundIndex: number): boolean {',
    '  return IS_3D[soundIndex] ?? false;',
    '}',
    '',
    '/** Cues 0 to count - 1 exist for this character, ordered as authored. */',
    'export function fighterSoundCueCount(character: number): number {',
    '  return CUES[character]?.length ?? 0;',
    '}',
    '',
    'export function fighterSoundCue(character: number, ordinal: number): ModelSoundCue | undefined {',
    '  return CUES[character]?.[ordinal];',
    '}',
];
await Bun.write(join(project, 'ts/src/game/assets/modelSoundInfo.ts'), typescript.join('\n') + '\n');
await Bun.write(join(output, 'model-sounds-evidence.json'), JSON.stringify({
    status: 'authored-sound-metadata-extracted-native-pending', table: 'AnimSounds.slk', tableSha256: hash(tableBytes), sounds, records,
    policy: 'Exact source event key/sequence identity; label and variant files resolved from installed stock AnimSounds.slk. Runtime dispatch is confirmed only.',
    limits: ['Native label playback, original random-variant and pitch behavior, spatial mix and polyphony remain unverified.',
        'This exports fighter model SND events only. Footprints, splats, spawned objects, particles and stock projectile/summon components remain separate.',
        'Custom animation clips with no authored SND event acquire no invented sound cue.'],
}, null, 2) + '\n');
console.log(`MODEL_SOUND_EXPORT_PASS ${records.reduce((n, r) => n + r.cues.length, 0)} cues, ${sounds.length} stock labels`);
