import { join, relative, resolve } from "node:path";
import { generateMDX, parseMDX, model as mdx } from "war3-model";
import { fighters, removeBodyEffects } from "./original-clips";
import { modelFacts } from "../../ts/node_modules/wisp/scripts/wisp/models";

const [assetsArg, outputArg] = process.argv.slice(2);
if (assetsArg === undefined || outputArg === undefined) throw new Error("usage: bun tools/animations/white-flash-models.ts PRIVATE_ASSETS PRIVATE_OUTPUT");
const assets = resolve(assetsArg), output = resolve(outputArg);
if (!relative(resolve(import.meta.dir, "../.."), output).startsWith("..")) throw new Error("White fighter models must stay in private storage");
const hash = (bytes: Uint8Array) => new Bun.CryptoHasher("sha256").update(bytes).digest("hex");
const texture = new Uint8Array(18 + 16);
texture[2] = 2; texture[12] = 2; texture[14] = 2; texture[16] = 32; texture[17] = 0x28;
texture.fill(255, 18);
const textureName = `FighterWhite-${hash(texture)}.tga`;
await Bun.write(join(output, textureName), texture);
const paths: string[] = [], imports = [textureName];
const facts: Record<string, ReturnType<typeof modelFacts>> = {};
for (const fighter of fighters) {
  const source = await Bun.file(join(assets, fighter.source)).arrayBuffer();
  const model = parseMDX(source);
  const sequence = model.Sequences[0];
  if (sequence === undefined) throw new Error(`${fighter.name}: no animation sequence`);
  const lastFrame = Math.max(...model.Sequences.map(item => item.Interval[1]));
  model.Sequences = [{ ...sequence, Name: "Stand", Interval: new Uint32Array([0, lastFrame]), NonLooping: true }];
  removeBodyEffects(model);
  model.Lights = [];
  for (const material of model.Materials) {
    const halo = material.Layers.some(layer => typeof layer.TextureID === "number" && model.Textures[layer.TextureID]?.ReplaceableId === 2);
    material.Layers = [{ FilterMode: mdx.FilterMode.Blend, Shading: mdx.LayerShading.Unshaded | mdx.LayerShading.TwoSided | mdx.LayerShading.NoDepthSet, TextureID: 0, TVertexAnimId: -1, CoordId: 0, Alpha: halo ? 0 : 1 }];
  }
  model.Textures = [{ Image: `war3mapImported\\${textureName}` }];
  for (const geoset of model.GeosetAnims) { geoset.Color = new Float32Array([1, 1, 1]); geoset.Flags &= ~mdx.GeosetAnimFlags.Color; }
  const bytes = new Uint8Array(generateMDX(model));
  const decoded = parseMDX(bytes.buffer);
  if (decoded.Sequences.length !== 1 || decoded.Geosets.length !== model.Geosets.length) throw new Error(`${fighter.name}: white overlay changed geometry`);
  const filename = `${fighter.name}White-${hash(bytes)}.mdx`;
  await Bun.write(join(output, filename), bytes);
  imports.push(filename); paths.push(`war3mapImported\\${filename}`);
  facts[`war3mapImported/${filename}`.toLowerCase()] = modelFacts(bytes);
}
await Bun.write(join(output, "white-flash-imports.txt"), imports.join("\n") + "\n");
await Bun.write(join(import.meta.dir, "../../ts/src/game/assets/whiteFighterModels.ts"), `// Generated by tools/animations/white-flash-models.ts; regenerate instead of editing.\nexport const WHITE_FIGHTER_MODELS: readonly string[] = ${JSON.stringify(paths, null, 2)};\n`);
await Bun.write(join(import.meta.dir, "../../ts/scripts/wisp/whiteModelFacts.ts"), `// Generated by tools/animations/white-flash-models.ts; regenerate instead of editing.\nimport type { ModelFacts } from "wisp/scripts/wisp/models";\nexport const WHITE_MODEL_FACTS: Readonly<Record<string, ModelFacts>> = ${JSON.stringify(facts, null, 2)};\n`);
console.log(`${paths.length} white body models: original mesh and animation keys retained on one seekable timeline, emitters/lights removed`);
