export const character = 23;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\undead\\herocryptlord\\herocryptlord.mdx';
export const visibilityPairs: readonly (readonly [number, number])[] = [[0, 0], [1, 1]];
export const classic = {
    root: 'Bone_Root',
    pelvis: 'Bone_Pelvis',
    chest: 'Bone_Chest',
    neck: 'Bone_Neck',
    head: 'Bone_Head',
    'shoulder.L': 'Bone_Arm1L',
    'elbow.L': 'Bone_Arm2L',
    'wrist.L': 'Bone_Arm3L',
    'shoulder.R': 'Bone_Arm1R',
    'elbow.R': 'Bone_Arm2R',
    'wrist.R': 'Bone_Arm3R',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['root', 'local_C0_0_jnt'],
    ['pelvis', 'spine_C0_0_jnt'],
    ['root', 'spine_C1_0_jnt'],
    ['chest', 'chest_C0_0_jnt'],
    ['neck', 'neck_C0_0_jnt'],
    ['head', 'head_C0_0_jnt'],
    ['Bone_Jaw', 'jaw_C0_0_jnt'],
    ['Bone_Butt', 'abdomen_C0_0_jnt'],
    ['chest', 'armor_C0_0_jnt'],
    ['chest', 'armor_plate_C0_0_jnt'],
    ['Bone_HeadCloth1L', 'armor_plate_L0_0_jnt'],
    ['Bone_HeadCloth2L', 'armor_plate_L1_0_jnt'],
    ['Bone_HeadCloth3L', 'armor_plate_L2_0_jnt'],
    ['Bone_HeadCloth1R', 'armor_plate_R0_0_jnt'],
    ['Bone_HeadCloth2R', 'armor_plate_R1_0_jnt'],
    ['Bone_HeadCloth3R', 'armor_plate_R2_0_jnt'],
    ['chest', 'elytraA_C0_0_jnt'],
    ['Bone_TopCarapaceL', 'wingA_L0_0_jnt'],
    ['Bone_TopCarapaceR', 'wingA_R0_0_jnt'],
    ['Bone_Butt', 'elytraB_C0_0_jnt'],
    ['Bone_RearCarapaceL', 'wingB_L0_0_jnt'],
    ['Bone_RearCarapaceR', 'wingB_R0_0_jnt'],
    ['chest', 'shoulder_L0_0_jnt'],
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['elbow.L', 'elbow_L0_0_jnt'],
    ['wrist.L', 'wrist_L0_0_jnt'],
    ['Bone_ArmClawL', 'finger_L0_0_jnt'],
    ['Bone_ArmShieldR01', 'pauldron_L0_0_jnt'],
    ['chest', 'shoulder_R0_0_jnt'],
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['elbow.R', 'elbow_R0_0_jnt'],
    ['wrist.R', 'wrist_R0_0_jnt'],
    ['Bone_ArmClawR', 'finger_R0_0_jnt'],
    ['Bone_ArmShieldR', 'pauldron_R0_0_jnt'],
    ['Bone_LFLeg04', 'legA_L0_0_jnt'],
    ['Bone_LFLeg03', 'legA_L0_2_jnt'],
    ['Bone_LFLeg02', 'legA_L0_4_jnt'],
    ['Bone_LegEnd03', 'legA_L0_6_jnt'],
    ['Bone_LFLeg07', 'legA_R0_0_jnt'],
    ['Bone_LFLeg06', 'legA_R0_2_jnt'],
    ['Bone_LFLeg05', 'legA_R0_4_jnt'],
    ['Bone_LegEnd01', 'legA_R0_6_jnt'],
    ['Bone_LFLeg13', 'legB_L0_0_jnt'],
    ['Bone_LFLeg14', 'legB_L0_2_jnt'],
    ['Bone_LFLeg15', 'legB_L0_4_jnt'],
    ['Bone_LegEnd04', 'legB_L0_6_jnt'],
    ['Bone_LFLeg09', 'legB_R0_0_jnt'],
    ['Bone_LFLeg10', 'legB_R0_2_jnt'],
    ['Bone_LFLeg11', 'legB_R0_4_jnt'],
    ['Bone_LegEnd02', 'legB_R0_6_jnt'],
    ['Bone_BodyShieldR', 'thorax_armor_L0_0_jnt'],
    ['Bone_BodyShieldL', 'thorax_armor_R0_0_jnt'],
];
