export const character = 11;
export const fighter = 'Beastmaster';
export const stockPath = 'war3.w3mod:_de.w3mod:units\\creeps\\BeastMaster\\BeastMaster.mdx';
export const classic = {
    pelvis: 'Bone_Pelvis',
    chest: 'Bone_Chest',
    head: 'Bone_Head',
    'shoulder.L': 'Bone_Arm1_L',
    'elbow.L': 'Bone_Arm2_L',
    'wrist.L': 'Bone_Hand_L',
    'hip.L': 'Bone_Leg1_L',
    'knee.L': 'Bone_Leg2_L',
    'ankle.L': 'Bone_Foot_L',
    'shoulder.R': 'Bone_Arm1_R',
    'elbow.R': 'Bone_Arm2_R',
    'wrist.R': 'Bone_Hand_R',
    'hip.R': 'Bone_Leg1_R',
    'knee.R': 'Bone_Leg2_R',
    'ankle.R': 'Bone_Foot_R',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['Origin Ref ', 'local_C0_0_jnt'], ['pelvis', 'spine_C0_0_jnt'],
    ['chest', 'spine_C0_1_jnt'], ['chest', 'bone_chest'],
    ['head', 'neck_C0_0_jnt'], ['head', 'bone_head'],
    ['wrist.L', 'Wep01_L0_0_jnt'], ['wrist.R', 'Wep01_R0_0_jnt'],
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['shoulder.L', 'arm_L0_1_jnt'], ['elbow.L', 'arm_L0_2_jnt'],
    ['elbow.L', 'arm_L0_3_jnt'], ['wrist.L', 'arm_L0_4_jnt'],
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['shoulder.R', 'arm_R0_1_jnt'], ['elbow.R', 'arm_R0_2_jnt'],
    ['elbow.R', 'arm_R0_3_jnt'], ['wrist.R', 'arm_R0_4_jnt'],
    ['hip.L', 'leg_L0_0_jnt'], ['hip.L', 'leg_L0_1_jnt'],
    ['knee.L', 'leg_L0_2_jnt'], ['knee.L', 'leg_L0_3_jnt'],
    ['ankle.L', 'leg_L0_4_jnt'], ['ankle.L', 'foot_L0_0_jnt'],
    ['hip.R', 'leg_R0_0_jnt'], ['hip.R', 'leg_R0_1_jnt'],
    ['knee.R', 'leg_R0_2_jnt'], ['knee.R', 'leg_R0_3_jnt'],
    ['ankle.R', 'leg_R0_4_jnt'], ['ankle.R', 'foot_R0_0_jnt'],
    ['Bone Robe', 'cloak_C0_0_jnt'], ['Bone Robe', 'cloak_C0_1_jnt'],
    ['Bone Robe B', 'cloak_C0_2_jnt'], ['Bone Robe B', 'cloak_C0_3_jnt'],
    ['Bone Robe B', 'cloak_C0_4_jnt'], ['Bone Loine', 'loin_C0_0_jnt'],
    ['Bone Coat A', 'Mask_L0_0_jnt'], ['Bone Coat A', 'Mask_L0_1_jnt'],
    ['Bone Coat A', 'Mask_L0_2_jnt'], ['Bone PAD', 'Pauldron_R0_0_jnt'],
    ['Bone PAD', 'Mask_R0_0_jnt'], ['Bone Coat C', 'Mask_R0_1_jnt'],
    ['Bone Coat C', 'Mask_R0_2_jnt'],
];
