export const character = 16;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\orc\\HeroTaurenChieftain\\HeroTaurenChieftain.mdx';
export const fitScale = 0.762;
export const classic = {
    root: 'Root',
    pelvis: 'Bone_Pelvis',
    chest: 'Bone_Chest',
    neck: 'Bone_Neck',
    head: 'Bone_Head',
    'clavicle.L': 'Bone_ClavicalL',
    'shoulder.L': 'Bone_UpperArmL',
    'elbow.L': 'Bone_LowerArmL',
    'wrist.L': 'Bone_HandL',
    'hip.L': 'Bone_UpperlegL',
    'knee.L': 'Bone_Leg2L',
    'ankle.L': 'Bone_Leg3L',
    'toe.L': 'Bone_FootL',
    'clavicle.R': 'Bone_ClavicalR',
    'shoulder.R': 'Bone_UpperArmR',
    'elbow.R': 'Bone_LowerArmR',
    'wrist.R': 'Bone_HandR',
    'hip.R': 'Bone_UpperlegR',
    'knee.R': 'Bone_Leg2R',
    'ankle.R': 'Bone_Leg3R',
    'toe.R': 'Bone_FootR',
    weapon: 'Axe',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['root', 'root'],
    ['chest', 'bone_chest'],
    ['neck', 'neck'],
    ['head', 'bone_head'],
    ['pelvis', 'pelvis'],
    ['Bone_Totum', 'totem'],
    ['weapon', 'weapon'],
    ['clavicle.L', 'scapula_L'],
    ['shoulder.L', 'scapula_L|shoulder_l'],
    ['elbow.L', 'elbow_L'],
    ['wrist.L', 'wrist_L'],
    ['hip.L', 'hip_L'],
    ['knee.L', 'knee_L'],
    ['ankle.L', 'ankle_L'],
    ['toe.L', 'toes_L'],
    ['clavicle.R', 'scapula_R'],
    ['shoulder.R', 'scapula_R|shoulder_l'],
    ['elbow.R', 'elbow_R'],
    ['wrist.R', 'wrist_R'],
    ['hip.R', 'hip_R'],
    ['knee.R', 'knee_R'],
    ['ankle.R', 'ankle_R'],
    ['toe.R', 'toes_R'],
    ['Bone_Tail1', 'tail1'],
    ['Bone_Tail2', 'tail2'],
    ['Bone_Tail3', 'tail3'],
    ['Bone_Tail4', 'tail4'],
];
