export const character = 17;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\creeps\\PandarenBrewmaster\\PandarenBrewmaster.mdx';

export const pairs: readonly (readonly [string, string])[] = [
    ['Bone_Pelvis', 'spine_C0_0_jnt'],
    ['Bone_Chest', 'bone_chest'],
    ['Bone_Head', 'neck_C0_0_jnt'],
    ['Bone_Head', 'bone_head'],
    ['Bone_Arm1_L', 'arm_L0_0_jnt'],
    ['Bone_Arm2_L', 'arm_L0_2_jnt'],
    ['Bone_Hand_L', 'meta_L0_0_jnt'],
    ['Bone_Arm1_R', 'arm_R0_0_jnt'],
    ['Bone_Arm2_R', 'arm_R0_2_jnt'],
    ['Bone_Hand_R', 'meta_R0_0_jnt'],
    ['Box02', 'Wep01_L0_0_jnt'],
    ['Bone Rope', 'tiedjar_L0_0_jnt'],
    ['Mesh10', 'Wep01_R0_0_jnt'],
    ['Bone_Leg1_L', 'leg_L0_0_jnt'],
    ['Bone_Leg2_L', 'leg_L0_2_jnt'],
    ['Bone_Foot_L', 'foot_L0_0_jnt'],
    ['Bone_Leg1_R', 'leg_R0_0_jnt'],
    ['Bone_Leg2_R', 'leg_R0_2_jnt'],
    ['Bone_Foot_R', 'foot_R0_0_jnt'],
    ['Box01', 'hat_C0_0_jnt'],
    ['Mesh30', 'robe_L0_0_jnt'],
    ['Mesh19', 'robe_L0_1_jnt'],
    ['Mesh31', 'robe_R0_0_jnt'],
    ['Mesh20', 'robe_R0_1_jnt'],
    ['Mesh18', 'robeback_C0_0_jnt'],
    ['Mesh27', 'robeback_C0_1_jnt'],
    ['Mesh28', 'robeback_C0_2_jnt'],
    ['Mesh11', 'robefront_C0_0_jnt'],
    ['Mesh26', 'robefront_C0_1_jnt'],
];
