export const character = 17;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\creeps\\PandarenBrewmaster\\PandarenBrewmaster.mdx';

export const classic = {
    root: 'Bone_Root',
    pelvis: 'Bone_Pelvis',
    chest: 'Bone_Chest',
    head: 'Bone_Head',
    'shoulder.L': 'Bone_Arm1_L',
    'elbow.L': 'Bone_Arm2_L',
    'wrist.L': 'Bone_Hand_L',
    'hip.L': 'Bone_Leg1_L',
    'knee.L': 'Bone_Leg2_L',
    'ankle.L': 'Bone_Foot_L',
    'shoulder.R': 'Bone_Arm1_R',
    'elbow.R': 'Bone_Arm2_R',
    'wrist.R': 'Bone_Hand_R',
    'hip.R': 'Bone_Leg1_R',
    'knee.R': 'Bone_Leg2_R',
    'ankle.R': 'Bone_Foot_R',
    weapon: 'Mesh10',
    'weapon.L': 'Box02',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['pelvis', 'spine_C0_0_jnt'],
    ['chest', 'bone_chest'],
    ['head', 'neck_C0_0_jnt'],
    ['head', 'bone_head'],
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['elbow.L', 'arm_L0_2_jnt'],
    ['wrist.L', 'meta_L0_0_jnt'],
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['elbow.R', 'arm_R0_2_jnt'],
    ['wrist.R', 'meta_R0_0_jnt'],
    ['weapon.L', 'Wep01_L0_0_jnt'],
    ['Bone Rope', 'tiedjar_L0_0_jnt'],
    ['weapon', 'Wep01_R0_0_jnt'],
    ['hip.L', 'leg_L0_0_jnt'],
    ['knee.L', 'leg_L0_2_jnt'],
    ['ankle.L', 'foot_L0_0_jnt'],
    ['hip.R', 'leg_R0_0_jnt'],
    ['knee.R', 'leg_R0_2_jnt'],
    ['ankle.R', 'foot_R0_0_jnt'],
    ['Box01', 'hat_C0_0_jnt'],
    ['Mesh30', 'robe_L0_0_jnt'],
    ['Mesh19', 'robe_L0_1_jnt'],
    ['Mesh31', 'robe_R0_0_jnt'],
    ['Mesh20', 'robe_R0_1_jnt'],
    ['Mesh18', 'robeback_C0_0_jnt'],
    ['Mesh27', 'robeback_C0_1_jnt'],
    ['Mesh28', 'robeback_C0_2_jnt'],
    ['Mesh11', 'robefront_C0_0_jnt'],
    ['Mesh26', 'robefront_C0_1_jnt'],
];
export const fitScale = 0.8;
