export const character = 8;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\undead\\herodreadlord\\herodreadlord.mdx';

// Classic wing meshes are articulated under the chest; the DE rig names their fingers.
export const classic = {
    root: 'Bone_Root',
    pelvis: 'Bone_Pelvis',
    chest: 'Bone_Chest',
    head: 'Bone_Head',
    'shoulder.L': 'Bone_Arm1_L',
    'elbow.L': 'Bone_Arm2_L',
    'wrist.L': 'Bone_Hand_L',
    'hip.L': 'Bone_Leg1_L',
    'knee.L': 'Bone_Leg2_L',
    'ankle.L': 'Bone_Foot_L',
    'shoulder.R': 'Bone_Arm1_R',
    'elbow.R': 'Bone_Arm2_R',
    'wrist.R': 'Bone_Hand_R',
    'hip.R': 'Bone_Leg1_R',
    'knee.R': 'Bone_Leg2_R',
    'ankle.R': 'Bone_Foot_R',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['root', 'local_C0_0_jnt'],
    ['pelvis', 'spine_C0_0_jnt'],
    ['chest', 'spine_C0_1_jnt'],
    ['chest', 'bone_chest'],
    ['head', 'neck_C0_0_jnt'],
    ['head', 'bone_head'],
    
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['elbow.L', 'arm_L0_2_jnt'],
    ['wrist.L', 'arm_L0_4_jnt'],
    
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['elbow.R', 'arm_R0_2_jnt'],
    ['wrist.R', 'arm_R0_4_jnt'],
    ['Bone Thumb L', 'thumb_L0_0_jnt'],
    ['Bone Thumb R', 'thumb_R0_0_jnt'],
    ['Bone Wrist R', 'finger_L1_0_jnt'],
    ['Bone Finger R', 'finger_L1_2_jnt'],
    ['Bone Wrist L', 'finger_R1_0_jnt'],
    ['Bone Finger L', 'finger_R1_2_jnt'],
    ['hip.L', 'leg_L0_0_jnt'],
    ['knee.L', 'leg_L0_2_jnt'],
    ['knee.L', 'leg_L0_4_jnt'],
    ['ankle.L', 'leg_L0_6_jnt'],
    ['ankle.L', 'foot_L0_0_jnt'],
    ['hip.R', 'leg_R0_0_jnt'],
    ['knee.R', 'leg_R0_2_jnt'],
    ['knee.R', 'leg_R0_4_jnt'],
    ['ankle.R', 'leg_R0_6_jnt'],
    ['ankle.R', 'foot_R0_0_jnt'],
    ['New Wings', 'wing_L0_0_jnt'],
    ['New Wings', 'wing_L0_2_jnt'],
    ['Object19', 'wing_L0_4_jnt'],
    ['Object21', 'wingThumb_L0_0_jnt'],
    ['Object19', 'wingIndexFinger_L0_0_jnt'],
    ['Object20', 'wingIndexFinger_L0_1_jnt'],
    ['Mesh04', 'wingIndexFinger_L0_2_jnt'],
    ['Object21', 'wingMidFinger_L0_0_jnt'],
    ['Object10', 'wingMidFinger_L0_1_jnt'],
    ['Mesh74', 'wingMidFinger_L0_2_jnt'],
    ['Object21', 'wingRingFinger_L0_0_jnt'],
    ['Object10', 'wingRingFinger_L0_1_jnt'],
    ['Mesh74', 'wingRingFinger_L0_2_jnt'],
    ['Mesh67', 'wing_R0_0_jnt'],
    ['Mesh67', 'wing_R0_2_jnt'],
    ['Mesh71', 'wing_R0_4_jnt'],
    ['Mesh73', 'wingThumb_R0_0_jnt'],
    ['Mesh71', 'wingIndexFinger_R0_0_jnt'],
    ['Mesh72', 'wingIndexFinger_R0_1_jnt'],
    ['Mesh69', 'wingIndexFinger_R0_2_jnt'],
    ['Mesh73', 'wingMidFinger_R0_0_jnt'],
    ['Mesh70', 'wingMidFinger_R0_1_jnt'],
    ['Mesh75', 'wingMidFinger_R0_2_jnt'],
    ['Mesh73', 'wingRingFinger_R0_0_jnt'],
    ['Mesh70', 'wingRingFinger_R0_1_jnt'],
    ['Mesh75', 'wingRingFinger_R0_2_jnt'],
    ['Mesh05', 'tail_C0_0_jnt'],
    ['Object05', 'tail_C0_1_jnt'],
    ['Object04', 'tail_C0_2_jnt'],
    ['Object04', 'tail_C0_3_jnt'],
    ['AMesh09', 'loin_C0_0_jnt'],
    ['AMesh09', 'loin_C0_1_jnt'],
    ['AMesh09', 'loin_C0_2_jnt'],
];
