export const stockPath = 'war3.w3mod:_de.w3mod:units\\undead\\herodreadlord\\herodreadlord.mdx';

// Classic wing meshes are articulated under the chest; the DE rig names their fingers.
export const pairs: readonly (readonly [string, string])[] = [
    ['Bone_Root', 'local_C0_0_jnt'],
    ['Bone_Pelvis', 'spine_C0_0_jnt'],
    ['Bone_Root', 'spine_C0_1_jnt'],
    ['Bone_Chest', 'bone_chest'],
    ['Bone_Head', 'neck_C0_0_jnt'],
    ['Bone_Head', 'bone_head'],
    ['Bone_Arm1_L', 'shoulder_L0_shoulder_jnt'],
    ['Bone_Arm1_L', 'arm_L0_0_jnt'],
    ['Bone_Arm2_L', 'arm_L0_2_jnt'],
    ['Bone_Hand_L', 'arm_L0_4_jnt'],
    ['Bone_Arm1_R', 'shoulder_R0_shoulder_jnt'],
    ['Bone_Arm1_R', 'arm_R0_0_jnt'],
    ['Bone_Arm2_R', 'arm_R0_2_jnt'],
    ['Bone_Hand_R', 'arm_R0_4_jnt'],
    ['Bone Thumb L', 'thumb_L0_0_jnt'],
    ['Bone Thumb R', 'thumb_R0_0_jnt'],
    ['Bone Wrist R', 'finger_L1_0_jnt'],
    ['Bone Finger R', 'finger_L1_2_jnt'],
    ['Bone Wrist L', 'finger_R1_0_jnt'],
    ['Bone Finger L', 'finger_R1_2_jnt'],
    ['Bone_Leg1_L', 'leg_L0_0_jnt'],
    ['Bone_Leg2_L', 'leg_L0_2_jnt'],
    ['Bone_Leg2_L', 'leg_L0_4_jnt'],
    ['Bone_Foot_L', 'leg_L0_6_jnt'],
    ['Bone_Foot_L', 'foot_L0_0_jnt'],
    ['Bone_Leg1_R', 'leg_R0_0_jnt'],
    ['Bone_Leg2_R', 'leg_R0_2_jnt'],
    ['Bone_Leg2_R', 'leg_R0_4_jnt'],
    ['Bone_Foot_R', 'leg_R0_6_jnt'],
    ['Bone_Foot_R', 'foot_R0_0_jnt'],
    ['New Wings', 'wing_L0_0_jnt'],
    ['New Wings', 'wing_L0_2_jnt'],
    ['Object19', 'wing_L0_4_jnt'],
    ['Object21', 'wingThumb_L0_0_jnt'],
    ['Object19', 'wingIndexFinger_L0_0_jnt'],
    ['Object20', 'wingIndexFinger_L0_1_jnt'],
    ['Mesh04', 'wingIndexFinger_L0_2_jnt'],
    ['Object21', 'wingMidFinger_L0_0_jnt'],
    ['Object10', 'wingMidFinger_L0_1_jnt'],
    ['Mesh74', 'wingMidFinger_L0_2_jnt'],
    ['Object21', 'wingRingFinger_L0_0_jnt'],
    ['Object10', 'wingRingFinger_L0_1_jnt'],
    ['Mesh74', 'wingRingFinger_L0_2_jnt'],
    ['Mesh67', 'wing_R0_0_jnt'],
    ['Mesh67', 'wing_R0_2_jnt'],
    ['Mesh71', 'wing_R0_4_jnt'],
    ['Mesh73', 'wingThumb_R0_0_jnt'],
    ['Mesh71', 'wingIndexFinger_R0_0_jnt'],
    ['Mesh72', 'wingIndexFinger_R0_1_jnt'],
    ['Mesh69', 'wingIndexFinger_R0_2_jnt'],
    ['Mesh73', 'wingMidFinger_R0_0_jnt'],
    ['Mesh70', 'wingMidFinger_R0_1_jnt'],
    ['Mesh75', 'wingMidFinger_R0_2_jnt'],
    ['Mesh73', 'wingRingFinger_R0_0_jnt'],
    ['Mesh70', 'wingRingFinger_R0_1_jnt'],
    ['Mesh75', 'wingRingFinger_R0_2_jnt'],
    ['Mesh05', 'tail_C0_0_jnt'],
    ['Object05', 'tail_C0_1_jnt'],
    ['Object04', 'tail_C0_2_jnt'],
    ['Object04', 'tail_C0_3_jnt'],
    ['AMesh09', 'loin_C0_0_jnt'],
    ['AMesh09', 'loin_C0_1_jnt'],
    ['AMesh09', 'loin_C0_2_jnt'],
];
