export const character = 7;
export const fighter = "ForsakenPaladin";
export const stockPath = "war3.w3mod:_de.w3mod:units/creeps/heroforsakenpaladin/heroforsakenpaladin.mdx";
export const classic = {
    root: 'local_C0_0_jnt',
    pelvis: 'spine_C0_0_jnt',
    chest: 'bone_chest',
    neck: 'neck_C0_0_jnt',
    head: 'bone_head',
    'clavicle.L': 'shoulder_L0_shoulder_jnt',
    'shoulder.L': 'arm_L0_0_jnt',
    'elbow.L': 'arm_L0_2_jnt',
    'wrist.L': 'arm_L0_end_jnt',
    'hip.L': 'leg_L0_0_jnt',
    'knee.L': 'leg_L0_2_jnt',
    'ankle.L': 'leg_L0_end_jnt',
    'toe.L': 'foot_L0_0_jnt',
    'clavicle.R': 'shoulder_R0_shoulder_jnt',
    'shoulder.R': 'arm_R0_0_jnt',
    'elbow.R': 'arm_R0_2_jnt',
    'wrist.R': 'arm_R0_end_jnt',
    'hip.R': 'leg_R0_0_jnt',
    'knee.R': 'leg_R0_2_jnt',
    'ankle.R': 'leg_R0_end_jnt',
    'toe.R': 'foot_R0_0_jnt',
    weapon: 'Wep01_R0_0_jnt',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ["root","local_C0_0_jnt"],
    ["pelvis","spine_C0_0_jnt"],
    ["spine_C0_1_jnt","spine_C0_1_jnt"],
    ["shoulder.L","arm_L0_0_jnt"],
    ["arm_L0_1_jnt","arm_L0_1_jnt"],
    ["elbow.L","arm_L0_2_jnt"],
    ["arm_L0_3_jnt","arm_L0_3_jnt"],
    ["arm_L0_4_jnt","arm_L0_4_jnt"],
    ["wrist.L","arm_L0_end_jnt"],
    ["meta_L0_0_jnt","meta_L0_0_jnt"],
    ["meta_L0_1_jnt","meta_L0_1_jnt"],
    ["meta_L0_3_jnt","meta_L0_3_jnt"],
    ["finger_L3_0_jnt","finger_L3_0_jnt"],
    ["finger_L3_1_jnt","finger_L3_1_jnt"],
    ["finger_L0_0_jnt","finger_L0_0_jnt"],
    ["thumb_L0_0_jnt","thumb_L0_0_jnt"],
    ["thumb_L0_1_jnt","thumb_L0_1_jnt"],
    ["thumb_L0_2_jnt","thumb_L0_2_jnt"],
    ["hip.L","leg_L0_0_jnt"],
    ["leg_L0_1_jnt","leg_L0_1_jnt"],
    ["leg_L0_3_jnt","leg_L0_3_jnt"],
    ["kneecap_L0_0_jnt","kneecap_L0_0_jnt"],
    ["buckle_C0_0_jnt","buckle_C0_0_jnt"],
    ["loin_C0_0_jnt","loin_C0_0_jnt"],
    ["loin_C0_1_jnt","loin_C0_1_jnt"],
    ["loin_C0_2_jnt","loin_C0_2_jnt"],
    ["book_C0_0_jnt","book_C0_0_jnt"],
    ["chest","bone_chest"],
    ["clavicle.L","shoulder_L0_shoulder_jnt"],
    ["meta_L0_2_jnt","meta_L0_2_jnt"],
    ["finger_L3_2_jnt","finger_L3_2_jnt"],
    ["finger_L2_0_jnt","finger_L2_0_jnt"],
    ["finger_L2_1_jnt","finger_L2_1_jnt"],
    ["finger_L1_0_jnt","finger_L1_0_jnt"],
    ["finger_L1_1_jnt","finger_L1_1_jnt"],
    ["finger_L0_1_jnt","finger_L0_1_jnt"],
    ["finger_L0_2_jnt","finger_L0_2_jnt"],
    ["Greaves_L0_0_jnt","Greaves_L0_0_jnt"],
    ["pauldron_L0_0_jnt","pauldron_L0_0_jnt"],
    ["neck","neck_C0_0_jnt"],
    ["neck_C0_1_jnt","neck_C0_1_jnt"],
    ["neck_C0_2_jnt","neck_C0_2_jnt"],
    ["head","bone_head"],
    ["ffx_mouth_C0_jaw_jnt","ffx_mouth_C0_jaw_jnt"],
    ["ffx_mouth_C0_liplow_jnt","ffx_mouth_C0_liplow_jnt"],
    ["ffx_mouth_C0_lipleft_jnt","ffx_mouth_C0_lipleft_jnt"],
    ["ffx_mouth_C0_lipright_jnt","ffx_mouth_C0_lipright_jnt"],
    ["ffx_mouth_C0_teethlow_jnt","ffx_mouth_C0_teethlow_jnt"],
    ["ffx_mouth_C0_tongue_01_jnt","ffx_mouth_C0_tongue_01_jnt"],
    ["ffx_mouth_C0_tongue_02_jnt","ffx_mouth_C0_tongue_02_jnt"],
    ["ffx_mouth_C0_tongue_03_jnt","ffx_mouth_C0_tongue_03_jnt"],
    ["ffx_mouth_C0_lipup_jnt","ffx_mouth_C0_lipup_jnt"],
    ["ffx_mouth_C0_teethup_jnt","ffx_mouth_C0_teethup_jnt"],
    ["ffx_eye_L0_eye_jnt","ffx_eye_L0_eye_jnt"],
    ["ffx_eye_L0_eyeOver_jnt","ffx_eye_L0_eyeOver_jnt"],
    ["ffx_eye_L0_eyelidupper_jnt","ffx_eye_L0_eyelidupper_jnt"],
    ["ffx_eye_L0_eyelidlower_jnt","ffx_eye_L0_eyelidlower_jnt"],
    ["ffx_eye_L0_brow_jnt","ffx_eye_L0_brow_jnt"],
    ["ffx_eye_R0_eye_jnt","ffx_eye_R0_eye_jnt"],
    ["ffx_eye_R0_eyeOver_jnt","ffx_eye_R0_eyeOver_jnt"],
    ["ffx_eye_R0_eyelidupper_jnt","ffx_eye_R0_eyelidupper_jnt"],
    ["ffx_eye_R0_eyelidlower_jnt","ffx_eye_R0_eyelidlower_jnt"],
    ["ffx_eye_R0_brow_jnt","ffx_eye_R0_brow_jnt"],
    ["clavicle.R","shoulder_R0_shoulder_jnt"],
    ["shoulder.R","arm_R0_0_jnt"],
    ["arm_R0_1_jnt","arm_R0_1_jnt"],
    ["elbow.R","arm_R0_2_jnt"],
    ["arm_R0_3_jnt","arm_R0_3_jnt"],
    ["arm_R0_4_jnt","arm_R0_4_jnt"],
    ["wrist.R","arm_R0_end_jnt"],
    ["meta_R0_0_jnt","meta_R0_0_jnt"],
    ["meta_R0_1_jnt","meta_R0_1_jnt"],
    ["meta_R0_2_jnt","meta_R0_2_jnt"],
    ["meta_R0_3_jnt","meta_R0_3_jnt"],
    ["finger_R3_0_jnt","finger_R3_0_jnt"],
    ["finger_R3_1_jnt","finger_R3_1_jnt"],
    ["finger_R3_2_jnt","finger_R3_2_jnt"],
    ["finger_R2_0_jnt","finger_R2_0_jnt"],
    ["finger_R2_1_jnt","finger_R2_1_jnt"],
    ["finger_R1_0_jnt","finger_R1_0_jnt"],
    ["finger_R1_1_jnt","finger_R1_1_jnt"],
    ["finger_R0_0_jnt","finger_R0_0_jnt"],
    ["finger_R0_1_jnt","finger_R0_1_jnt"],
    ["finger_R0_2_jnt","finger_R0_2_jnt"],
    ["thumb_R0_0_jnt","thumb_R0_0_jnt"],
    ["thumb_R0_1_jnt","thumb_R0_1_jnt"],
    ["thumb_R0_2_jnt","thumb_R0_2_jnt"],
    ["Greaves_R0_0_jnt","Greaves_R0_0_jnt"],
    ["pauldron_R0_0_jnt","pauldron_R0_0_jnt"],
    ["cloak_R0_0_jnt","cloak_R0_0_jnt"],
    ["cloak_R0_1_jnt","cloak_R0_1_jnt"],
    ["cloak_R0_2_jnt","cloak_R0_2_jnt"],
    ["cloak_R0_3_jnt","cloak_R0_3_jnt"],
    ["cloak_R0_4_jnt","cloak_R0_4_jnt"],
    ["cloak_C0_0_jnt","cloak_C0_0_jnt"],
    ["cloak_C0_1_jnt","cloak_C0_1_jnt"],
    ["cloak_C0_2_jnt","cloak_C0_2_jnt"],
    ["cloak_C0_3_jnt","cloak_C0_3_jnt"],
    ["cloak_C0_4_jnt","cloak_C0_4_jnt"],
    ["knee.L","leg_L0_2_jnt"],
    ["leg_L0_4_jnt","leg_L0_4_jnt"],
    ["ankle.L","leg_L0_end_jnt"],
    ["toe.L","foot_L0_0_jnt"],
    ["foot_L0_1_jnt","foot_L0_1_jnt"],
    ["loin_C0_3_jnt","loin_C0_3_jnt"],
    ["loin_C0_4_jnt","loin_C0_4_jnt"],
    ["loinback_C0_0_jnt","loinback_C0_0_jnt"],
    ["loinback_C0_1_jnt","loinback_C0_1_jnt"],
    ["loinback_C0_2_jnt","loinback_C0_2_jnt"],
    ["loinback_C0_3_jnt","loinback_C0_3_jnt"],
    ["loinback_C0_4_jnt","loinback_C0_4_jnt"],
    ["hip.R","leg_R0_0_jnt"],
    ["leg_R0_1_jnt","leg_R0_1_jnt"],
    ["knee.R","leg_R0_2_jnt"],
    ["leg_R0_3_jnt","leg_R0_3_jnt"],
    ["leg_R0_4_jnt","leg_R0_4_jnt"],
    ["ankle.R","leg_R0_end_jnt"],
    ["toe.R","foot_R0_0_jnt"],
    ["foot_R0_1_jnt","foot_R0_1_jnt"],
    ["kneecap_R0_0_jnt","kneecap_R0_0_jnt"],
    ["weapon","Wep01_R0_0_jnt"],
];
