export const character = 20;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\human\\herobloodelf\\herobloodelf.mdx';
export const classic = {
    root: 'Bone_Root',
    pelvis: 'Bone_Pelvis',
    chest: 'Bone_Chest',
    head: 'Bone_Head',
    'shoulder.L': 'Bone_Arm1_L',
    'elbow.L': 'Bone_Arm2_L',
    'wrist.L': 'Bone_Hand_L',
    'hip.L': 'Bone_Leg1_L',
    'knee.L': 'Bone_Leg2_L',
    'ankle.L': 'Bone_Foot_L',
    'shoulder.R': 'Bone_Arm1_R',
    'elbow.R': 'Bone_Arm2_R',
    'wrist.R': 'Bone_Hand_R',
    'hip.R': 'Bone_Leg1_R',
    'knee.R': 'Bone_Leg2_R',
    'ankle.R': 'Bone_Foot_R',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['pelvis', 'spine_C0_0_jnt'],
    ['chest', 'bone_chest'],
    ['head', 'bone_head'],
    ['Jaw', 'ffx_mouth_C0_jaw_jnt'],
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['elbow.L', 'arm_L0_2_jnt'],
    ['wrist.L', 'arm_L0_end_jnt'],
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['elbow.R', 'arm_R0_2_jnt'],
    ['wrist.R', 'arm_R0_end_jnt'],
    ['hip.L', 'leg_L0_0_jnt'],
    ['knee.L', 'leg_L0_2_jnt'],
    ['ankle.L', 'leg_L0_end_jnt'],
    ['hip.R', 'leg_R0_0_jnt'],
    ['knee.R', 'leg_R0_2_jnt'],
    ['ankle.R', 'leg_R0_end_jnt'],
    ['Mesh20', 'cape_C0_0_jnt'],
    ['Object11', 'cape_mid_L0_0_jnt'],
    ['Mesh24', 'cape_mid_L0_2_jnt'],
    ['Mesh18', 'cape_mid_L0_4_jnt'],
    ['Object10', 'cape_mid_R0_0_jnt'],
    ['Mesh23', 'cape_mid_R0_2_jnt'],
    ['Mesh17', 'cape_mid_R0_4_jnt'],
    ['robe', 'cape_side_L0_0_jnt'],
    ['Mesh26', 'cape_side_L0_2_jnt'],
    ['Mesh21', 'cape_side_L0_4_jnt'],
    ['Mesh29', 'cape_side_R0_0_jnt'],
    ['Mesh30', 'cape_side_R0_2_jnt'],
    ['Mesh31', 'cape_side_R0_4_jnt'],
    ['Object12', 'cape_front_L0_0_jnt'],
    ['Mesh25', 'cape_front_L0_2_jnt'],
    ['Mesh19', 'cape_front_L0_4_jnt'],
    ['Object09', 'cape_front_R0_0_jnt'],
    ['Mesh22', 'cape_front_R0_2_jnt'],
    ['Mesh16', 'cape_front_R0_4_jnt'],
];
export const fitScale = 1.08;
