export const stockPath = 'war3.w3mod:_de.w3mod:units\\human\\herobloodelf\\herobloodelf.mdx';
export const pairs: readonly (readonly [string, string])[] = [
    ['Bone_Pelvis', 'spine_C0_0_jnt'],
    ['Bone_Chest', 'bone_chest'],
    ['Bone_Head', 'bone_head'],
    ['Jaw', 'ffx_mouth_C0_jaw_jnt'],
    ['Bone_Arm1_L', 'arm_L0_0_jnt'],
    ['Bone_Arm2_L', 'arm_L0_2_jnt'],
    ['Bone_Hand_L', 'arm_L0_end_jnt'],
    ['Bone_Arm1_R', 'arm_R0_0_jnt'],
    ['Bone_Arm2_R', 'arm_R0_2_jnt'],
    ['Bone_Hand_R', 'arm_R0_end_jnt'],
    ['Bone_Leg1_L', 'leg_L0_0_jnt'],
    ['Bone_Leg2_L', 'leg_L0_2_jnt'],
    ['Bone_Foot_L', 'leg_L0_end_jnt'],
    ['Bone_Leg1_R', 'leg_R0_0_jnt'],
    ['Bone_Leg2_R', 'leg_R0_2_jnt'],
    ['Bone_Foot_R', 'leg_R0_end_jnt'],
    ['Mesh20', 'cape_C0_0_jnt'],
    ['Object11', 'cape_mid_L0_0_jnt'],
    ['Mesh24', 'cape_mid_L0_2_jnt'],
    ['Mesh18', 'cape_mid_L0_4_jnt'],
    ['Object10', 'cape_mid_R0_0_jnt'],
    ['Mesh23', 'cape_mid_R0_2_jnt'],
    ['Mesh17', 'cape_mid_R0_4_jnt'],
    ['robe', 'cape_side_L0_0_jnt'],
    ['Mesh26', 'cape_side_L0_2_jnt'],
    ['Mesh21', 'cape_side_L0_4_jnt'],
    ['Mesh29', 'cape_side_R0_0_jnt'],
    ['Mesh30', 'cape_side_R0_2_jnt'],
    ['Mesh31', 'cape_side_R0_4_jnt'],
    ['Object12', 'cape_front_L0_0_jnt'],
    ['Mesh25', 'cape_front_L0_2_jnt'],
    ['Mesh19', 'cape_front_L0_4_jnt'],
    ['Object09', 'cape_front_R0_0_jnt'],
    ['Mesh22', 'cape_front_R0_2_jnt'],
    ['Mesh16', 'cape_front_R0_4_jnt'],
];
export const fitScale = 1.08;
