export const character = 6;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\undead\\herolich\\herolich.mdx';
// The floating robe's lengths otherwise place the head 54% above the Classic body's height (#362).
export const fitScale = 0.65;
// The robe hem floats where Classic's does, so low strikes reach the same regions.
export const alignRoot = true;

// Lich has a floating torso and eight robe strips, rather than a leg rig.
export const classic = {
    root: 'Bone_Root',
    chest: 'Cylinder01',
    neck: 'Bone NECK',
    head: 'Bone_Head',
    'shoulder.L': 'Cylinder07',
    'elbow.L': 'Mesh05',
    'wrist.L': 'Mesh03',
    'shoulder.R': 'Cylinder06',
    'elbow.R': 'Mesh04',
    'wrist.R': 'Mesh02',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['root', 'spine_C0_0_jnt'],
    ['Mesh01', 'spine_C0_1_jnt'],
    ['chest', 'bone_chest'],
    ['neck', 'neck_C0_0_jnt'],
    ['head', 'bone_head'],
    ['shoulder.L', 'shoulder_L0_shoulder_jnt'],
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['elbow.L', 'arm_L0_2_jnt'],
    ['wrist.L', 'arm_L0_4_jnt'],
    ['shoulder.R', 'shoulder_R0_shoulder_jnt'],
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['elbow.R', 'arm_R0_2_jnt'],
    ['wrist.R', 'arm_R0_4_jnt'],
    ['Box20', 'ElbowChain_L0_0_jnt'],
    ['Mesh06', 'ElbowChain_L0_2_jnt'],
    ['Box21', 'HandChain_L0_0_jnt'],
    ['Mesh11', 'HandChain_L0_1_jnt'],
    ['Mesh09', 'HandChain_L0_3_jnt'],
    ['Box19', 'ElbowChain_R0_0_jnt'],
    ['Mesh07', 'ElbowChain_R0_2_jnt'],
    ['Box01', 'HandChain_R0_0_jnt'],
    ['Mesh10', 'HandChain_R0_1_jnt'],
    ['Mesh08', 'HandChain_R0_3_jnt'],
    ['Box34', 'cloak_L0_0_jnt'],
    ['Mesh16', 'cloak_L0_1_jnt'],
    ['Mesh14', 'cloak_L0_2_jnt'],
    ['Mesh12', 'cloak_L0_3_jnt'],
    ['Mesh36', 'cloak_L0_4_jnt'],
    ['Box33', 'cloak_L1_0_jnt'],
    ['Mesh22', 'cloak_L1_1_jnt'],
    ['Mesh20', 'cloak_L1_2_jnt'],
    ['Mesh18', 'cloak_L1_3_jnt'],
    ['Mesh18', 'cloak_L1_4_jnt'],
    ['Box32', 'cloak_L2_0_jnt'],
    ['Mesh23', 'cloak_L2_1_jnt'],
    ['Mesh21', 'cloak_L2_2_jnt'],
    ['Mesh19', 'cloak_L2_3_jnt'],
    ['Mesh19', 'cloak_L2_4_jnt'],
    ['Box31', 'cloak_L3_0_jnt'],
    ['Mesh34', 'cloak_L3_1_jnt'],
    ['Mesh32', 'cloak_L3_2_jnt'],
    ['Mesh30', 'cloak_L3_3_jnt'],
    ['Mesh30', 'cloak_L3_4_jnt'],
    ['Box15', 'cloak_L4_0_jnt'],
    ['Mesh35', 'cloak_L4_1_jnt'],
    ['Mesh33', 'cloak_L4_2_jnt'],
    ['Mesh31', 'cloak_L4_3_jnt'],
    ['Mesh31', 'cloak_L4_4_jnt'],
    ['Box16', 'cloak_R3_0_jnt'],
    ['Mesh29', 'cloak_R3_1_jnt'],
    ['Mesh27', 'cloak_R3_2_jnt'],
    ['Mesh25', 'cloak_R3_3_jnt'],
    ['Mesh25', 'cloak_R3_4_jnt'],
    ['Box17', 'cloak_R2_0_jnt'],
    ['Mesh28', 'cloak_R2_1_jnt'],
    ['Mesh26', 'cloak_R2_2_jnt'],
    ['Mesh24', 'cloak_R2_3_jnt'],
    ['Mesh24', 'cloak_R2_4_jnt'],
    ['Box18', 'cloak_R1_0_jnt'],
    ['Mesh17', 'cloak_R1_1_jnt'],
    ['Mesh15', 'cloak_R1_2_jnt'],
    ['Mesh13', 'cloak_R1_3_jnt'],
    ['Mesh37', 'cloak_R1_4_jnt'],
];
