export const stockPath = 'war3.w3mod:_de.w3mod:units\\creeps\\murloc\\murloc.mdx';
export const pairs: readonly (readonly [string, string])[] = [
    ['Bone_Pelvis', 'spine_C0_0_jnt'],
    ['Bone_Waist', 'spine_C0_1_jnt'],
    ['Bone_Chest', 'bone_chest'],
    ['Bone_Head', 'bone_head'],
    ['Mouth01', 'ffx_mouth_C0_jaw_jnt'],
    ['Bone_Arm1_L', 'arm_L0_0_jnt'],
    ['Bone_Arm2_L', 'arm_L0_2_jnt'],
    ['Bone_Hand_L', 'arm_L0_end_jnt'],
    ['Bone_Arm1_R', 'arm_R0_0_jnt'],
    ['Bone_Arm2_R', 'arm_R0_2_jnt'],
    ['Bone_Hand_R', 'arm_R0_end_jnt'],
    ['Bone_Leg1_L', 'leg_L0_0_jnt'],
    ['Bone_Leg2_L', 'leg_L0_2_jnt'],
    ['Bone_Foot_L', 'leg_L0_end_jnt'],
    ['Bone_Leg1_R', 'leg_R0_0_jnt'],
    ['Bone_Leg2_R', 'leg_R0_2_jnt'],
    ['Bone_Foot_R', 'leg_R0_end_jnt'],
    ['Blade', 'Wep01_R0_0_jnt'],
    ['Bone_Hand_L', 'Shield_L0_0_jnt'],
    ['Mesh04', 'SideArm_C0_0_jnt'],
    ['Head01', 'HeadFrill_R0_0_jnt'],
    ['Head02', 'HeadFrill_L0_0_jnt'],
    ['Bone_Waist', 'MidSkike_C3_0_jnt'],
    ['Bone_Chest', 'MidSkike_C0_0_jnt'],
    ['Bone_Chest', 'UpperSkike_C3_0_jnt'],
    ['Bone_Chest', 'UpperSpike_L3_0_jnt'],
    ['Bone_Chest', 'UpperSpike_R3_0_jnt'],
    ['Bone_Pelvis', 'LowerSpike_L0_0_jnt'],
    ['Bone_Pelvis', 'LowerSpike_R0_0_jnt'],
];
