export const stockPath = 'war3.w3mod:_de.w3mod:units\\orc\\peon\\peon.mdx';
export const pairs: readonly (readonly [string, string])[] = [
    ['Bone_Pelvis', 'spine_C0_0_jnt'],
    ['Bone_Chest', 'bone_chest'],
    ['Bone_Head', 'bone_head'],
    ['Bone_Arm1_L', 'arm_L0_0_jnt'],
    ['Bone_Arm2_L', 'arm_L0_2_jnt'],
    ['Bone_Hand_L', 'arm_L0_end_jnt'],
    ['Bone_Arm1_R', 'arm_R0_0_jnt'],
    ['Bone_Arm2_R', 'arm_R0_2_jnt'],
    ['Bone_Hand_R', 'arm_R0_end_jnt'],
    ['Bone_Leg1_L', 'leg_L0_0_jnt'],
    ['Bone_Leg2_L', 'leg_L0_2_jnt'],
    ['Bone_Foot_L', 'leg_L0_end_jnt'],
    ['Bone_Leg1_R', 'leg_R0_0_jnt'],
    ['Bone_Leg2_R', 'leg_R0_2_jnt'],
    ['Bone_Foot_R', 'leg_R0_end_jnt'],
    ['axehandle', 'Wep01_L0_0_jnt'],
    ['GoldBag Root', 'bag_R0_0_jnt'],
    ['GoldBag2', 'bag_R1_0_jnt'],
    ['Mesh12', 'bag_R1_1_jnt'],
    ['Mesh06', 'bag_R2_0_jnt'],
    ['Lumber', 'Log_R0_0_jnt'],
];
