export const character = 10;
export const fighter = 'PitLord';
export const fitScale = 0.8;
export const limbScales = [['Wep01_R0_0_jnt', 0.78]] as const;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\demon\\HeroPitLord\\HeroPitLord.mdx';
export const classic = {
    pelvis: 'Bone Koto Waist01',
    chest: 'Bone_Chest',
    head: 'Bone_Head',
    'shoulder.L': 'Bone_Arm1_L',
    'elbow.L': 'Bone_Arm2_L',
    'wrist.L': 'Bone_Hand_L',
    'shoulder.R': 'Bone_Arm1_R',
    'elbow.R': 'Bone_Arm2_R',
    'wrist.R': 'Bone_Hand_R',
    weapon: 'Real BLADE',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['pelvis', 'back_C0_0_jnt'], ['Bone Center01', 'back_C0_1_jnt'],
    ['Bone Koto Neck02', 'back_C0_2_jnt'], ['chest', 'spine_C0_0_jnt'],
    ['chest', 'spine_C0_1_jnt'], ['chest', 'bone_chest'],
    ['head', 'neck_C0_0_jnt'], ['head', 'bone_head'], ['weapon', 'Wep01_R0_0_jnt'],
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['shoulder.L', 'arm_L0_1_jnt'], ['elbow.L', 'arm_L0_2_jnt'],
    ['elbow.L', 'arm_L0_3_jnt'], ['wrist.L', 'arm_L0_4_jnt'],
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['shoulder.R', 'arm_R0_1_jnt'], ['elbow.R', 'arm_R0_2_jnt'],
    ['elbow.R', 'arm_R0_3_jnt'], ['wrist.R', 'arm_R0_4_jnt'],
    ['Bone Front L Leg01', 'foreleg_L0_0_jnt'], ['Bone Front L Leg01', 'foreleg_L0_1_jnt'],
    ['Bone Front L Leg01', 'foreleg_L0_2_jnt'], ['Bone Front L Shin01', 'foreleg_L0_3_jnt'],
    ['Bone Front L Shin01', 'foreleg_L0_4_jnt'], ['Bone FrontL Toe01', 'foreleg_L0_5_jnt'],
    ['Bone FrontL Toe01', 'foreleg_L0_6_jnt'],
    ['Bone Front R Leg01', 'foreleg_R0_0_jnt'], ['Bone Front R Leg01', 'foreleg_R0_1_jnt'],
    ['Bone Front R Leg01', 'foreleg_R0_2_jnt'], ['Bone Front R Shin01', 'foreleg_R0_3_jnt'],
    ['Bone Front R Shin01', 'foreleg_R0_4_jnt'], ['Bone Front R Toe01', 'foreleg_R0_5_jnt'],
    ['Bone Front R Toe01', 'foreleg_R0_6_jnt'],
    ['Bone Back L Leg01', 'backleg_L0_0_jnt'], ['Bone Back L Leg01', 'backleg_L0_1_jnt'],
    ['Bone Back L Leg01', 'backleg_L0_2_jnt'], ['Bone Back L Shin01', 'backleg_L0_3_jnt'],
    ['Bone Back L Shin01', 'backleg_L0_4_jnt'], ['Bone Toe L ', 'backleg_L0_5_jnt'],
    ['Bone Toe L ', 'backleg_L0_6_jnt'],
    ['Bone Back R Leg01', 'backleg_R0_0_jnt'], ['Bone Back R Leg01', 'backleg_R0_1_jnt'],
    ['Bone Back R Leg01', 'backleg_R0_2_jnt'], ['Bone Back R Shin01', 'backleg_R0_3_jnt'],
    ['Bone Back R Shin01', 'backleg_R0_4_jnt'], ['Bone Toe R', 'backleg_R0_5_jnt'],
    ['Bone Toe R', 'backleg_R0_6_jnt'],
    ['Bone Tail 03', 'tail_C0_0_jnt'], ['Bone Tail 04', 'tail_C0_1_jnt'],
    ['Bone Tail 05', 'tail_C0_2_jnt'], ['Bone Tail 06', 'tail_C0_3_jnt'],
    ['Mesh25', 'wingbase_L0_0_jnt'], ['Mesh31', 'wingbase_L0_1_jnt'],
    ['Mesh30', 'wingfinger_L0_0_jnt'], ['Mesh27', 'wingfinger_L0_1_jnt'], ['Mesh26', 'wingfinger_L0_2_jnt'],
    ['Mesh30', 'wingfinger_L1_0_jnt'], ['Mesh28', 'wingfinger_L1_1_jnt'], ['Mesh26', 'wingfinger_L1_2_jnt'],
    ['Mesh32', 'wingfinger_L2_0_jnt'], ['Mesh28', 'wingfinger_L2_1_jnt'], ['Mesh26', 'wingfinger_L2_2_jnt'],
    ['Wing', 'wingbase_R0_0_jnt'], ['Mesh23', 'wingbase_R0_1_jnt'],
    ['Mesh22', 'wingfinger_R0_0_jnt'], ['Mesh20', 'wingfinger_R0_1_jnt'], ['Mesh19', 'wingfinger_R0_2_jnt'],
    ['Mesh22', 'wingfinger_R1_0_jnt'], ['Mesh21', 'wingfinger_R1_1_jnt'], ['Mesh19', 'wingfinger_R1_2_jnt'],
    ['Mesh24', 'wingfinger_R2_0_jnt'], ['Mesh21', 'wingfinger_R2_1_jnt'], ['Mesh19', 'wingfinger_R2_2_jnt'],
];
