export const character = 13;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\orc\\Thrall\\Thrall.mdx';
export const limbScales = [
    ['mount_tail_01_bind_jnt', 0.4],
    ['mount_tail_scale_01_bind_jnt', 0.4, 'mount_tail_01_bind_jnt'],
    ['mount_tail_scale_02_bind_jnt', 0.4, 'mount_tail_01_bind_jnt'],
    ['mount_tail_scale_03_bind_jnt', 0.4, 'mount_tail_01_bind_jnt'],
] as const;

export const classic = {
    pelvis: 'Bone Rider Waist',
    chest: 'Bone_Chest',
    head: 'Bone_Head',
    'shoulder.L': 'Bone Rider L Arm',
    'wrist.L': 'Bone Rider L Wrist',
    'shoulder.R': 'Bone Rider R Arm',
    'wrist.R': 'Bone Rider R Wrist',
    weapon: 'Hammer',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['pelvis', 'bone_turret'],
    ['pelvis', 'pelvis_bind_jnt'],
    ['chest', 'bone_chest'],
    ['head', 'neck_bind_jnt'],
    ['head', 'bone_head'],
    ['shoulder.L', 'L_upr_arm_bind_jnt'],
    ['wrist.L', 'L_lwr_arm_bind_jnt'],
    ['wrist.L', 'bone_hand_left'],
    ['shoulder.R', 'R_upr_arm_bind_jnt'],
    ['wrist.R', 'R_lwr_arm_bind_jnt'],
    ['wrist.R', 'bone_hand_right'],
    ['weapon', 'weapon_bind_jnt'],
    ['Object24', 'R_pauldron_bind_jnt'],
    ['Mesh14', 'L_pauldron_bind_jnt'],
    ['Object10', 'L_hair_01_bind_jnt'],
    ['Mesh18', 'L_hair_02_bind_jnt'],
    ['Mesh16', 'L_hair_03_bind_jnt'],
    ['Object07', 'R_hair_01_bind_jnt'],
    ['Mesh17', 'R_hair_02_bind_jnt'],
    ['Mesh15', 'R_hair_03_bind_jnt'],
    ['Object04', 'M_hair_01_bind_jnt'],
    ['Object11', 'M_hair_02_bind_jnt'],
    ['Object05', 'M_Hair_03_bind_jnt'],
    ['Bone Center', 'mount_spine_01_bind_jnt'],
    ['Bone Wolf Waist', 'mount_pelvis_bind_jnt'],
    ['Bone Wolf Neck', 'mount_bone_chest'],
    ['Bone Wolf Head', 'mount_neck_bind_jnt'],
    ['Bone Wolf Head', 'mount_hd_anim_bind_jnt'],
    ['Jaw', 'mount_jaw_bind_jnt'],
    ['Object27', 'mount_L_ear_bind_jnt'],
    ['Object28', 'mount_R_ear_bind_jnt'],
    ['Bone Front L Leg', 'mount_L_upr_arm_bind_jnt'],
    ['Bone Front L Shin', 'mount_L_lwr_arm_bind_jnt'],
    ['Bone FrontL Toe', 'mount_bone_hand_left'],
    ['Bone Front R Leg', 'mount_R_upr_arm_bind_jnt'],
    ['Bone_Mesh49', 'mount_R_lwr_arm_bind_jnt'],
    ['Bone_Mesh48', 'mount_bone_hand_right'],
    ['Bone Back L Leg', 'mount_L_leg_01_bind_jnt'],
    ['Bone Back L Shin', 'mount_L_leg_02_bind_jnt'],
    ['Bone Object67', 'mount_bone_leg_left'],
    ['Bone Back R Leg', 'mount_R_leg_01_bind_jnt'],
    ['Bone Back R Shin', 'mount_R_leg_02_bind_jnt'],
    ['Bone Back R Toe', 'mount_bone_leg_right'],
    ['Bone Tail 1', 'mount_tail_01_bind_jnt'],
    ['Bone Tail 2', 'mount_tail_02_bind_jnt'],
];
