export const character = 19;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\creeps\\herotinker\\herotinker.mdx';
export const visibilityPairs: readonly (readonly [number, number])[] = [
    [0, 0], [0, 4], [0, 5],
    [9, 2], [2, 3],
    [15, 6], [15, 7], [15, 8], [15, 9], [15, 10], [15, 11],
];
export const classic = {
    pelvis: 'Bone_Pelvis01',
    chest: 'Bone_Chest01',
    head: 'Bone_Head01',
    'shoulder.L': 'Bone_Arm1_L01',
    'elbow.L': 'Bone_Arm2_L01',
    'wrist.L': 'Bone_Hand_L01',
    'hip.L': 'Bone_Leg1_L01',
    'knee.L': 'Bone_Leg2_L01',
    'ankle.L': 'Bone_Foot_L01',
    'shoulder.R': 'Bone_Arm1_R01',
    'elbow.R': 'Bone_Arm2_R01',
    'wrist.R': 'Bone_Hand_R01',
    'hip.R': 'Bone_Leg1_R01',
    'knee.R': 'Bone_Leg2_R01',
    'ankle.R': 'Bone_Foot_R01',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['pelvis', 'spine_C0_0_jnt'],
    ['chest', 'bone_chest'],
    ['head', 'bone_head'],
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['elbow.L', 'arm_L0_2_jnt'],
    ['wrist.L', 'arm_L0_end_jnt'],
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['elbow.R', 'arm_R0_2_jnt'],
    ['wrist.R', 'arm_R0_end_jnt'],
    ['hip.L', 'leg_L0_0_jnt'],
    ['knee.L', 'leg_L0_2_jnt'],
    ['ankle.L', 'leg_L0_end_jnt'],
    ['hip.R', 'leg_R0_0_jnt'],
    ['knee.R', 'leg_R0_2_jnt'],
    ['ankle.R', 'leg_R0_end_jnt'],
    ['bonebackpack', 'backpack_C0_0_jnt'],
    ['Bone_BackPack_UpJoint1', 'armbaserot_C0_0_jnt'],
    ['Bone_BackPack_UpJoint2', 'armbase_C0_0_jnt'],
    ['Bone_BackPack_UpJoint3', 'armshoulder_C0_0_jnt'],
    ['Bone_BackPack_ArmLeft1', 'clawarm_L0_0_jnt'],
    ['Bone_BackPack_ArmLeft2', 'clawarm_L0_2_jnt'],
    ['Bone_BackPack_ArmLeft3', 'clawarm_L0_end_jnt'],
    ['Bone_BackPack_ArmRight1', 'clawarm_R0_0_jnt'],
    ['Bone_BackPack_ArmRight2', 'clawarm_R0_2_jnt'],
    ['Bone_BackPack_ArmRight3', 'clawarm_R0_end_jnt'],
    ['Bone_BackPack_Claw1Left', 'clawjaw_L1_0_jnt'],
    ['Bone_BackPack_Claw2Left', 'clawjaw_L0_0_jnt'],
    ['Bone_BackPack_Claw1Right', 'clawjaw_R1_0_jnt'],
    ['Bone_BackPack_Claw2Right', 'clawjaw_R0_0_jnt'],
    ['Bone_BackPack_Canister', 'electrodetank_C0_0_jnt'],
    ['Bone_BackPack_Missles', 'cartridge_C0_0_jnt'],
    ['Bone_BackPack_Smoker_Left', 'exhaust_L1_0_jnt'],
    ['Bone_BackPack_Smoker_Right', 'exhaust_R1_0_jnt'],
    ['wrist.L', 'Wep01_L0_0_jnt'],
    ['Bone_MainTank_Tank', 'tankbody_C0_0_jnt'],
    ['TreadsStand_LF_Tank', 'tread_L0_0_jnt'],
    ['Wheels_R_Tank', 'tread_R0_0_jnt'],
    ['Bone_Turret_Tank', 'turretrot_C0_0_jnt'],
    ['Bone_BackPack_Canister02_Tank', 'tankbackcylinder_C0_0_jnt'],
    ['Bone_BackPack_Smoker_Left02_Tank', 'tankbackexhaust_L0_0_jnt'],
    ['Bone_BackPack_Smoker_Right02_Tank', 'tankbackexhaust_R0_0_jnt'],
    ['Bone_BackPack_UpJoint07_Tank', 'tankarmbase_C0_0_jnt'],
    ['Bone_BackPack_UpJoint08_Tank', 'tankarmmid_C0_0_jnt'],
    ['Bone_BackPack_ArmRight07_Tank', 'tankarm_L0_0_jnt'],
    ['Bone_BackPack_ArmRight08_Tank', 'tankarm_L0_2_jnt'],
    ['Bone_BackPack_ArmRight09_Tank', 'tankarm_L0_end_jnt'],
    ['Bone_BackPack_ArmRight09_Tank', 'Wep_C1_0_jnt'],
    ['Bone_BackPack_ArmLeft07_Tank', 'tankarm_R0_0_jnt'],
    ['Bone_BackPack_ArmLeft08_Tank', 'tankarm_R0_2_jnt'],
    ['Bone_BackPack_ArmLeft09_Tank', 'tankarm_R0_end_jnt'],
    ['Bone_Morph__BackPack_Claw1Right02_Tank', 'tankgrip_L1_0_jnt'],
    ['Bone_Morph__BackPack_Claw2Right02_Tank', 'tankgrip_L0_0_jnt'],
    ['Bone_BackPack_Claw1Left02_Tank', 'tankgrip_R1_0_jnt'],
    ['Bone_BackPack_Claw2Left02_Tank', 'tankgrip_R0_0_jnt'],
    ['Bone_LauncherLeft_Tank', 'tankpod_L0_0_jnt'],
    ['Bone_LauncherRight_Tank', 'tankpod_R0_0_jnt'],
    ['Cylinder21', 'rocket_C0_0_jnt'],
    ['Cylinder26', 'rocket_C1_0_jnt'],
    ['Cylinder25', 'rocket_C2_0_jnt'],
    ['Cylinder24', 'rocket_C3_0_jnt'],
    ['Cylinder23', 'rocket_C4_0_jnt'],
    ['Cylinder22', 'rocket_C5_0_jnt'],
];
