export const stockPath = 'war3.w3mod:_de.w3mod:units\\nightelf\\herowarden\\herowarden.mdx';

// The Definitive limbs contain twist joints between the named Classic articulations.
export const pairs: readonly (readonly [string, string])[] = [
    ['Bone_Pelvis', 'spine_C0_0_jnt'],
    ['Bone_Chest', 'spine_C0_1_jnt'],
    ['Bone_Chest', 'bone_chest'],
    ['Bone_Head', 'neck_C0_0_jnt'],
    ['Bone_Head', 'bone_head'],
    
    ['Bone_Arm1_L', 'arm_L0_0_jnt'],
    ['Bone_Arm2_L', 'arm_L0_2_jnt'],
    ['Bone_Hand_L', 'arm_L0_4_jnt'],
    
    ['Bone_Arm1_R', 'arm_R0_0_jnt'],
    ['Bone_Arm2_R', 'arm_R0_2_jnt'],
    ['Bone_Hand_R', 'arm_R0_4_jnt'],
    ['Bone_Leg1_L', 'leg_L0_0_jnt'],
    ['Bone_Leg2_L', 'leg_L0_2_jnt'],
    ['Bone_Foot_L', 'leg_L0_4_jnt'],
    ['Bone_Foot_L', 'foot_L0_0_jnt'],
    ['Bone_Leg1_R', 'leg_R0_0_jnt'],
    ['Bone_Leg2_R', 'leg_R0_2_jnt'],
    ['Bone_Foot_R', 'leg_R0_4_jnt'],
    ['Bone_Foot_R', 'foot_R0_0_jnt'],
    ['Object08', 'Wep01_R0_0_jnt'],
    ['Mesh28', 'hair_C0_0_jnt'],
    ['Mesh18', 'hair_C1_0_jnt'],
    ['Mesh24', 'hair_C2_0_jnt'],
    ['Mesh02', 'hair_C3_0_jnt'],
    ['Object01', 'hair_C4_0_jnt'],
    ['Cape_Dummy01', 'cloak_C0_0_jnt'],
    ['Cape_Dummy02', 'cloak_C0_1_jnt'],
    ['Cape_Dummy03', 'cloak_C0_2_jnt'],
    ['Cape_Dummy04', 'cloak_C0_3_jnt'],
    ['Cape_Dummy04', 'cloak_C0_4_jnt'],
    ['Cape_Piece24', 'cloakBR_L1_0_jnt'],
    ['Cape_Piece16', 'cloakBR_L1_1_jnt'],
    ['Cape_Piece04', 'cloakBR_L1_2_jnt'],
    ['Cape_Piece06', 'cloakBR_L1_3_jnt'],
    ['Cape_Piece06', 'cloakBR_L1_4_jnt'],
    ['Cape_Piece18', 'cloakSide_L2_0_jnt'],
    ['Cape_Piece11', 'cloakSide_L2_1_jnt'],
    ['Cape_Piece02', 'cloakSide_L2_2_jnt'],
    ['Cape_Piece05', 'cloakSide_L2_3_jnt'],
    ['Cape_Piece05', 'cloakSide_L2_4_jnt'],
    ['Cape_Piece18', 'cloakFront_L3_0_jnt'],
    ['Cape_Piece14', 'cloakFront_L3_1_jnt'],
    ['Cape_Piece02', 'cloakFront_L3_2_jnt'],
    ['Cape_Piece07', 'cloakFront_L3_3_jnt'],
    ['Cape_Piece07', 'cloakFront_L3_4_jnt'],
    ['Cape_Piece23', 'cloakBR_R1_0_jnt'],
    ['Cape_Piece15', 'cloakBR_R1_1_jnt'],
    ['Cape_Piece03', 'cloakBR_R1_2_jnt'],
    ['Cape_Piece08', 'cloakBR_R1_3_jnt'],
    ['Cape_Piece08', 'cloakBR_R1_4_jnt'],
    ['Cape_Piece21', 'cloakSide_R2_0_jnt'],
    ['Cape_Piece13', 'cloakSide_R2_1_jnt'],
    ['Cape_Piece01', 'cloakSide_R2_2_jnt'],
    ['Cape_Piece10', 'cloakSide_R2_3_jnt'],
    ['Cape_Piece10', 'cloakSide_R2_4_jnt'],
    ['Cape_Piece20', 'cloakFront_R3_0_jnt'],
    ['Cape_Piece12', 'cloakFront_R3_1_jnt'],
    ['Cape_Piece01', 'cloakFront_R3_2_jnt'],
    ['Cape_Piece09', 'cloakFront_R3_3_jnt'],
    ['Cape_Piece09', 'cloakFront_R3_4_jnt'],
];
