export const character = 5;
export const stockPath = 'war3.w3mod:_de.w3mod:units\\nightelf\\herowarden\\herowarden.mdx';

// The Definitive limbs contain twist joints between the named Classic articulations.
export const classic = {
    root: 'Bone_Root',
    pelvis: 'Bone_Pelvis',
    chest: 'Bone_Chest',
    head: 'Bone_Head',
    'shoulder.L': 'Bone_Arm1_L',
    'elbow.L': 'Bone_Arm2_L',
    'wrist.L': 'Bone_Hand_L',
    'hip.L': 'Bone_Leg1_L',
    'knee.L': 'Bone_Leg2_L',
    'ankle.L': 'Bone_Foot_L',
    'shoulder.R': 'Bone_Arm1_R',
    'elbow.R': 'Bone_Arm2_R',
    'wrist.R': 'Bone_Hand_R',
    'hip.R': 'Bone_Leg1_R',
    'knee.R': 'Bone_Leg2_R',
    'ankle.R': 'Bone_Foot_R',
    weapon: 'Object08',
} as const;
export const pairs: readonly (readonly [string, string])[] = [
    ['pelvis', 'spine_C0_0_jnt'],
    ['chest', 'spine_C0_1_jnt'],
    ['chest', 'bone_chest'],
    ['head', 'neck_C0_0_jnt'],
    ['head', 'bone_head'],
    
    ['shoulder.L', 'arm_L0_0_jnt'],
    ['elbow.L', 'arm_L0_2_jnt'],
    ['wrist.L', 'arm_L0_4_jnt'],
    
    ['shoulder.R', 'arm_R0_0_jnt'],
    ['elbow.R', 'arm_R0_2_jnt'],
    ['wrist.R', 'arm_R0_4_jnt'],
    ['hip.L', 'leg_L0_0_jnt'],
    ['knee.L', 'leg_L0_2_jnt'],
    ['ankle.L', 'leg_L0_4_jnt'],
    ['ankle.L', 'foot_L0_0_jnt'],
    ['hip.R', 'leg_R0_0_jnt'],
    ['knee.R', 'leg_R0_2_jnt'],
    ['ankle.R', 'leg_R0_4_jnt'],
    ['ankle.R', 'foot_R0_0_jnt'],
    ['weapon', 'Wep01_R0_0_jnt'],
    ['Mesh28', 'hair_C0_0_jnt'],
    ['Mesh18', 'hair_C1_0_jnt'],
    ['Mesh24', 'hair_C2_0_jnt'],
    ['Mesh02', 'hair_C3_0_jnt'],
    ['Object01', 'hair_C4_0_jnt'],
    ['Cape_Dummy01', 'cloak_C0_0_jnt'],
    ['Cape_Dummy02', 'cloak_C0_1_jnt'],
    ['Cape_Dummy03', 'cloak_C0_2_jnt'],
    ['Cape_Dummy04', 'cloak_C0_3_jnt'],
    ['Cape_Dummy04', 'cloak_C0_4_jnt'],
    ['Cape_Piece24', 'cloakBR_L1_0_jnt'],
    ['Cape_Piece16', 'cloakBR_L1_1_jnt'],
    ['Cape_Piece04', 'cloakBR_L1_2_jnt'],
    ['Cape_Piece06', 'cloakBR_L1_3_jnt'],
    ['Cape_Piece06', 'cloakBR_L1_4_jnt'],
    ['Cape_Piece18', 'cloakSide_L2_0_jnt'],
    ['Cape_Piece11', 'cloakSide_L2_1_jnt'],
    ['Cape_Piece02', 'cloakSide_L2_2_jnt'],
    ['Cape_Piece05', 'cloakSide_L2_3_jnt'],
    ['Cape_Piece05', 'cloakSide_L2_4_jnt'],
    ['Cape_Piece18', 'cloakFront_L3_0_jnt'],
    ['Cape_Piece14', 'cloakFront_L3_1_jnt'],
    ['Cape_Piece02', 'cloakFront_L3_2_jnt'],
    ['Cape_Piece07', 'cloakFront_L3_3_jnt'],
    ['Cape_Piece07', 'cloakFront_L3_4_jnt'],
    ['Cape_Piece23', 'cloakBR_R1_0_jnt'],
    ['Cape_Piece15', 'cloakBR_R1_1_jnt'],
    ['Cape_Piece03', 'cloakBR_R1_2_jnt'],
    ['Cape_Piece08', 'cloakBR_R1_3_jnt'],
    ['Cape_Piece08', 'cloakBR_R1_4_jnt'],
    ['Cape_Piece21', 'cloakSide_R2_0_jnt'],
    ['Cape_Piece13', 'cloakSide_R2_1_jnt'],
    ['Cape_Piece01', 'cloakSide_R2_2_jnt'],
    ['Cape_Piece10', 'cloakSide_R2_3_jnt'],
    ['Cape_Piece10', 'cloakSide_R2_4_jnt'],
    ['Cape_Piece20', 'cloakFront_R3_0_jnt'],
    ['Cape_Piece12', 'cloakFront_R3_1_jnt'],
    ['Cape_Piece01', 'cloakFront_R3_2_jnt'],
    ['Cape_Piece09', 'cloakFront_R3_3_jnt'],
    ['Cape_Piece09', 'cloakFront_R3_4_jnt'],
];
