// Checks every sound and track the match presentation names against the
// installed game's storage and records the verified paths, so headless tests
// can hold the presentation to sounds that exist. Only paths are written; the
// audio stays in the game.
// Usage: bun tools/presentation/stock-sounds.ts --extract CASC_EXTRACT [--storage WARCRAFT_DIR]
// (tools/animations/extract.sh builds CASC_EXTRACT into build/animation-assets/.)
import {mkdtempSync, rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {presentationSoundPaths} from '../../ts/src/game/presentation/matchAudio';
import {SELECTABLE_CHARACTERS} from '../../ts/src/game/sim/heroes/registry';
import {STAGE_CATALOG} from '../../ts/src/game/menu/stageCatalog';

const option = (name: string) => { const index = process.argv.indexOf(name); return index < 0 ? undefined : process.argv[index + 1]; };
const extract = option('--extract');
if (extract === undefined) throw new Error('usage: bun tools/presentation/stock-sounds.ts --extract CASC_EXTRACT [--storage WARCRAFT_DIR]');
const storage = option('--storage') ?? `${process.env.HOME}/.local/share/Steam/steamapps/compatdata/3516115571/pfx/drive_c/Program Files (x86)/Warcraft III`;
const project = resolve(import.meta.dir, '../..');
const scratch = mkdtempSync(join(tmpdir(), 'smashcraft-sounds.'));

/** The game resolves a script's sound path to whichever encoding and locale it stores. */
function storedNames(path: string): string[] {
  const stem = path.toLowerCase().replace(/\.[a-z0-9]+$/, '');
  const names: string[] = [];
  for (const root of ['war3.w3mod:', 'war3.w3mod:_locales\\enus.w3mod:']) {
    for (const extension of ['.flac', '.ogg', '.mp3', '.wav']) names.push(`${root}${stem}${extension}`);
  }
  return names;
}

async function stored(path: string, index: number): Promise<string | undefined> {
  for (const name of storedNames(path)) {
    const output = join(scratch, `${index}.bin`);
    const child = Bun.spawn([extract!, storage, name, output], {stdout: 'ignore', stderr: 'ignore'});
    if (await child.exited === 0) return name;
  }
  return undefined;
}

const paths = presentationSoundPaths(SELECTABLE_CHARACTERS, STAGE_CATALOG.map(stage => stage.id));
const found: (string | undefined)[] = new Array(paths.length);
try {
  let next = 0;
  await Promise.all(Array.from({length: 4}, async () => {
    while (next < paths.length) { const index = next++; found[index] = await stored(paths[index], index); }
  }));
} finally {
  rmSync(scratch, {recursive: true, force: true});
}
const missing = paths.filter((_, index) => found[index] === undefined);
if (missing.length > 0) throw new Error(`not in the installed game: ${missing.join(', ')}`);
const lines = [
  '// Generated by tools/presentation/stock-sounds.ts from the installed game\'s storage; regenerate instead of editing.',
  '/** Script sound paths found in the game, with the stored file each resolves to. */',
  'export const VERIFIED_STOCK_SOUNDS: Readonly<Record<string, string>> = {',
  ...paths.map((path, index) => `  ${JSON.stringify(path)}: ${JSON.stringify(found[index])},`),
  '};',
  '',
];
const out = join(project, 'ts/src/game/assets/stockSoundInfo.ts');
await Bun.write(out, lines.join('\n'));
console.log(`${paths.length} paths verified: ${out}`);
