import { stageBounds } from "./stageBounds";
import { assertEquals, assertGreaterThan, assertFalse, assertTrue, test } from "wisp/src/runtime/testing";
import { AttackStyle, Character } from "./codes";
import { canStartAttackStyle } from "./conditions";
import { createFighter } from "./fighter";
import { attackDurationFramesForGrounding, attackStartupFrames } from "./moves";
import { resolveAttacks, beginFighterAttack } from "./attacks";
import { advanceFreezeTraps } from "./summons";
import { advanceSolo, controls, testWorld } from "./testWorld";
import { respawnFighter } from "./stocks";
import { createRoster } from "./roster";
import { f32 } from "wisp/src/sim/f32";

test("shieldConsumesTrapWithoutFreezingAndHitBreaksIce", () => {
  const owner = createFighter(Character.rifleman, 0.0, 1);
  const target = createFighter(Character.archer, 0.0, -1);
  owner.motion.surface = 0;
  target.motion.surface = 0;
  owner.freezeTrap.life = 30;
  owner.freezeTrap.x = 0.0;
  owner.freezeTrap.surface = 0;
  target.shield.raised = true;
  advanceFreezeTraps(testWorld(owner, target));
  assertEquals(owner.freezeTrap.life, 0);
  assertEquals(target.status.frozenFrames, 0);
  target.shield.raised = false;
  target.status.frozenFrames = 100;
  owner.motion.x = 0.0;
  beginFighterAttack(testWorld(owner, target), 0, AttackStyle.jab, false);
  owner.attack.frame = attackStartupFrames(AttackStyle.jab);
  owner.attack.duration = attackDurationFramesForGrounding(AttackStyle.jab, true);
  owner.attack.hit = false;
  target.motion.x = 100.0;
  resolveAttacks(testWorld(owner, target));
  assertGreaterThan(target.status.damage, 0.0);
  assertEquals(target.status.frozenFrames, 0);
});

test("trapConsumesOnContactButNotOwnerOrInvulnerableTarget", () => {
  const owner = createFighter(Character.rifleman, 0.0, 1);
  const target = createFighter(Character.archer, 0.0, -1);
  owner.motion.surface = 0;
  target.motion.surface = 0;
  owner.freezeTrap.life = 30;
  owner.freezeTrap.arming = 0;
  owner.freezeTrap.x = 0.0;
  owner.freezeTrap.surface = 0;
  target.status.invincible = 2;
  advanceFreezeTraps(testWorld(owner, target));
  assertEquals(owner.freezeTrap.life, 30);
  assertEquals(target.status.frozenFrames, 0);
  target.status.invincible = 0;
  advanceFreezeTraps(testWorld(owner, target));
  assertEquals(owner.freezeTrap.life, 0);
  assertEquals(target.status.frozenFrames, 300);
  assertEquals(owner.status.frozenFrames, 0);
});

test("freezeExpiresAfterThreeHundredFramesIncludingHitlag", () => {
  const target = createFighter(Character.archer, 0.0, 1);
  target.status.frozenFrames = 300;
  target.launch.hitlag = 20;
  for (let frame = 1; frame < 300; frame++) advanceSolo(target, 0, controls(), -240.0);
  assertEquals(target.status.frozenFrames, 1);
  assertEquals(target.launch.hitlag, 20);
  advanceSolo(target, 0, controls(), -240.0);
  assertEquals(target.status.frozenFrames, 0);
  assertEquals(target.launch.hitlag, 20);
  assertFalse(canStartAttackStyle(target, AttackStyle.jab));
  target.launch.hitlag = 0;
  assertTrue(canStartAttackStyle(target, AttackStyle.jab));
});

test("koRespawnAndResetClearTrapAndFrozenState", () => {
  const rifleman = createFighter(Character.rifleman, 0.0, 1);
  const world = createRoster(1, [rifleman]);
  rifleman.status.stocks = 2;
  rifleman.freezeTrap.life = 900;
  rifleman.freezeTrap.arming = 12;
  rifleman.freezeTrap.serial = 3;
  rifleman.status.frozenFrames = 120;
  rifleman.motion.x = f32(stageBounds(0).blast.right + 0.0009765625);
  advanceSolo(rifleman, 0, controls(), -240.0);
  assertTrue(rifleman.status.out);
  assertEquals(rifleman.status.stocks, 1);
  assertEquals(rifleman.freezeTrap.life, 0);
  assertEquals(rifleman.status.frozenFrames, 0);
  for (let frame = 1; frame <= 60; frame++) advanceSolo(rifleman, 0, controls(), -240.0);
  assertFalse(rifleman.status.out);
  assertEquals(rifleman.freezeTrap.serial, 0);
  assertEquals(rifleman.freezeTrap.life, 0);
  assertEquals(rifleman.freezeTrap.cooldown, 0);
  assertEquals(rifleman.status.frozenFrames, 0);
  rifleman.freezeTrap.life = 900;
  rifleman.freezeTrap.serial = 1;
  rifleman.status.frozenFrames = 12;
  respawnFighter(world, 0, 240.0);
  assertEquals(rifleman.freezeTrap.serial, 0);
  assertEquals(rifleman.freezeTrap.life, 0);
  assertEquals(rifleman.status.frozenFrames, 0);
});
