// Generated by tools/effects/package.ts from the authored impact models; regenerate instead of editing.
export const IMPACT_HIT_MODEL = "war3mapImported\\ImpactHit-62592fbfab277201dd66093d95282de50557b534957f04c3754c2c727b3b9b5d.mdx";
export const IMPACT_TECH_MODEL = "war3mapImported\\ImpactTech-3f6fcc8da2fd291caa5a490222d3071e912641606fac841e62e211907258a6cc.mdx";
export const IMPACT_MISS_MODEL = "war3mapImported\\ImpactMiss-50c0e9d040c9afb26b09d79bb05d4b7ab26bfb0beca733025071288db725e412.mdx";
export const IMPACT_DUST_MODEL = "war3mapImported\\ImpactDust-203c5231debda1f1be87bee7ea942bb77b953c077731f33b78409144da9a3778.mdx";
export const IMPACT_ROLL_MODEL = "war3mapImported\\ImpactRoll-669e5efa0a209e4d41441c277aefb3fc2a9ecfb95dc9aef0f6c492cf2008c768.mdx";
export const IMPACT_ELECTRIC_MODEL = "war3mapImported\\ImpactElectric-9dbba329f6eab3916fd4fa90199d077d11a7cc6992c2f008c080e26d7c372acf.mdx";
export const IMPACT_SHIELD_MODEL = "war3mapImported\\ImpactShield-45ee224451846210394de9480ea69f041edce17210c5b045a577d1130126e87f.mdx";
export const IMPACT_JUMP_MODEL = "war3mapImported\\ImpactJump-2819c9b61c83f2dd214fa7ece4262c69abfb4cd90d7efaf8687544253577869f.mdx";
export const IMPACT_KO_MODEL = "war3mapImported\\ImpactKO-3f455594c218cda43d93f025b3997bced37c0e224cc1cd1ec40b8806899f5bf4.mdx";
export const IMPACT_RESPAWN_MODEL = "war3mapImported\\ImpactRespawn-8948249a993a5287433c1123220cbaec68c6cb111bd6ef748b2c4f02bfa5dd20.mdx";
export const IMPACT_DEFILE_MODEL = "war3mapImported\\ImpactDefile-f9468786e4e4da0c1c062345017758d5092c30ad7c673e078b00c823447b4f90.mdx";
