// Generated by tools/animations/export-model-sounds.ts from the original fighter models' sound events and AnimSounds.slk; regenerate instead of editing.
import { f32 } from "wisp/src/sim/f32";

/** A sound keyed at `seconds` into an original sequence. */
export interface ModelSoundCue {
  readonly sequenceIndex: number;
  readonly seconds: number;
  readonly soundIndex: number;
}

/** Stock sound labels by sound index; each owns its variants, pitch, channel and attenuation. */
const LABELS: readonly string[] = [
  "RiflemanDeath",
  "RiflemanAttack1",
  "HeroDemonHunterAttack1",
  "HeroDemonHunterAttack2",
  "HeroDemonHunterDeath",
  "DemonHunterMorph",
  "HeroDemonHunterDeathAlternate",
  "NightElfDissipate",
  "DeepFootstep",
  "DeepFootstep2",
];

const IS_3D: readonly boolean[] = [
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
];

/** Each character's cues, ordered as authored. */
const CUES: Readonly<Record<number, (readonly ModelSoundCue[])>> = {
  1: [
    { sequenceIndex: 5, seconds: f32(0.167), soundIndex: 1 },
    { sequenceIndex: 11, seconds: 0.0, soundIndex: 0 },
  ],
  2: [
    { sequenceIndex: 6, seconds: 0.0, soundIndex: 2 },
    { sequenceIndex: 7, seconds: 0.0, soundIndex: 3 },
    { sequenceIndex: 18, seconds: 0.0, soundIndex: 4 },
    { sequenceIndex: 19, seconds: 0.0, soundIndex: 6 },
    { sequenceIndex: 20, seconds: 0.0, soundIndex: 7 },
    { sequenceIndex: 21, seconds: 0.0, soundIndex: 7 },
    { sequenceIndex: 58, seconds: 0.0, soundIndex: 5 },
    { sequenceIndex: 59, seconds: 0.0, soundIndex: 5 },
    { sequenceIndex: 108, seconds: f32(0.133), soundIndex: 8 },
    { sequenceIndex: 108, seconds: 0.5, soundIndex: 9 },
  ],
};

/** The stock sound label, which owns its variants, pitch, channel and attenuation. */
export function modelSoundLabel(soundIndex: number): string | undefined {
  return LABELS[soundIndex];
}

export function modelSoundIs3D(soundIndex: number): boolean {
  return IS_3D[soundIndex] ?? false;
}

/** Cues 0 to count - 1 exist for this character, ordered as authored. */
export function fighterSoundCueCount(character: number): number {
  return CUES[character]?.length ?? 0;
}

export function fighterSoundCue(character: number, ordinal: number): ModelSoundCue | undefined {
  return CUES[character]?.[ordinal];
}
