// Generated by tools/effects/shield.ts from the authored shield models; regenerate instead of editing.
export const SHIELD_P1_MODEL = "war3mapImported\\ShieldP1-0dc63c994e74dac66ecfba82be407f857a34d6a34d1f8f15a8fd6178e524cfdf.mdx";
export const SHIELD_P2_MODEL = "war3mapImported\\ShieldP2-ac92f76db1b3abc762bd6af85ab0141b1c0142f1294dd04e64ee57e3da9ba720.mdx";
export const SHIELD_P3_MODEL = "war3mapImported\\ShieldP3-bdb7fec231882f2026bc007f4b3ca51f7219404428e3c343d6c73b583df141c3.mdx";
export const SHIELD_P4_MODEL = "war3mapImported\\ShieldP4-0f6afe67f46efb19213ea283f57c12a8f13a264f9660903d3e1a451a095dd2a2.mdx";
