// Generated by tools/stage/package.ts; regenerate instead of editing.
/** Original atmospheric skies; Nordrassil retains its stock aurora. */
export const STAGE_SKY_MODELS: Readonly<Record<number, string>> = {
  0: "war3mapImported\\StageSky-aeb236c0b2015082fc3019a8e1a97416f723fb716c5feed687ceb1c35347e672.mdx",
  2: "war3mapImported\\StageSky-d9cbadf43d0f709c55d9d120d747200b1ee1eda89019bcd214232da0072dbb22.mdx",
  11: "war3mapImported\\StageSky-90e5744312092ab15b6c403600b533cfcff944b39192f39cfe605d08181e73e8.mdx",
  3: "war3mapImported\\StageSky-cef63d68a00a351ddbb84e90e842b1dacbd49752c7c9a29c14957df7d7aeec7b.mdx",
  4: "war3mapImported\\StageSky-e09b4ad1f520a5e04bf277049d369caf9f7734a8c6dab5e5258a04f399b47628.mdx",
  14: "war3mapImported\\StageSky-1f7efcede2ef8e18581648085e569a2619d73e16a701858fcb4ba4004f4cf2fb.mdx",
  12: "war3mapImported\\StageSky-72ec195c65104d2667ff190623a1b74046d0c6ea6ae7f5a55c68dffba410e5d5.mdx",
  13: "war3mapImported\\StageSky-42e53813a7e74ae30fc91999d14de81a661756781edc2fca94a7f61545f2ebae.mdx",
};
