// Generated by tools/stage/package.ts from the authored deck models; regenerate instead of editing.
/** The raised decks' slab, which the map scales to each deck. */
export const STAGE_DECK_MODEL = "war3mapImported\\StageDeck-48ca8b3ca98aa77d741926a42ad589a5f8b1df78e68f565c285ccadd6bc2c27c.mdx";
/** The main deck, drawn from its collision outline in arena units. */
export const STAGE_MAIN_DECK_MODEL = "war3mapImported\\StageMainDeck-043d3ab8ff1b03b9c0288e9f38951e8a2a383379d0020e3898cf16a351ca71ae.mdx";
