// Generated by tools/stage/package.ts; regenerate instead of editing.
/** Original atmospheric skies; Nordrassil retains its stock aurora. */
export const STAGE_SKY_MODELS: Readonly<Record<number, string>> = {
  0: "war3mapImported\\StageSky-3ea21e7af33222f5b0262d728156005e62cf58f0a91c85270e4e823b784e869d.mdx",
  2: "war3mapImported\\StageSky-001d9efc0f60170d503e9896ba1818ee98903d7be1f7219eac1eba0206e5d933.mdx",
  11: "war3mapImported\\StageSky-c3a88e4c3b121d131d7676b51cf3276b50ce2653997f33010a0a1b55c1d7bed5.mdx",
  3: "war3mapImported\\StageSky-2f2c893f3ceed80677bba9a312d64e0808a7b02e969bd4312f3261f222daefc9.mdx",
  4: "war3mapImported\\StageSky-a4ea2c55d5bec4d503872f4063e37515f2cb2e1ca62b076de8da4e09783f1cb8.mdx",
  14: "war3mapImported\\StageSky-4fdca07a9d6155b871fb5704458be5ce29dc8bce50a980c85439e651a6093a3a.mdx",
  12: "war3mapImported\\StageSky-62889846b0da28640a3a78a68478e1dac6a5c23b080ee477d8b585968c166d91.mdx",
  13: "war3mapImported\\StageSky-6b2f702b854f591c521b318bae0c60eb6020f2218b9790cdb33b8b2b9d197574.mdx",
};
