// Generated by tools/stage/package.ts from the authored deck models; regenerate instead of editing.
/** Each selectable stage's deck models in its palette: the raised decks' slab, which the map scales to each deck, and the main deck, drawn from its collision outline in arena units. */
export const STAGE_DECK_MODELS: Readonly<Record<number, { readonly slab: string; readonly main: string; readonly alternate?: string }>> = {
  0: { slab: "war3mapImported\\StageDeck-7e2aae2330a24a8ac729f2e74e7461292e493daebf98cda5c5d99fc07e302052.mdx", main: "war3mapImported\\StageMainDeck-d84846d2cdced8d9736dca878d5d1fb303a50f512a0dea0eb06142af33fe1b06.mdx" },
  2: { slab: "war3mapImported\\StageDeck-490d920caa3293c2b59c64fd20600753fb50fb37792456ac09ca32120fcf9abc.mdx", main: "war3mapImported\\StageMainDeck-5ee5bfbdf7780ff3af5d5a6c8c5a04b1269bfa71600aaa2877b0130a1d59c7e9.mdx" },
  10: { slab: "war3mapImported\\StageDeck-e7b28faad32ee6f1aebfbe1f919e826c6aab355c9faf2f6353183ac53bef8602.mdx", main: "war3mapImported\\StageMainDeck-964152662ba914991835f366d8cf95dcb24be1077b267d838e8191a342de9cd4.mdx" },
  11: { slab: "war3mapImported\\StageDeck-46d3e1533ec507ee9756d96b95b077596ac8ac527ade934265918bf3a35ff9ef.mdx", main: "war3mapImported\\StageMainDeck-fe065b7681d386e05382f03eafb53b9fd1ed525c1b32949b0699e8a49579161e.mdx", alternate: "war3mapImported\\StageDeck-6cf55f4c398fe902a2025f11b959e627452ccce8b3042ceac596a45f2077ccad.mdx" },
  3: { slab: "war3mapImported\\StageDeck-f50de2749e88b8f23c39e407d754a9ba2b5da1ce35cd1a3705e38f460ffcd4e2.mdx", main: "war3mapImported\\StageMainDeck-d515d10e84d10f2948cef82813083f8738ddebdcaadb52815b72e9d1f3f59db0.mdx" },
  4: { slab: "war3mapImported\\StageDeck-42aadf5d0c0e5338fcedaec9c2faae69aad7c84c59bc11497bfdf790693e87d5.mdx", main: "war3mapImported\\StageMainDeck-28c2bf5c3e5ec0ec7a949f50a708d31573fc52590e84fecba8b700b0661c45c3.mdx", alternate: "war3mapImported\\StageDeck-a81845b5bf33ba958e6b59a85d594ad9098682e60321301e21803b5234f3828e.mdx" },
  14: { slab: "war3mapImported\\StageDeck-ac92d7d504dfa134c760f69c12b8c018b4d4699529fab3b0eceebcc44f578f6d.mdx", main: "war3mapImported\\StageMainDeck-a31fe67df8fe9fa25a5c12b6b16583753edca1216db7cfc662797515237e825b.mdx" },
  12: { slab: "war3mapImported\\StageDeck-14ac350c5ca9c3f1cdc914b44159f54889eaf7d0ac1be33eda7a1f6d2ef5a578.mdx", main: "war3mapImported\\StageMainDeck-3afba373301e6392580cadc0e6de21dbd2d39a2e07c2086267bc79c81ba967a2.mdx" },
  6: { slab: "war3mapImported\\StageDeck-92dc55828d06da5ea6a9660d2457c9b6df2253be0cd2950a92de4dcf54d35b7e.mdx", main: "war3mapImported\\StageMainDeck-5dc41258c9e332f39a823514420054433f121f2b791a6f38b6a1b249d1b28f43.mdx" },
  7: { slab: "war3mapImported\\StageDeck-312202aebbbd8b0c1dd7dfcda7a1d357ef149e4d0590117a048e15a21470df39.mdx", main: "war3mapImported\\StageMainDeck-0fa3afd1d3929594674a58761415a33954d343a8358d7d0e2adb87c798886ddc.mdx" },
  13: { slab: "war3mapImported\\StageDeck-8ad82e4800b62de2ef9da93ee09586c6cf9177cd41f234974006d6e7ba6780c0.mdx", main: "war3mapImported\\StageMainDeck-2c25bb13ee2212293baaae6e1f7a0c97bf6dcd2fb335453342c2ce192dbd2d2e.mdx" },
};
/** The neutral palette's slab. */
export const STAGE_DECK_MODEL = "war3mapImported\\StageDeck-7e2aae2330a24a8ac729f2e74e7461292e493daebf98cda5c5d99fc07e302052.mdx";
/** The neutral palette's main deck. */
export const STAGE_MAIN_DECK_MODEL = "war3mapImported\\StageMainDeck-d84846d2cdced8d9736dca878d5d1fb303a50f512a0dea0eb06142af33fe1b06.mdx";
/** Drifting snow behind the fighting plane, using the stock snowflake texture. */
export const STAGE_SNOW_MODEL = "war3mapImported\\StageSnow-917b74168e66aca0467360dffd3956aabf3e0b69503b2f26da0ddedc1e8a5bd4.mdx";
/** Each selectable stage's day/night lighting model, from its light in stageLighting.ts. */
export const STAGE_LIGHT_MODELS: Readonly<Record<number, string>> = {
  0: "war3mapImported\\StageLight-58aa70a31b10f62d7bb32417f729569e4b05db2baa78efd264754cca6e604be6.mdx",
  2: "war3mapImported\\StageLight-1ad8299ee23d76791423ad6ef47e0c1efe055f732fbf692f5eea764c7bf0f738.mdx",
  10: "war3mapImported\\StageLight-237830eeeab84963d9a926cef8a7feaa72a71cb011309292ea8ad44f5ca69774.mdx",
  11: "war3mapImported\\StageLight-05aabd398820dbd090d773939d22c06f15272ac65ae31484b6ac69312ca119b6.mdx",
  3: "war3mapImported\\StageLight-fb31be74844f3d133719d66ba8227f747932fcf3d203a7cf8181ca071c7c6fcc.mdx",
  4: "war3mapImported\\StageLight-a1cf0295f1d9682a4ecb95d75eefa97bea7d6ce9877241c9cfd424288b5b8586.mdx",
  14: "war3mapImported\\StageLight-e2e9386a7685323a61c636f8d97042435961a2254e369c4af27061e382c12990.mdx",
  12: "war3mapImported\\StageLight-ecb13d23efd5e332c60425c87a7554ca5ecb54096c06b457a584a5e5a95aea25.mdx",
  6: "war3mapImported\\StageLight-72c98875af85ebde417d827ee435f29e5151d6a7b93c13c1e3f7569005990f36.mdx",
  7: "war3mapImported\\StageLight-edf3b5df8d80335a608fe64f09ae146f616bfd1e255338dcf59c73937403957a.mdx",
  13: "war3mapImported\\StageLight-ae4432a8c4c7ead2f4655b3f2ee7b8a1457e8d5dc0afd011d537768e7e5d32b9.mdx",
};
/** Each stage's backdrop omni light models, in the order of its lights in stagePointLights.ts. */
export const STAGE_POINT_LIGHT_MODELS: Readonly<Record<number, readonly string[]>> = {
  4: ["war3mapImported\\StagePointLight-3c239f503cd4b885fb1d2ccbd395dce50e78f4797f65e6db0ea63e33a1d92923.mdx"],
  14: ["war3mapImported\\StagePointLight-a80bf58f5aab59d642ab911bc6ae05f69654de09308907c907d76de24c2fd479.mdx", "war3mapImported\\StagePointLight-e40b69be1b897ad6f33fb53f05e23630f4af667ba227af8a3da1b3ea270dfb6f.mdx"],
  12: ["war3mapImported\\StagePointLight-999e4101ca5c95726a64c7da6fb63358b7f581400b20ef4bc2c0aacdd79d4619.mdx", "war3mapImported\\StagePointLight-a570d9a1bc4c3789b5c18b15b77898cdc97168e585ea26494d42ebac45446328.mdx"],
  6: ["war3mapImported\\StagePointLight-999e4101ca5c95726a64c7da6fb63358b7f581400b20ef4bc2c0aacdd79d4619.mdx", "war3mapImported\\StagePointLight-a570d9a1bc4c3789b5c18b15b77898cdc97168e585ea26494d42ebac45446328.mdx"],
};
