// Generated by tools/stage/package.ts from the authored deck models; regenerate instead of editing.
/** Each selectable stage's deck models in its palette: the raised decks' slab, which the map scales to each deck, and the main deck, drawn from its collision outline in arena units. */
export const STAGE_DECK_MODELS: Readonly<Record<number, { readonly slab: string; readonly main: string }>> = {
  0: { slab: "war3mapImported\\StageDeck-e02a115781aef5234e6a2a01f851b88645069cb4836a8937b5535ee185fd7004.mdx", main: "war3mapImported\\StageMainDeck-c84bc87b008bdb0f02a3682c90d4f4d68da18dae09e55f24d435314733e766ec.mdx" },
  2: { slab: "war3mapImported\\StageDeck-5f691054b8c02adf08f13ebcb9cc713921857872ae429ef359077a2f35a5533d.mdx", main: "war3mapImported\\StageMainDeck-1492f5c29ef827337dcfe44915981a628aa2351c6e0cd2a90d09e74531f73e33.mdx" },
  10: { slab: "war3mapImported\\StageDeck-61265a12559ca9d6a36ff718a261f6ef8b06c89d3d8b3f6ad013350b8fb2ae5f.mdx", main: "war3mapImported\\StageMainDeck-0ac7120672642305d02ca86d091248146b2036bd6736b3904016a8bf5c3c9655.mdx" },
  11: { slab: "war3mapImported\\StageDeck-cc09ab6cbed06cb9861b9bd15993d1d692224f59f9ef1271dd736eb0185593c3.mdx", main: "war3mapImported\\StageMainDeck-cb9fa22e0eb2b956bc45257997fe4f72efb128f26a2a86c1d9a07218f48b39c9.mdx" },
  3: { slab: "war3mapImported\\StageDeck-e8050527bc56d4dda4c74071e8d226282fadade90fe30469efd5bf941d663df1.mdx", main: "war3mapImported\\StageMainDeck-5c129cf8f4606902e7ac357442b815211525daa51e72c17e18d002faade76d96.mdx" },
  4: { slab: "war3mapImported\\StageDeck-cd0892f60aeebced0159be4beceb75273860026f37bccfb131d961d699ac26e5.mdx", main: "war3mapImported\\StageMainDeck-6718c06e1ee85005365bff0985a2f25494c069cdc9196cd8d50b2f0489a47d28.mdx" },
  14: { slab: "war3mapImported\\StageDeck-d7087c4429a50b12e62b25e17cec5506e9070fd0db22fb7e51da7ec76c80d76f.mdx", main: "war3mapImported\\StageMainDeck-c062360c30d944bdad7035949dd321ddd7548bbf22612e7333f1ecad911bc424.mdx" },
  12: { slab: "war3mapImported\\StageDeck-697f09a1a69928c15b7ecc2646ef7c6ab7f1027a03a83bf825fba6dbd14e7f5b.mdx", main: "war3mapImported\\StageMainDeck-3caf6919d206847a90cffa1778dda3ad403df57507f0d88715f3b59fbc7dac8f.mdx" },
  13: { slab: "war3mapImported\\StageDeck-d8845bd0c9c043cb18b8b1e4480bb112197019fb4ca5b7b25273ce503f1e63a9.mdx", main: "war3mapImported\\StageMainDeck-bc6293bb28debe8be5ae2a8128cb1e88f47628306d1800dc2611bc47cd6583d8.mdx" },
};
/** The neutral palette's slab. */
export const STAGE_DECK_MODEL = "war3mapImported\\StageDeck-e02a115781aef5234e6a2a01f851b88645069cb4836a8937b5535ee185fd7004.mdx";
/** The neutral palette's main deck. */
export const STAGE_MAIN_DECK_MODEL = "war3mapImported\\StageMainDeck-c84bc87b008bdb0f02a3682c90d4f4d68da18dae09e55f24d435314733e766ec.mdx";
/** Drifting snow behind the fighting plane, using the stock snowflake texture. */
export const STAGE_SNOW_MODEL = "war3mapImported\\StageSnow-917b74168e66aca0467360dffd3956aabf3e0b69503b2f26da0ddedc1e8a5bd4.mdx";
