// Generated by tools/animations/white-flash-models.ts; regenerate instead of editing.
export const WHITE_FIGHTER_MODELS: readonly string[] = [
  "war3mapImported\\ArcherWhite-d847d0b9e76603178965260fcc2a3efd2098a64d1ff27356480e4b84c7bf01e3.mdx",
  "war3mapImported\\RiflemanWhite-aa27bfcd18f4e64757343ea55e2cf5c617cdf16aa3c37de3410e283d57a16046.mdx",
  "war3mapImported\\IllidanWhite-60dc0712b0f3960494b58be3261777b3cd75317ee37ef0296d56b0f9888dff5d.mdx",
  "war3mapImported\\BlademasterWhite-56fba6dad67177de819bf65800788e9fd421b9bf3ff461901d56c95e7675e0d2.mdx",
  "war3mapImported\\MountainKingWhite-7ce9e975d61da07c8d00aa975bc7322afd31d31691dec955487529b95d147de1.mdx",
  "war3mapImported\\WardenWhite-827951155f021ff2cdcb154d0f2fded07b042cd1e9c04c2d03f5012fd23e42fd.mdx",
  "war3mapImported\\LichWhite-1af5f483c0fb9c8c06c9b80acf00e3e299896d6db6d43d5cf0133ad4d63b3620.mdx",
  "war3mapImported\\UtherWhite-bc60a0e092c036f89c704a32ef945c2624339f9399d26d158b4c031ff4590351.mdx",
  "war3mapImported\\DreadlordWhite-0ed4ab28a02f6caca283b13e65b2549ffab62b78a083a67db275c35b1b135a31.mdx",
  "war3mapImported\\ShadowHunterWhite-985db83ee1bc9cbf4907e337708b3aec0a23581723372298818c8e99b6697a61.mdx",
  "war3mapImported\\PitLordWhite-1947945c40164c185596e35ab4e676db978225966f61afab6d3a3cd296ab18dd.mdx",
  "war3mapImported\\BeastmasterWhite-b150e4bb66307c8d05b5ebc149b95b80933d9b79cbfdaec8a5f0aab848d77810.mdx",
  "war3mapImported\\LichKingWhite-9c6c318483342972ad65355b9dbe90e65fc2b86d4667790074fcbd0f6ac95c15.mdx",
  "war3mapImported\\ThrallWhite-ca629528805e2570f45ff937d45bf081445e4604d793258b0eef3454c8cff513.mdx"
];
