// Generated by tools/animations/white-flash-models.ts; regenerate instead of editing.
export const WHITE_FIGHTER_MODELS: readonly string[] = [
  "war3mapImported\\ArcherWhite-5599494d2e3da37f1d285f54607c66988896edf63dba223cebe01d19cc71f7e9.mdx",
  "war3mapImported\\RiflemanWhite-f74731bb86aca88ef047cc1362b6dcffa1b51519c750ed7670b8aeabdc49d3ef.mdx",
  "war3mapImported\\IllidanWhite-764afe9ed3b75426cf4e3303c9475029cfdb6bc879a870231f7c1bd17735f8f3.mdx",
  "war3mapImported\\BlademasterWhite-260734cfb9577d4c643355feaa92ff6497a4acb2142df75dc7cd2070f830a9a2.mdx",
  "war3mapImported\\MountainKingWhite-535afe7da7d2308248b3601c3ef9a3e800d8006a2f7cf0699a1bbe289c4217a2.mdx",
  "war3mapImported\\WardenWhite-0655f8acbce17a38b2d40c40e1543f67c5807e1f35683fb9d733068060cc0f3b.mdx",
  "war3mapImported\\LichWhite-ac76dec65d4c36d23ec87efeb8bc1708a5554f918c72e5be6ea15ad555d6a60f.mdx",
  "war3mapImported\\UtherWhite-bf42f479f0154e8991a03f51546e4b37bd34ab7f112d35aeb573667d4bf6ce36.mdx",
  "war3mapImported\\DreadlordWhite-612f66de162e9c38c03245493ec19ec4f933958fa4b1cc69eaa3cf9bfe59e2f6.mdx",
  "war3mapImported\\ShadowHunterWhite-911856adeb89d4c9dd34a33330de5e65d782aa751307fa215df609fae5782903.mdx",
  "war3mapImported\\PitLordWhite-2c9b512a87d1640390a55bf3515a4855f9700603d287e71759280c8ef486d557.mdx",
  "war3mapImported\\BeastmasterWhite-9faa3d568f7d520e0373b321827d7508b6148cbe6252ac62175ac4a2250625ac.mdx",
  "war3mapImported\\LichKingWhite-04ac205b2cdd4d50e1269f83269ac58e34b27148d5a353c78dcffcabfb6f58bb.mdx",
  "war3mapImported\\ThrallWhite-c78200f6c83811c8ced9d201e21e1eb87dd5a3ea8e4f36d128ab573593e6a332.mdx"
];
