import { assertEquals, assertTrue, test } from "wisp/src/runtime/testing";
import { Phase, beginRematchCountdown, confirmRematch, createMatchState, requestStageSelect, requestStart, returnToCharacters, selectCpuCharacter, selectStage, setAutomaticRematch, setCpuOpponent, setCpuTier, setParticipants, tickRematchCountdown } from "../match/rules";
import { Character } from "../sim/codes";
import { cpuOpponentSummary, resultNotice } from "../shell/messages";

test("CPU choices survive fighter/stage changes, New Match and the automatic rematch; Random reveals the drawn identity [k3 measure #185]", () => {
  const game = createMatchState();
  setParticipants(game, 3, 4);
  game.characterReadiness[0] = true;
  game.characterReadiness[1] = true;
  setCpuOpponent(game, 0, 2, "random");
  setCpuTier(game, 0, 2, "advanced");
  setAutomaticRematch(game, 0, true);
  selectCpuCharacter(game, 0, 2, Character.rifleman);
  assertTrue(requestStageSelect(game, 0));
  selectStage(game, 0, 0);
  returnToCharacters(game, 0);
  assertEquals(game.cpuOpponents[2], "random");
  assertEquals(game.cpuTiers[2], "advanced");
  assertTrue(requestStageSelect(game, 0));
  assertTrue(requestStart(game, 0));
  const summary = cpuOpponentSummary(game, 2);
  assertTrue(summary.includes("CPU 3 · ") && summary.endsWith(" · Advanced"));
  assertTrue(!summary.includes("Random"));
  game.startHold = 180;
  assertEquals(resultNotice(game, ""), "");
  game.phase = Phase.result;
  game.matchFrame = 120;
  confirmRematch(game, 0);
  assertTrue(confirmRematch(game, 1));
  assertEquals(game.cpuOpponents[2], "random");
  assertEquals(game.cpuTiers[2], "advanced");
  assertTrue(requestStageSelect(game, 0));
  assertTrue(requestStart(game, 0));
  assertEquals(game.cpuOpponents[2], "random");
  game.phase = Phase.result;
  beginRematchCountdown(game, 1);
  for (let frame = 0; frame < 59; frame++) tickRematchCountdown(game);
  assertTrue(tickRematchCountdown(game));
  assertEquals(game.cpuOpponents[2], "random");
  assertEquals(game.cpuTiers[2], "advanced");
  assertEquals(game.phase, Phase.match);
  assertTrue(cpuOpponentSummary(game, 2).endsWith(" · Advanced"));
});
