// Generated by wisp:scripts/wisp/frames.ts from the OpponentSettings definition. Do not edit.
export const OPPONENTSETTINGS_TOC = "war3mapImported\\OpponentSettings.toc";

export interface OpponentSettingsFrames {
  readonly root: framehandle;
  readonly backdrop: framehandle;
  readonly title: framehandle;
  readonly close: framehandle;
  readonly opponentCaption: framehandle;
  readonly opponentPrevious: framehandle;
  readonly opponentNext: framehandle;
  readonly opponentValue: framehandle;
  readonly difficultyCaption: framehandle;
  readonly difficultyPrevious: framehandle;
  readonly difficultyNext: framehandle;
  readonly difficultyValue: framehandle;
  readonly preview: framehandle;
  readonly done: framehandle;
  readonly prompt: framehandle;
}

/** Loads the TOC, then creates the OpponentSettings tree; context tells copies apart. */
export function createOpponentSettings(parent: framehandle, context: number): OpponentSettingsFrames | undefined {
  if (!BlzLoadTOCFile(OPPONENTSETTINGS_TOC)) return undefined;
  const root = BlzCreateFrame("OpponentSettings", parent, 0, context);
  BlzFrameSetAbsPoint(root, FRAMEPOINT_TOPLEFT, 0.11999999731779099, 0.4399999976158142);
  BlzFrameSetLevel(root, 100);
  const frames: OpponentSettingsFrames = {
    root,
    backdrop: BlzGetFrameByName("OpponentSettingsBackdrop", context),
    title: BlzGetFrameByName("OpponentSettingsTitle", context),
    close: BlzGetFrameByName("OpponentSettingsClose", context),
    opponentCaption: BlzGetFrameByName("OpponentSettingsOpponentCaption", context),
    opponentPrevious: BlzGetFrameByName("OpponentSettingsOpponentPrevious", context),
    opponentNext: BlzGetFrameByName("OpponentSettingsOpponentNext", context),
    opponentValue: BlzGetFrameByName("OpponentSettingsOpponentValue", context),
    difficultyCaption: BlzGetFrameByName("OpponentSettingsDifficultyCaption", context),
    difficultyPrevious: BlzGetFrameByName("OpponentSettingsDifficultyPrevious", context),
    difficultyNext: BlzGetFrameByName("OpponentSettingsDifficultyNext", context),
    difficultyValue: BlzGetFrameByName("OpponentSettingsDifficultyValue", context),
    preview: BlzGetFrameByName("OpponentSettingsPreview", context),
    done: BlzGetFrameByName("OpponentSettingsDone", context),
    prompt: BlzGetFrameByName("OpponentSettingsPrompt", context),
  };
  BlzFrameSetEnable(frames.backdrop, false);
  BlzFrameSetEnable(frames.title, false);
  BlzFrameSetText(frames.close, "Close");
  BlzFrameSetEnable(frames.opponentCaption, false);
  BlzFrameSetText(frames.opponentPrevious, "<");
  BlzFrameSetText(frames.opponentNext, ">");
  BlzFrameSetEnable(frames.opponentValue, false);
  BlzFrameSetEnable(frames.difficultyCaption, false);
  BlzFrameSetText(frames.difficultyPrevious, "<");
  BlzFrameSetText(frames.difficultyNext, ">");
  BlzFrameSetEnable(frames.difficultyValue, false);
  BlzFrameSetEnable(frames.preview, false);
  BlzFrameSetText(frames.done, "Done");
  BlzFrameSetEnable(frames.prompt, false);
  return frames;
}
