// Usage: WC3_STORAGE=CLIENT_INSTALL bun scripts/fighterViewBounds.ts
// Measures each fighter's drawn body, in model units, over its Stand sequences in both looks and
// rewrites src/game/presentation/fighterViewBounds.ts, which the match camera frames.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { FIGHTER_OBJECTS } from "../src/game/objectData";
import { Character } from "../src/game/sim/codes";
import { DrawnModel } from "./wisp/hurtboxView";
import { headlessRender } from "./wisp/headlessRender";

const LOOKS = ["classic", "definitive"] as const;
const SAMPLES = 12;
const STAND = /^stand(\s*-?\s*\d+)?$/i;

const renderer = headlessRender();
const rows: string[] = [];
for (const [name, character] of Object.entries(Character)) {
  const object = FIGHTER_OBJECTS[character];
  const looks: string[] = [];
  for (const look of LOOKS) {
    const { bytes, selected } = await renderer.resolveAsset(object.model, look);
    if (bytes === undefined) throw new Error(`${object.name}: no ${look} model for ${object.model}`);
    const model = new DrawnModel(bytes.slice().buffer, 1.0);
    const sequences: number[] = [];
    for (let index = 0; model.sequenceName(index) !== undefined; index++) if (STAND.test((model.sequenceName(index) ?? "").trim())) sequences.push(index);
    if (sequences.length === 0) throw new Error(`${object.name}: ${look} model has no Stand sequence`);
    let left = Infinity, right = -Infinity, bottom = Infinity, top = -Infinity;
    for (const sequence of sequences) for (let sample = 0; sample < SAMPLES; sample++) {
      const { vertices, drawn } = model.posed(sequence, sample * 0.25, 1);
      for (let vertex = 0; vertex < drawn.length; vertex++) {
        if (drawn[vertex] !== 1) continue;
        const x = vertices[vertex * 2] ?? 0, z = vertices[vertex * 2 + 1] ?? 0;
        left = Math.min(left, x); right = Math.max(right, x); bottom = Math.min(bottom, z); top = Math.max(top, z);
      }
    }
    const round = (value: number) => Math.round(value);
    looks.push(`${look}: { left: ${round(left)}, right: ${round(right)}, bottom: ${round(bottom)}, top: ${round(top)} }`);
    console.log(`${object.name.padEnd(22)} ${look.padEnd(10)} ${selected?.layer ?? "?"} left ${round(left)} right ${round(right)} bottom ${round(bottom)} top ${round(top)}`);
  }
  rows.push(`  [Character.${name}]: { ${looks.join(", ")} },`);
}

const out = join(import.meta.dir, "../src/game/presentation/fighterViewBounds.ts");
writeFileSync(out, `// Generated by \`bun scripts/fighterViewBounds.ts\` from each look's drawn Stand body in model units (the camera applies characterModelScale); regenerate after a body or model change.
import { Character } from "../sim/codes";

export interface ViewBounds {
  readonly left: number;
  readonly right: number;
  readonly bottom: number;
  readonly top: number;
}

export const FIGHTER_VIEW_BOUNDS: Readonly<Record<Character, { readonly classic: ViewBounds; readonly definitive: ViewBounds }>> = {
${rows.join("\n")}
};
`);
console.log(`wrote ${out}`);
