// The stage-select card spec (smashcraft:docs/design/stage-select.md): the
// hero cameras of stages with no zone art, the render grade, each stage's
// layout silhouette, and the hash of every input a rendered picture is drawn
// from, which ts/test/stage-thumbnails.test.ts compares with the last
// regeneration's record.
import { createHash } from "node:crypto";
import { STAGE_CATALOG, type StageTile } from "../src/game/menu/stageCatalog";
import { deckModel } from "../src/game/presentation/stagePreload";
import { stageLightModel, stageScenery, terrainPieces } from "../src/game/presentation/stageScenery";
import { surfaceCount, surfaceLeft, surfacePass, surfaceRight, surfaceZ } from "../src/game/sim/stage";
import { hasCannon } from "../src/game/sim/stageHazards";

/** Warcraft camera fields for the card, relative to the stage centre and the floor. */
export interface HeroCamera {
  /** CAMERA_FIELD_ROTATION in degrees; gameplay is 90 (looking along +y). */
  readonly rotation: number;
  /** CAMERA_FIELD_ANGLE_OF_ATTACK in degrees; gameplay is 350, 270 looks straight down. */
  readonly angleOfAttack: number;
  readonly distance: number;
  readonly fieldOfView: number;
  /** Target offset along the stage from its centre. */
  readonly x: number;
  /** Target height above the main deck's floor. */
  readonly z: number;
}

const HERO: HeroCamera = { rotation: 80.0, angleOfAttack: 340.0, distance: 1900.0, fieldOfView: 52.0, x: 0.0, z: -220.0 };

/** The stages with no fitting Warcraft zone art (stage-select.md, "Picture sources"): their pictures are hero-camera renders. */
export const HERO_CAMERAS: Readonly<Partial<Record<StageTile, HeroCamera>>> = {
  0: { ...HERO, distance: 1700.0 },
  11: { ...HERO },
  12: { ...HERO },
  13: { ...HERO },
};

export const RENDERED_STAGES = STAGE_CATALOG.map((entry) => entry.id).filter((stage) => HERO_CAMERAS[stage] !== undefined);

export const CARD = {
  /** The stored picture: square, the card's left part. */
  width: 512,
  height: 512,
  /** The headless render, at 1.5 times the picture for antialiasing. */
  renderWidth: 768,
  renderHeight: 768,
  /** IJG quality of the BLP's JPEG content. */
  quality: 82,
  /** ImageMagick operators every render gets after the stage is composited over its sky. */
  grade: ["-modulate", "100,94,100", "-sigmoidal-contrast", "2.5x42%"],
  /** The sky gradient: the stage's fog colour at the horizon, scaled by this at the top. */
  skyTop: 0.35,
} as const;

/** Silhouette pieces per card: enough for the stage with the most surfaces. */
export const SILHOUETTE_PIECES = 6;

/**
 * A stage's layout from its surfaces at rest, as [left, top, width, height]
 * fractions of the silhouette box's width (the box is half as tall as wide):
 * the main deck thick, platforms thin, at their true spacing.
 */
export function stageSilhouette(stage: StageTile): (readonly [number, number, number, number])[] {
  const surfaces = Array.from({ length: surfaceCount(stage) }, (_, index) => ({ left: surfaceLeft(stage, index, 0), right: surfaceRight(stage, index, 0), z: surfaceZ(stage, index, 0), main: index === 0 }));
  if (surfaces.length > SILHOUETTE_PIECES) throw new Error(`stage ${stage} has ${surfaces.length} surfaces; raise SILHOUETTE_PIECES`);
  const left = Math.min(...surfaces.map((surface) => surface.left)), right = Math.max(...surfaces.map((surface) => surface.right));
  const top = Math.max(...surfaces.map((surface) => surface.z)), bottom = Math.min(...surfaces.map((surface) => surface.z));
  const deck = 0.07, platform = 0.022, room = 0.5 - 0.06 - deck;
  const scale = Math.min(1 / (right - left), top === bottom ? Infinity : room / (top - bottom));
  const width = (right - left) * scale;
  // Map code holds binary32 values only.
  const round = (value: number) => Math.fround(Math.round(value * 1000) / 1000);
  return surfaces.map((surface) => [
    round((1 - width) / 2 + (surface.left - left) * scale), round(0.5 - deck - (surface.z - bottom) * scale),
    round((surface.right - surface.left) * scale), round(surface.main ? deck : platform),
  ] as const);
}

/** smashcraft:ts/src/game/menu/stageSilhouettes.ts as the current stage data draws it. */
export function silhouetteSource(): string {
  const rows = STAGE_CATALOG.map(({ id }) => `  ${id}: [${stageSilhouette(id).map((piece) => `[${piece.join(", ")}]`).join(", ")}],`);
  return [
    "// Generated by scripts/stageThumbnails.ts from the stages' surfaces; regenerate instead of editing.",
    "/** Each selectable stage's layout silhouette: [left, top, width, height] as fractions of the silhouette box's width. */",
    "export const STAGE_SILHOUETTES: Readonly<Record<number, readonly (readonly [number, number, number, number])[]>> = {",
    ...rows,
    "};",
    `/** Frames each card keeps for its silhouette. */`,
    `export const SILHOUETTE_PIECES = ${SILHOUETTE_PIECES};`,
    "",
  ].join("\n");
}

/** The archive file a stage's card is imported as, which the stage catalog names. */
export function thumbnailFile(stage: StageTile): string {
  const info = STAGE_CATALOG.find((entry) => entry.id === stage);
  if (info === undefined) throw new Error(`stage ${stage} is not selectable`);
  return info.texture.replace("war3mapImported\\", "");
}

/** Everything a rendered stage's picture is drawn from, besides the stage-assets files the build inputs name. */
export function stageArtInputs(stage: StageTile) {
  const surfaces = Array.from({ length: surfaceCount(stage) }, (_, index) => ({
    model: deckModel(stage, index), left: surfaceLeft(stage, index, 0), right: surfaceRight(stage, index, 0), z: surfaceZ(stage, index, 0), pass: surfacePass(stage, index),
  }));
  return {
    stage, file: thumbnailFile(stage),
    scenery: stageScenery(stage), terrain: terrainPieces(stage, true), light: stageLightModel(stage), cannon: hasCannon(stage), surfaces,
    camera: HERO_CAMERAS[stage], card: CARD,
  };
}

const sha256 = (text: string) => createHash("sha256").update(text).digest("hex");

/** The hash a rendered picture's inputs have now: its stage data and the stage-assets family. */
export function stageInputHash(stage: StageTile, stageAssets: string): string {
  return sha256(JSON.stringify({ art: stageArtInputs(stage), stageAssets }));
}

/** smashcraft:ts/stage-thumbnails.json: what the last regeneration drew each card from. */
export interface ThumbnailManifest {
  readonly family: string;
  readonly totalBytes: number;
  readonly stages: readonly { readonly stage: number; readonly file: string; readonly inputs: string; readonly sha256: string; readonly bytes: number }[];
}
