




import { createHash } from "node:crypto";
import { STAGE_CATALOG, type StageTile } from "../src/game/menu/stageCatalog";
import { deckModel, stageModels } from "../src/game/presentation/stagePreload";
import { placedPieces, stageScenery, terrainPieces } from "../src/game/presentation/stageScenery";
import { surfaceCount, surfaceLeft, surfacePass, surfaceRight, surfaceZ } from "../src/game/sim/stage";
import { hasCannon } from "../src/game/sim/stageHazards";


export interface HeroCamera {

  readonly rotation: number;

  readonly angleOfAttack: number;
  readonly distance: number;
  readonly fieldOfView: number;

  readonly x: number;

  readonly z: number;
}

const HERO: HeroCamera = { rotation: 80.0, angleOfAttack: 340.0, distance: 1900.0, fieldOfView: 52.0, x: 0.0, z: -220.0 };


export const HERO_CAMERAS: Readonly<Partial<Record<StageTile, HeroCamera>>> = {
  0: { ...HERO, distance: 1700.0 },
  11: { ...HERO },
  12: { ...HERO },
  13: { ...HERO },
};

export const RENDERED_STAGES = STAGE_CATALOG.map((entry) => entry.id).filter((stage) => HERO_CAMERAS[stage] !== undefined);

export const CARD = {

  width: 512,
  height: 512,

  renderWidth: 768,
  renderHeight: 768,

  quality: 82,

  grade: ["-modulate", "100,94,100", "-sigmoidal-contrast", "2.5x42%"],

  skyTop: 0.35,
} as const;


export const SILHOUETTE_PIECES = 6;






export function stageSilhouette(stage: StageTile): (readonly [number, number, number, number])[] {
  const surfaces = Array.from({ length: surfaceCount(stage) }, (_, index) => ({ left: surfaceLeft(stage, index, 0), right: surfaceRight(stage, index, 0), z: surfaceZ(stage, index, 0), main: index === 0 }));
  if (surfaces.length > SILHOUETTE_PIECES) throw new Error(`stage ${stage} has ${surfaces.length} surfaces; raise SILHOUETTE_PIECES`);
  const left = Math.min(...surfaces.map((surface) => surface.left)), right = Math.max(...surfaces.map((surface) => surface.right));
  const top = Math.max(...surfaces.map((surface) => surface.z)), bottom = Math.min(...surfaces.map((surface) => surface.z));
  const deck = 0.07, platform = 0.022, room = 0.5 - 0.06 - deck;
  const scale = Math.min(1 / (right - left), top === bottom ? Infinity : room / (top - bottom));
  const width = (right - left) * scale;

  const round = (value: number) => Math.fround(Math.round(value * 1000) / 1000);
  return surfaces.map((surface) => [
    round((1 - width) / 2 + (surface.left - left) * scale), round(0.5 - deck - (surface.z - bottom) * scale),
    round((surface.right - surface.left) * scale), round(surface.main ? deck : platform),
  ] as const);
}


export function silhouetteEntry(stage: StageTile): string {
  const info = STAGE_CATALOG.find((entry) => entry.id === stage);
  return `  // ${info?.name ?? stage}\n  ${stage}: [${stageSilhouette(stage).map((piece) => `[${piece.join(", ")}]`).join(", ")}],`;
}


export function silhouetteSource(): string {
  return [
    "// Generated by scripts/stageThumbnails.ts from the stages' surfaces; regenerate instead of editing.",
    "/** Each selectable stage's layout silhouette: [left, top, width, height] as fractions of the silhouette box's width. */",
    "export const STAGE_SILHOUETTES: Readonly<Record<number, readonly (readonly [number, number, number, number])[]>> = {",
    ...STAGE_CATALOG.map(({ id }) => silhouetteEntry(id)),
    "};",
    `/** Frames each card keeps for its silhouette. */`,
    `export const SILHOUETTE_PIECES = ${SILHOUETTE_PIECES};`,
    "",
  ].join("\n");
}


export function stageNamed(name: string): StageTile | undefined {
  return STAGE_CATALOG.find((entry) => entry.name.toLowerCase() === name.toLowerCase())?.id;
}


export function regenerateCommand(stage: StageTile): string {
  const info = STAGE_CATALOG.find((entry) => entry.id === stage);
  return `bun scripts/stageThumbnails.ts --stage ${JSON.stringify(info?.name ?? String(stage))}`;
}


export function thumbnailFile(stage: StageTile): string {
  const info = STAGE_CATALOG.find((entry) => entry.id === stage);
  if (info === undefined) throw new Error(`stage ${stage} is not selectable`);
  return info.texture.replace("war3mapImported\\", "");
}





export function stageArtInputs(stage: StageTile) {
  const surfaces = Array.from({ length: surfaceCount(stage) }, (_, index) => ({
    model: deckModel(stage, index), left: surfaceLeft(stage, index, 0), right: surfaceRight(stage, index, 0), z: surfaceZ(stage, index, 0), pass: surfacePass(stage, index),
  }));
  return {
    stage, file: thumbnailFile(stage),
    scenery: stageScenery(stage), terrain: terrainPieces(stage), pieces: placedPieces(stage), models: stageModels(stage), cannon: hasCannon(stage), surfaces,
    camera: HERO_CAMERAS[stage], card: CARD,
  };
}

const sha256 = (text: string) => createHash("sha256").update(text).digest("hex");


export function stageInputHash(stage: StageTile): string {
  return sha256(JSON.stringify(stageArtInputs(stage)));
}






export interface ThumbnailManifest {
  readonly stages: readonly { readonly stage: number; readonly file: string; readonly inputs: string; readonly sha256: string; readonly bytes: number }[];
}
