import { createPlacedObject, placedObject } from "../sim/fighter";
import { PARTICIPANT_CAPACITY } from "../input/participants";
import type { Fighter } from "../sim/fighter";
import { HERO_STATUS_GROUPS } from "../sim/codes";
import { shareFighterProjectiles } from "../sim/fighterProjectiles";


const retained = (activeMask: number, slot: number | undefined) =>
  (slot !== undefined && activeMask > 0 && activeMask < 16 && slot >= 0 && slot < 4 && (activeMask & (1 << slot)) !== 0 ? slot : undefined);







export function copyFighterState(target: Fighter, source: Readonly<Fighter>, activeMask: number): void {
  target.character = source.character;
  target.facing = source.facing;
  const tuning = target.tuning;
  const sourceTuning = source.tuning;
  tuning.physics = sourceTuning.physics;
  tuning.surface = sourceTuning.surface;
  tuning.ground = sourceTuning.ground;
  tuning.dashGrab = sourceTuning.dashGrab;
  tuning.shield = sourceTuning.shield;
  tuning.tech = sourceTuning.tech;
  tuning.shieldBreak = sourceTuning.shieldBreak;
  tuning.moves = sourceTuning.moves;
  tuning.specials = sourceTuning.specials;
  tuning.ultimate = sourceTuning.ultimate;

  const motion = target.motion;
  const sourceMotion = source.motion;
  motion.x = sourceMotion.x;
  motion.z = sourceMotion.z;
  motion.deltaX = sourceMotion.deltaX;
  motion.deltaZ = sourceMotion.deltaZ;
  motion.vx = sourceMotion.vx;
  motion.vz = sourceMotion.vz;
  motion.meleeX.original = sourceMotion.meleeX.original;
  motion.meleeX.published = sourceMotion.meleeX.published;
  motion.meleeZ.original = sourceMotion.meleeZ.original;
  motion.meleeZ.published = sourceMotion.meleeZ.published;
  motion.meleeVelocityZ.original = sourceMotion.meleeVelocityZ.original;
  motion.meleeVelocityZ.published = sourceMotion.meleeVelocityZ.published;
  motion.grounded = sourceMotion.grounded;
  motion.surface = sourceMotion.surface;
  motion.crouching = sourceMotion.crouching;
  motion.fastFalling = sourceMotion.fastFalling;
  motion.fastFallDownHeld = sourceMotion.fastFallDownHeld;
  motion.fastFallInputAge = sourceMotion.fastFallInputAge;
  motion.previousStickSide = sourceMotion.previousStickSide;
  motion.stickSideAge = sourceMotion.stickSideAge;
  motion.turnaroundSide = sourceMotion.turnaroundSide;
  motion.turnaroundAge = sourceMotion.turnaroundAge;

  const ground = target.ground;
  const sourceGround = source.ground;
  ground.dashFrame = sourceGround.dashFrame;
  ground.dashDirection = sourceGround.dashDirection;
  ground.action = sourceGround.action;
  ground.actionFrame = sourceGround.actionFrame;
  ground.runBrakeFramesRemaining = sourceGround.runBrakeFramesRemaining;
  ground.turnRunEntryFacing = sourceGround.turnRunEntryFacing;
  ground.turnRunFacingCommandLatched = sourceGround.turnRunFacingCommandLatched;
  ground.turnRunPausePending = sourceGround.turnRunPausePending;
  ground.dashGrabWindow = sourceGround.dashGrabWindow;

  const jump = target.jump;
  const sourceJump = source.jump;
  jump.inputAge = sourceJump.inputAge;
  jump.remaining = sourceJump.remaining;
  jump.serial = sourceJump.serial;
  jump.isDouble = sourceJump.isDouble;
  jump.squat = sourceJump.squat;
  jump.ascent = sourceJump.ascent;
  jump.held = sourceJump.held;
  jump.dodgeQueued = sourceJump.dodgeQueued;
  jump.dodgeX = sourceJump.dodgeX;
  jump.dodgeZ = sourceJump.dodgeZ;

  const launch = target.launch;
  const sourceLaunch = source.launch;
  launch.knockbackX = sourceLaunch.knockbackX;
  launch.knockbackZ = sourceLaunch.knockbackZ;
  launch.meleeKnockbackX.original = sourceLaunch.meleeKnockbackX.original;
  launch.meleeKnockbackX.published = sourceLaunch.meleeKnockbackX.published;
  launch.meleeKnockbackZ.original = sourceLaunch.meleeKnockbackZ.original;
  launch.meleeKnockbackZ.published = sourceLaunch.meleeKnockbackZ.published;
  launch.groundKnockbackX = sourceLaunch.groundKnockbackX;
  launch.knockbackAge = sourceLaunch.knockbackAge;
  launch.damageLevel = sourceLaunch.damageLevel;
  launch.hitstun = sourceLaunch.hitstun;
  launch.throwHitstun = sourceLaunch.throwHitstun;
  launch.hitlag = sourceLaunch.hitlag;
  launch.hitlagFrames = sourceLaunch.hitlagFrames;
  launch.hitlagEndAge = sourceLaunch.hitlagEndAge;
  launch.sdiFollowup = sourceLaunch.sdiFollowup;
  launch.diPending = sourceLaunch.diPending;
  launch.diLaunchSpeed = sourceLaunch.diLaunchSpeed;
  launch.diSerial = sourceLaunch.diSerial;
  launch.diAngleDegrees = sourceLaunch.diAngleDegrees;
  launch.sdiWasGrounded = sourceLaunch.sdiWasGrounded;
  launch.sdiLaunchesUpward = sourceLaunch.sdiLaunchesUpward;
  launch.sdiSerial = sourceLaunch.sdiSerial;
  launch.asdiSerial = sourceLaunch.asdiSerial;
  launch.sdiHitTravel = sourceLaunch.sdiHitTravel;
  launch.sdiStringTravel = sourceLaunch.sdiStringTravel;
  launch.sdiStepX = sourceLaunch.sdiStepX;
  launch.sdiStepZ = sourceLaunch.sdiStepZ;
  launch.sdiStepTravel = sourceLaunch.sdiStepTravel;
  launch.sdiNextX = sourceLaunch.sdiNextX;
  launch.sdiNextZ = sourceLaunch.sdiNextZ;
  launch.sdiNextTravel = sourceLaunch.sdiNextTravel;

  const shield = target.shield;
  const sourceShield = source.shield;
  shield.raised = sourceShield.raised;
  shield.tiltX = sourceShield.tiltX;
  shield.tiltZ = sourceShield.tiltZ;
  shield.strength = sourceShield.strength;
  shield.energy = sourceShield.energy;
  shield.stun = sourceShield.stun;
  shield.heldFrames = sourceShield.heldFrames;
  shield.releaseLag = sourceShield.releaseLag;
  shield.pushbackX = sourceShield.pushbackX;
  shield.recoilX = sourceShield.recoilX;
  shield.recoilZ = sourceShield.recoilZ;
  shield.meleeRecoilX.original = sourceShield.meleeRecoilX.original;
  shield.meleeRecoilX.published = sourceShield.meleeRecoilX.published;
  shield.meleeRecoilZ.original = sourceShield.meleeRecoilZ.original;
  shield.meleeRecoilZ.published = sourceShield.meleeRecoilZ.published;
  shield.drainResumePending = sourceShield.drainResumePending;
  shield.triggerWasActive = sourceShield.triggerWasActive;
  shield.triggerAge = sourceShield.triggerAge;
  shield.reflectFrames = sourceShield.reflectFrames;
  shield.perfectFrames = sourceShield.perfectFrames;
  shield.perfectActionFrames = sourceShield.perfectActionFrames;
  shield.redParryTried = sourceShield.redParryTried;
  shield.parryBuffer = sourceShield.parryBuffer;
  shield.parryBufferDirection = sourceShield.parryBufferDirection;
  shield.breakState = sourceShield.breakState;
  shield.breakFrame = sourceShield.breakFrame;
  shield.breakSerial = sourceShield.breakSerial;
  shield.breakRemaining = sourceShield.breakRemaining;

  const attack = target.attack;
  const sourceAttack = source.attack;
  attack.style = sourceAttack.style;
  attack.frame = sourceAttack.frame;
  attack.duration = sourceAttack.duration;
  attack.serial = sourceAttack.serial;
  attack.hit = sourceAttack.hit;
  attack.dashGrab = sourceAttack.dashGrab;
  attack.pivotGrab = sourceAttack.pivotGrab;
  attack.cooldown = sourceAttack.cooldown;
  attack.smashCharging = sourceAttack.smashCharging;
  attack.smashChargeFrames = sourceAttack.smashChargeFrames;
  attack.smashChargeAllowed = sourceAttack.smashChargeAllowed;

  const hits = target.hits;
  const sourceHits = source.hits;

  let hit = 0;
  for (const to of hits.entries) {
    const from = sourceHits.entries[hit++];
    if (from === undefined) throw new Error(`no hit entry ${hit - 1} to copy`);
    to.attacker = retained(activeMask, from.attacker);
    to.attackSerial = from.attackSerial;
    to.window = from.window;
  }
  hits.lastAttacker = retained(activeMask, sourceHits.lastAttacker);
  hits.lastAttackSerial = sourceHits.lastAttackSerial;
  hits.lastWindow = sourceHits.lastWindow;

  const visuals = target.visuals;
  const sourceVisuals = source.visuals;
  visuals.grab = sourceVisuals.grab;
  visuals.throw = sourceVisuals.throw;
  visuals.hit = sourceVisuals.hit;
  visuals.hitElectric = sourceVisuals.hitElectric;
  visuals.hitElement = sourceVisuals.hitElement;
  visuals.hitStrength = sourceVisuals.hitStrength;
  visuals.hitHeight = sourceVisuals.hitHeight;
  visuals.hitPummel = sourceVisuals.hitPummel;
  visuals.shieldElectric = sourceVisuals.shieldElectric;
  visuals.shield = sourceVisuals.shield;
  visuals.shieldReflect = sourceVisuals.shieldReflect;
  visuals.manaDrained = sourceVisuals.manaDrained;
  visuals.manaDenied = sourceVisuals.manaDenied;

  const special = target.special;
  const sourceSpecial = source.special;
  special.action = sourceSpecial.action;
  special.ex = sourceSpecial.ex;
  special.exArmorUsed = sourceSpecial.exArmorUsed;
  special.frame = sourceSpecial.frame;
  special.duration = sourceSpecial.duration;
  special.lockFrames = sourceSpecial.lockFrames;
  special.fall = sourceSpecial.fall;

  const cooldowns = special.cooldowns;
  const sourceCooldowns = sourceSpecial.cooldowns;
  for (let i = 0; i < cooldowns.length; i++) cooldowns[i] = sourceCooldowns[i] ?? 0;
  special.direction = sourceSpecial.direction;
  special.hit = sourceSpecial.hit;
  for (let i = 0; i < PARTICIPANT_CAPACITY; i++) special.hitTargets[i] = retained(activeMask, sourceSpecial.hitTargets[i]);
  special.form = sourceSpecial.form;
  special.aimX = sourceSpecial.aimX;
  special.aimZ = sourceSpecial.aimZ;
  special.airtimeUses = sourceSpecial.airtimeUses;
  special.grabFrame = sourceSpecial.grabFrame;
  special.guarded = sourceSpecial.guarded;

  shareFighterProjectiles(target, source);

  const bear = target.bear;
  const sourceBear = source.bear;
  bear.exDamage = sourceBear.exDamage;
  bear.life = sourceBear.life;
  bear.x = sourceBear.x;
  bear.z = sourceBear.z;
  bear.velocityX = sourceBear.velocityX;
  bear.velocityZ = sourceBear.velocityZ;
  bear.swipeCooldown = sourceBear.swipeCooldown;
  bear.hitSerial = sourceBear.hitSerial;
  bear.surface = sourceBear.surface;
  const trap = target.freezeTrap;
  const sourceTrap = source.freezeTrap;
  trap.exReach = sourceTrap.exReach;
  trap.life = sourceTrap.life;
  trap.arming = sourceTrap.arming;
  trap.x = sourceTrap.x;
  trap.z = sourceTrap.z;
  trap.surface = sourceTrap.surface;
  trap.serial = sourceTrap.serial;
  trap.cooldown = sourceTrap.cooldown;

  const dodge = target.dodge;
  const sourceDodge = source.dodge;
  dodge.airDodging = sourceDodge.airDodging;
  dodge.airFrame = sourceDodge.airFrame;
  dodge.airUsed = sourceDodge.airUsed;
  dodge.airMotionFrames = sourceDodge.airMotionFrames;
  dodge.groundFrame = sourceDodge.groundFrame;
  dodge.groundDirection = sourceDodge.groundDirection;
  dodge.groundEntryFacing = sourceDodge.groundEntryFacing;
  const landing = target.landing;
  const sourceLanding = source.landing;
  landing.lag = sourceLanding.lag;
  const down = target.down;
  const sourceDown = source.down;
  down.state = sourceDown.state;
  down.frame = sourceDown.frame;
  down.direction = sourceDown.direction;
  down.waitRemaining = sourceDown.waitRemaining;
  down.faceUp = sourceDown.faceUp;
  down.attackQueued = sourceDown.attackQueued;
  const tech = target.tech;
  const sourceTech = source.tech;
  tech.window = sourceTech.window;
  tech.pressAge = sourceTech.pressAge;
  tech.previousPressAge = sourceTech.previousPressAge;
  tech.accumulatedPress = sourceTech.accumulatedPress;
  const recovery = target.surfaceRecovery;
  const sourceRecovery = source.surfaceRecovery;
  recovery.state = sourceRecovery.state;
  recovery.frame = sourceRecovery.frame;
  recovery.velocityApplied = sourceRecovery.velocityApplied;
  recovery.wallJumpQueued = sourceRecovery.wallJumpQueued;
  recovery.wallJumpRepeat = sourceRecovery.wallJumpRepeat;
  recovery.wallJumpAge = sourceRecovery.wallJumpAge;
  recovery.wallJumpSide = sourceRecovery.wallJumpSide;
  recovery.wallJumpsUsed = sourceRecovery.wallJumpsUsed;
  recovery.reflectCooldown = sourceRecovery.reflectCooldown;
  recovery.lastReflectedSurface = sourceRecovery.lastReflectedSurface;
  recovery.contactSerial = sourceRecovery.contactSerial;
  recovery.contactKind = sourceRecovery.contactKind;
  recovery.contactApproachSpeed = sourceRecovery.contactApproachSpeed;
  recovery.contactX = sourceRecovery.contactX;
  recovery.contactZ = sourceRecovery.contactZ;
  recovery.contactNormalX = sourceRecovery.contactNormalX;
  recovery.contactNormalZ = sourceRecovery.contactNormalZ;
  const grab = target.grab;
  const sourceGrab = source.grab;
  grab.grabbedFrames = sourceGrab.grabbedFrames;
  grab.action = sourceGrab.action;
  grab.frame = sourceGrab.frame;
  grab.serial = sourceGrab.serial;
  grab.pummels = sourceGrab.pummels;
  grab.heldFrames = sourceGrab.heldFrames;
  grab.queuedThrow = sourceGrab.queuedThrow;
  grab.mashX = sourceGrab.mashX;
  grab.mashZ = sourceGrab.mashZ;
  grab.owner = retained(activeMask, sourceGrab.owner);
  grab.target = retained(activeMask, sourceGrab.target);
  const ledge = target.ledge;
  const sourceLedge = source.ledge;
  ledge.state = sourceLedge.state;
  ledge.side = sourceLedge.side;
  ledge.frame = sourceLedge.frame;
  ledge.serial = sourceLedge.serial;
  ledge.intangible = sourceLedge.intangible;
  ledge.regrab = sourceLedge.regrab;
  ledge.grabs = sourceLedge.grabs;
  const platform = target.platform;
  const sourcePlatform = source.platform;
  platform.move = sourcePlatform.move;
  platform.frame = sourcePlatform.frame;
  platform.duration = sourcePlatform.duration;
  platform.deck = sourcePlatform.deck;
  platform.fromX = sourcePlatform.fromX;
  platform.toX = sourcePlatform.toX;
  platform.fromZ = sourcePlatform.fromZ;
  platform.toZ = sourcePlatform.toZ;
  platform.rise = sourcePlatform.rise;
  platform.stand = sourcePlatform.stand;
  platform.shield = sourcePlatform.shield;
  platform.upFrames = sourcePlatform.upFrames;
  platform.landedFrames = sourcePlatform.landedFrames;
  platform.dodgeQueued = sourcePlatform.dodgeQueued;
  platform.dodgeX = sourcePlatform.dodgeX;
  platform.dodgeZ = sourcePlatform.dodgeZ;
  platform.specialQueued = sourcePlatform.specialQueued;
  platform.specialX = sourcePlatform.specialX;
  platform.specialZ = sourcePlatform.specialZ;
  const cannon = target.cannon;
  const sourceCannon = source.cannon;
  cannon.held = sourceCannon.held;
  cannon.firing = sourceCannon.firing;
  cannon.cooldown = sourceCannon.cooldown;
  cannon.passing = sourceCannon.passing;
  const water = target.water;
  const sourceWater = source.water;
  water.inWater = sourceWater.inWater;
  water.frames = sourceWater.frames;
  water.entries = sourceWater.entries;
  water.hydraFrame = sourceWater.hydraFrame;
  water.hydraX = sourceWater.hydraX;
  water.hydraStrikeFrame = sourceWater.hydraStrikeFrame;
  const status = target.status;
  const sourceStatus = source.status;
  status.damage = sourceStatus.damage;
  status.offscreenFrames = sourceStatus.offscreenFrames;
  status.stocks = sourceStatus.stocks;
  status.respawn = sourceStatus.respawn;
  status.out = sourceStatus.out;
  status.invincible = sourceStatus.invincible;
  status.frozenFrames = sourceStatus.frozenFrames;
  status.freezeImmunityFrames = sourceStatus.freezeImmunityFrames;
  status.armorFrames = sourceStatus.armorFrames;
  status.armorMaxDamage = sourceStatus.armorMaxDamage;
  status.armorChills = sourceStatus.armorChills;
  status.condition = sourceStatus.condition;
  status.conditionFrames = sourceStatus.conditionFrames;
  status.conditionGroup = sourceStatus.conditionGroup;
  status.conditionImmunityFrames = sourceStatus.conditionImmunityFrames;
  for (let i = 0; i < HERO_STATUS_GROUPS; i++) status.conditionImmunity[i] = sourceStatus.conditionImmunity[i] ?? 0;
  status.poisonFrames = sourceStatus.poisonFrames;
  status.poisonEvery = sourceStatus.poisonEvery;
  status.poisonDamage = sourceStatus.poisonDamage;
  status.divineFrames = sourceStatus.divineFrames;
  status.buff = sourceStatus.buff;
  status.buffFrames = sourceStatus.buffFrames;

  const mana = target.mana;
  const sourceMana = source.mana;
  mana.points = sourceMana.points;


  while (target.pack.length < source.pack.length) target.pack.push(createPlacedObject());
  target.pack.length = source.pack.length;
  for (let animal = 0; animal <= source.pack.length; animal++) {
    const placed = placedObject(target, animal);
    const sourcePlaced = placedObject(source, animal);
    placed.life = sourcePlaced.life;
    placed.age = sourcePlaced.age;
    placed.x = sourcePlaced.x;
    placed.z = sourcePlaced.z;
    placed.direction = sourcePlaced.direction;
    placed.durability = sourcePlaced.durability;
    placed.serial = sourcePlaced.serial;
    placed.spec = sourcePlaced.spec;
    for (let slot = 0; slot < PARTICIPANT_CAPACITY; slot++) placed.struck[slot] = sourcePlaced.struck[slot];
    placed.specialStruck = sourcePlaced.specialStruck;
    placed.mode = sourcePlaced.mode;
    placed.modeFrame = sourcePlaced.modeFrame;
    placed.apart = sourcePlaced.apart;
    placed.bitten = sourcePlaced.bitten;
    placed.surface = sourcePlaced.surface;
  }
}


const RECORD_DEPTH = 6;


function sameRecord<T extends object>(a: Readonly<T>, b: Readonly<T>, depth: number): boolean {
  if (depth > RECORD_DEPTH) return false;
  let fields = 0;
  for (const key in a) {
    const x = a[key];
    if (x === undefined) continue;
    fields++;
    const y = b[key];
    if (x === y) {
      if (x === 0 && typeof x === "number" && typeof y === "number" && 1 / x !== 1 / y) return false;
      continue;
    }
    if (typeof x !== "object" || typeof y !== "object" || x === null || y === null || !sameRecord(x, y, depth + 1)) return false;
  }
  for (const key in b) if (b[key] !== undefined) fields--;
  return fields === 0;
}





export function sameFighterState(target: Readonly<Fighter>, source: Readonly<Fighter>): boolean {
  if (target.character !== source.character) return false;
  if (target.facing !== source.facing || (target.facing === 0 && 1 / target.facing !== 1 / source.facing)) return false;
  const tuning = target.tuning;
  const sourceTuning = source.tuning;
  if (tuning.physics !== sourceTuning.physics) return false;
  if (tuning.surface !== sourceTuning.surface) return false;
  if (tuning.ground !== sourceTuning.ground) return false;
  if (tuning.dashGrab !== sourceTuning.dashGrab) return false;
  if (tuning.shield !== sourceTuning.shield) return false;
  if (tuning.tech !== sourceTuning.tech) return false;
  if (tuning.shieldBreak !== sourceTuning.shieldBreak) return false;
  if (tuning.moves !== sourceTuning.moves) return false;
  if (tuning.specials !== sourceTuning.specials) return false;
  if (tuning.ultimate !== sourceTuning.ultimate) return false;

  const motion = target.motion;
  const sourceMotion = source.motion;
  if (motion.x !== sourceMotion.x || (motion.x === 0 && 1 / motion.x !== 1 / sourceMotion.x)) return false;
  if (motion.z !== sourceMotion.z || (motion.z === 0 && 1 / motion.z !== 1 / sourceMotion.z)) return false;
  if (motion.deltaX !== sourceMotion.deltaX || (motion.deltaX === 0 && 1 / motion.deltaX !== 1 / sourceMotion.deltaX)) return false;
  if (motion.deltaZ !== sourceMotion.deltaZ || (motion.deltaZ === 0 && 1 / motion.deltaZ !== 1 / sourceMotion.deltaZ)) return false;
  if (motion.vx !== sourceMotion.vx || (motion.vx === 0 && 1 / motion.vx !== 1 / sourceMotion.vx)) return false;
  if (motion.vz !== sourceMotion.vz || (motion.vz === 0 && 1 / motion.vz !== 1 / sourceMotion.vz)) return false;
  if (motion.meleeX.original !== sourceMotion.meleeX.original || (motion.meleeX.original === 0 && 1 / motion.meleeX.original !== 1 / sourceMotion.meleeX.original)) return false;
  if (motion.meleeX.published !== sourceMotion.meleeX.published || (motion.meleeX.published === 0 && 1 / motion.meleeX.published !== 1 / sourceMotion.meleeX.published)) return false;
  if (motion.meleeZ.original !== sourceMotion.meleeZ.original || (motion.meleeZ.original === 0 && 1 / motion.meleeZ.original !== 1 / sourceMotion.meleeZ.original)) return false;
  if (motion.meleeZ.published !== sourceMotion.meleeZ.published || (motion.meleeZ.published === 0 && 1 / motion.meleeZ.published !== 1 / sourceMotion.meleeZ.published)) return false;
  if (motion.meleeVelocityZ.original !== sourceMotion.meleeVelocityZ.original || (motion.meleeVelocityZ.original === 0 && 1 / motion.meleeVelocityZ.original !== 1 / sourceMotion.meleeVelocityZ.original)) return false;
  if (motion.meleeVelocityZ.published !== sourceMotion.meleeVelocityZ.published || (motion.meleeVelocityZ.published === 0 && 1 / motion.meleeVelocityZ.published !== 1 / sourceMotion.meleeVelocityZ.published)) return false;
  if (motion.grounded !== sourceMotion.grounded) return false;
  if (motion.surface !== sourceMotion.surface || (motion.surface === 0 && sourceMotion.surface === 0 && 1 / motion.surface !== 1 / sourceMotion.surface)) return false;
  if (motion.crouching !== sourceMotion.crouching) return false;
  if (motion.fastFalling !== sourceMotion.fastFalling) return false;
  if (motion.fastFallDownHeld !== sourceMotion.fastFallDownHeld) return false;
  if (motion.fastFallInputAge !== sourceMotion.fastFallInputAge || (motion.fastFallInputAge === 0 && 1 / motion.fastFallInputAge !== 1 / sourceMotion.fastFallInputAge)) return false;
  if (motion.previousStickSide !== sourceMotion.previousStickSide || (motion.previousStickSide === 0 && 1 / motion.previousStickSide !== 1 / sourceMotion.previousStickSide)) return false;
  if (motion.stickSideAge !== sourceMotion.stickSideAge || (motion.stickSideAge === 0 && 1 / motion.stickSideAge !== 1 / sourceMotion.stickSideAge)) return false;
  if (motion.turnaroundSide !== sourceMotion.turnaroundSide || (motion.turnaroundSide === 0 && 1 / motion.turnaroundSide !== 1 / sourceMotion.turnaroundSide)) return false;
  if (motion.turnaroundAge !== sourceMotion.turnaroundAge || (motion.turnaroundAge === 0 && 1 / motion.turnaroundAge !== 1 / sourceMotion.turnaroundAge)) return false;

  const ground = target.ground;
  const sourceGround = source.ground;
  if (ground.dashFrame !== sourceGround.dashFrame || (ground.dashFrame === 0 && 1 / ground.dashFrame !== 1 / sourceGround.dashFrame)) return false;
  if (ground.dashDirection !== sourceGround.dashDirection || (ground.dashDirection === 0 && 1 / ground.dashDirection !== 1 / sourceGround.dashDirection)) return false;
  if (ground.action !== sourceGround.action || (ground.action === 0 && 1 / ground.action !== 1 / sourceGround.action)) return false;
  if (ground.actionFrame !== sourceGround.actionFrame || (ground.actionFrame === 0 && 1 / ground.actionFrame !== 1 / sourceGround.actionFrame)) return false;
  if (ground.runBrakeFramesRemaining !== sourceGround.runBrakeFramesRemaining || (ground.runBrakeFramesRemaining === 0 && 1 / ground.runBrakeFramesRemaining !== 1 / sourceGround.runBrakeFramesRemaining)) return false;
  if (ground.turnRunEntryFacing !== sourceGround.turnRunEntryFacing || (ground.turnRunEntryFacing === 0 && 1 / ground.turnRunEntryFacing !== 1 / sourceGround.turnRunEntryFacing)) return false;
  if (ground.turnRunFacingCommandLatched !== sourceGround.turnRunFacingCommandLatched) return false;
  if (ground.turnRunPausePending !== sourceGround.turnRunPausePending) return false;
  if (ground.dashGrabWindow !== sourceGround.dashGrabWindow || (ground.dashGrabWindow === 0 && 1 / ground.dashGrabWindow !== 1 / sourceGround.dashGrabWindow)) return false;

  const jump = target.jump;
  const sourceJump = source.jump;
  if (jump.inputAge !== sourceJump.inputAge || (jump.inputAge === 0 && 1 / jump.inputAge !== 1 / sourceJump.inputAge)) return false;
  if (jump.remaining !== sourceJump.remaining || (jump.remaining === 0 && 1 / jump.remaining !== 1 / sourceJump.remaining)) return false;
  if (jump.serial !== sourceJump.serial || (jump.serial === 0 && 1 / jump.serial !== 1 / sourceJump.serial)) return false;
  if (jump.isDouble !== sourceJump.isDouble) return false;
  if (jump.squat !== sourceJump.squat || (jump.squat === 0 && 1 / jump.squat !== 1 / sourceJump.squat)) return false;
  if (jump.ascent !== sourceJump.ascent || (jump.ascent === 0 && 1 / jump.ascent !== 1 / sourceJump.ascent)) return false;
  if (jump.held !== sourceJump.held) return false;
  if (jump.dodgeQueued !== sourceJump.dodgeQueued) return false;
  if (jump.dodgeX !== sourceJump.dodgeX || (jump.dodgeX === 0 && 1 / jump.dodgeX !== 1 / sourceJump.dodgeX)) return false;
  if (jump.dodgeZ !== sourceJump.dodgeZ || (jump.dodgeZ === 0 && 1 / jump.dodgeZ !== 1 / sourceJump.dodgeZ)) return false;

  const launch = target.launch;
  const sourceLaunch = source.launch;
  if (launch.knockbackX !== sourceLaunch.knockbackX || (launch.knockbackX === 0 && 1 / launch.knockbackX !== 1 / sourceLaunch.knockbackX)) return false;
  if (launch.knockbackZ !== sourceLaunch.knockbackZ || (launch.knockbackZ === 0 && 1 / launch.knockbackZ !== 1 / sourceLaunch.knockbackZ)) return false;
  if (launch.meleeKnockbackX.original !== sourceLaunch.meleeKnockbackX.original || (launch.meleeKnockbackX.original === 0 && 1 / launch.meleeKnockbackX.original !== 1 / sourceLaunch.meleeKnockbackX.original)) return false;
  if (launch.meleeKnockbackX.published !== sourceLaunch.meleeKnockbackX.published || (launch.meleeKnockbackX.published === 0 && 1 / launch.meleeKnockbackX.published !== 1 / sourceLaunch.meleeKnockbackX.published)) return false;
  if (launch.meleeKnockbackZ.original !== sourceLaunch.meleeKnockbackZ.original || (launch.meleeKnockbackZ.original === 0 && 1 / launch.meleeKnockbackZ.original !== 1 / sourceLaunch.meleeKnockbackZ.original)) return false;
  if (launch.meleeKnockbackZ.published !== sourceLaunch.meleeKnockbackZ.published || (launch.meleeKnockbackZ.published === 0 && 1 / launch.meleeKnockbackZ.published !== 1 / sourceLaunch.meleeKnockbackZ.published)) return false;
  if (launch.groundKnockbackX !== sourceLaunch.groundKnockbackX || (launch.groundKnockbackX === 0 && 1 / launch.groundKnockbackX !== 1 / sourceLaunch.groundKnockbackX)) return false;
  if (launch.knockbackAge !== sourceLaunch.knockbackAge || (launch.knockbackAge === 0 && sourceLaunch.knockbackAge === 0 && 1 / launch.knockbackAge !== 1 / sourceLaunch.knockbackAge)) return false;
  if (launch.damageLevel !== sourceLaunch.damageLevel || (launch.damageLevel === 0 && 1 / launch.damageLevel !== 1 / sourceLaunch.damageLevel)) return false;
  if (launch.hitstun !== sourceLaunch.hitstun || (launch.hitstun === 0 && 1 / launch.hitstun !== 1 / sourceLaunch.hitstun)) return false;
  if (launch.throwHitstun !== sourceLaunch.throwHitstun) return false;
  if (launch.hitlag !== sourceLaunch.hitlag || (launch.hitlag === 0 && 1 / launch.hitlag !== 1 / sourceLaunch.hitlag)) return false;
  if (launch.diPending !== sourceLaunch.diPending) return false;
  if (launch.hitlagFrames !== sourceLaunch.hitlagFrames) return false;
  if (launch.hitlagEndAge !== sourceLaunch.hitlagEndAge) return false;
  if (launch.sdiFollowup !== sourceLaunch.sdiFollowup) return false;
  if (launch.diLaunchSpeed !== sourceLaunch.diLaunchSpeed || (launch.diLaunchSpeed === 0 && 1 / launch.diLaunchSpeed !== 1 / sourceLaunch.diLaunchSpeed)) return false;
  if (launch.diSerial !== sourceLaunch.diSerial || (launch.diSerial === 0 && 1 / launch.diSerial !== 1 / sourceLaunch.diSerial)) return false;
  if (launch.diAngleDegrees !== sourceLaunch.diAngleDegrees || (launch.diAngleDegrees === 0 && 1 / launch.diAngleDegrees !== 1 / sourceLaunch.diAngleDegrees)) return false;
  if (launch.sdiWasGrounded !== sourceLaunch.sdiWasGrounded) return false;
  if (launch.sdiLaunchesUpward !== sourceLaunch.sdiLaunchesUpward) return false;
  if (launch.sdiSerial !== sourceLaunch.sdiSerial || (launch.sdiSerial === 0 && 1 / launch.sdiSerial !== 1 / sourceLaunch.sdiSerial)) return false;
  if (launch.asdiSerial !== sourceLaunch.asdiSerial || (launch.asdiSerial === 0 && 1 / launch.asdiSerial !== 1 / sourceLaunch.asdiSerial)) return false;
  if (launch.sdiHitTravel !== sourceLaunch.sdiHitTravel || (launch.sdiHitTravel === 0 && 1 / launch.sdiHitTravel !== 1 / sourceLaunch.sdiHitTravel)) return false;
  if (launch.sdiStringTravel !== sourceLaunch.sdiStringTravel || (launch.sdiStringTravel === 0 && 1 / launch.sdiStringTravel !== 1 / sourceLaunch.sdiStringTravel)) return false;
  if (launch.sdiStepX !== sourceLaunch.sdiStepX || (launch.sdiStepX === 0 && 1 / launch.sdiStepX !== 1 / sourceLaunch.sdiStepX)) return false;
  if (launch.sdiStepZ !== sourceLaunch.sdiStepZ || (launch.sdiStepZ === 0 && 1 / launch.sdiStepZ !== 1 / sourceLaunch.sdiStepZ)) return false;
  if (launch.sdiStepTravel !== sourceLaunch.sdiStepTravel || (launch.sdiStepTravel === 0 && 1 / launch.sdiStepTravel !== 1 / sourceLaunch.sdiStepTravel)) return false;
  if (launch.sdiNextX !== sourceLaunch.sdiNextX || (launch.sdiNextX === 0 && 1 / launch.sdiNextX !== 1 / sourceLaunch.sdiNextX)) return false;
  if (launch.sdiNextZ !== sourceLaunch.sdiNextZ || (launch.sdiNextZ === 0 && 1 / launch.sdiNextZ !== 1 / sourceLaunch.sdiNextZ)) return false;
  if (launch.sdiNextTravel !== sourceLaunch.sdiNextTravel || (launch.sdiNextTravel === 0 && 1 / launch.sdiNextTravel !== 1 / sourceLaunch.sdiNextTravel)) return false;

  const shield = target.shield;
  const sourceShield = source.shield;
  if (shield.raised !== sourceShield.raised) return false;
  if (shield.tiltX !== sourceShield.tiltX || (shield.tiltX === 0 && 1 / shield.tiltX !== 1 / sourceShield.tiltX)) return false;
  if (shield.tiltZ !== sourceShield.tiltZ || (shield.tiltZ === 0 && 1 / shield.tiltZ !== 1 / sourceShield.tiltZ)) return false;
  if (shield.strength !== sourceShield.strength || (shield.strength === 0 && 1 / shield.strength !== 1 / sourceShield.strength)) return false;
  if (shield.energy !== sourceShield.energy || (shield.energy === 0 && 1 / shield.energy !== 1 / sourceShield.energy)) return false;
  if (shield.stun !== sourceShield.stun || (shield.stun === 0 && 1 / shield.stun !== 1 / sourceShield.stun)) return false;
  if (shield.heldFrames !== sourceShield.heldFrames || (shield.heldFrames === 0 && 1 / shield.heldFrames !== 1 / sourceShield.heldFrames)) return false;
  if (shield.releaseLag !== sourceShield.releaseLag || (shield.releaseLag === 0 && 1 / shield.releaseLag !== 1 / sourceShield.releaseLag)) return false;
  if (shield.pushbackX !== sourceShield.pushbackX || (shield.pushbackX === 0 && 1 / shield.pushbackX !== 1 / sourceShield.pushbackX)) return false;
  if (shield.recoilX !== sourceShield.recoilX || (shield.recoilX === 0 && 1 / shield.recoilX !== 1 / sourceShield.recoilX)) return false;
  if (shield.recoilZ !== sourceShield.recoilZ || (shield.recoilZ === 0 && 1 / shield.recoilZ !== 1 / sourceShield.recoilZ)) return false;
  if (shield.meleeRecoilX.original !== sourceShield.meleeRecoilX.original || (shield.meleeRecoilX.original === 0 && 1 / shield.meleeRecoilX.original !== 1 / sourceShield.meleeRecoilX.original)) return false;
  if (shield.meleeRecoilX.published !== sourceShield.meleeRecoilX.published || (shield.meleeRecoilX.published === 0 && 1 / shield.meleeRecoilX.published !== 1 / sourceShield.meleeRecoilX.published)) return false;
  if (shield.meleeRecoilZ.original !== sourceShield.meleeRecoilZ.original || (shield.meleeRecoilZ.original === 0 && 1 / shield.meleeRecoilZ.original !== 1 / sourceShield.meleeRecoilZ.original)) return false;
  if (shield.meleeRecoilZ.published !== sourceShield.meleeRecoilZ.published || (shield.meleeRecoilZ.published === 0 && 1 / shield.meleeRecoilZ.published !== 1 / sourceShield.meleeRecoilZ.published)) return false;
  if (shield.drainResumePending !== sourceShield.drainResumePending) return false;
  if (shield.triggerWasActive !== sourceShield.triggerWasActive) return false;
  if (shield.triggerAge !== sourceShield.triggerAge || (shield.triggerAge === 0 && 1 / shield.triggerAge !== 1 / sourceShield.triggerAge)) return false;
  if (shield.reflectFrames !== sourceShield.reflectFrames || (shield.reflectFrames === 0 && 1 / shield.reflectFrames !== 1 / sourceShield.reflectFrames)) return false;
  if (shield.perfectFrames !== sourceShield.perfectFrames || (shield.perfectFrames === 0 && 1 / shield.perfectFrames !== 1 / sourceShield.perfectFrames)) return false;
  if (shield.perfectActionFrames !== sourceShield.perfectActionFrames || (shield.perfectActionFrames === 0 && 1 / shield.perfectActionFrames !== 1 / sourceShield.perfectActionFrames)) return false;
  if (shield.redParryTried !== sourceShield.redParryTried) return false;
  if (shield.parryBuffer !== sourceShield.parryBuffer || (shield.parryBuffer === 0 && 1 / shield.parryBuffer !== 1 / sourceShield.parryBuffer)) return false;
  if (shield.parryBufferDirection !== sourceShield.parryBufferDirection || (shield.parryBufferDirection === 0 && 1 / shield.parryBufferDirection !== 1 / sourceShield.parryBufferDirection)) return false;
  if (shield.breakState !== sourceShield.breakState || (shield.breakState === 0 && 1 / shield.breakState !== 1 / sourceShield.breakState)) return false;
  if (shield.breakFrame !== sourceShield.breakFrame || (shield.breakFrame === 0 && 1 / shield.breakFrame !== 1 / sourceShield.breakFrame)) return false;
  if (shield.breakSerial !== sourceShield.breakSerial || (shield.breakSerial === 0 && 1 / shield.breakSerial !== 1 / sourceShield.breakSerial)) return false;
  if (shield.breakRemaining !== sourceShield.breakRemaining || (shield.breakRemaining === 0 && 1 / shield.breakRemaining !== 1 / sourceShield.breakRemaining)) return false;

  const attack = target.attack;
  const sourceAttack = source.attack;
  if (attack.style !== sourceAttack.style || (attack.style === 0 && sourceAttack.style === 0 && 1 / attack.style !== 1 / sourceAttack.style)) return false;
  if (attack.frame !== sourceAttack.frame || (attack.frame === 0 && 1 / attack.frame !== 1 / sourceAttack.frame)) return false;
  if (attack.duration !== sourceAttack.duration || (attack.duration === 0 && 1 / attack.duration !== 1 / sourceAttack.duration)) return false;
  if (attack.serial !== sourceAttack.serial || (attack.serial === 0 && 1 / attack.serial !== 1 / sourceAttack.serial)) return false;
  if (attack.hit !== sourceAttack.hit) return false;
  if (attack.dashGrab !== sourceAttack.dashGrab) return false;
  if (attack.pivotGrab !== sourceAttack.pivotGrab) return false;
  if (attack.cooldown !== sourceAttack.cooldown || (attack.cooldown === 0 && 1 / attack.cooldown !== 1 / sourceAttack.cooldown)) return false;
  if (attack.smashCharging !== sourceAttack.smashCharging) return false;
  if (attack.smashChargeFrames !== sourceAttack.smashChargeFrames || (attack.smashChargeFrames === 0 && 1 / attack.smashChargeFrames !== 1 / sourceAttack.smashChargeFrames)) return false;
  if (attack.smashChargeAllowed !== sourceAttack.smashChargeAllowed) return false;

  const hits = target.hits;
  const sourceHits = source.hits;
  let hit = 0;
  for (const to of hits.entries) {
    const from = sourceHits.entries[hit++];
    if (from === undefined) return false;
    if (to.attacker !== from.attacker) return false;
    if (to.attackSerial !== from.attackSerial || (to.attackSerial === 0 && 1 / to.attackSerial !== 1 / from.attackSerial)) return false;
    if (to.window !== from.window || (to.window === 0 && 1 / to.window !== 1 / from.window)) return false;
  }
  if (hits.lastAttacker !== sourceHits.lastAttacker) return false;
  if (hits.lastAttackSerial !== sourceHits.lastAttackSerial || (hits.lastAttackSerial === 0 && sourceHits.lastAttackSerial === 0 && 1 / hits.lastAttackSerial !== 1 / sourceHits.lastAttackSerial)) return false;
  if (hits.lastWindow !== sourceHits.lastWindow || (hits.lastWindow === 0 && 1 / hits.lastWindow !== 1 / sourceHits.lastWindow)) return false;

  const visuals = target.visuals;
  const sourceVisuals = source.visuals;
  if (visuals.grab !== sourceVisuals.grab || (visuals.grab === 0 && 1 / visuals.grab !== 1 / sourceVisuals.grab)) return false;
  if (visuals.throw !== sourceVisuals.throw || (visuals.throw === 0 && 1 / visuals.throw !== 1 / sourceVisuals.throw)) return false;
  if (visuals.hit !== sourceVisuals.hit || (visuals.hit === 0 && 1 / visuals.hit !== 1 / sourceVisuals.hit)) return false;
  if (visuals.hitElectric !== sourceVisuals.hitElectric) return false;
  if (visuals.hitElement !== sourceVisuals.hitElement || (visuals.hitElement === 0 && 1 / visuals.hitElement !== 1 / sourceVisuals.hitElement)) return false;
  if (visuals.hitStrength !== sourceVisuals.hitStrength || (visuals.hitStrength === 0 && 1 / visuals.hitStrength !== 1 / sourceVisuals.hitStrength)) return false;
  if (visuals.hitHeight !== sourceVisuals.hitHeight || (visuals.hitHeight === 0 && 1 / visuals.hitHeight !== 1 / sourceVisuals.hitHeight)) return false;
  if (visuals.hitPummel !== sourceVisuals.hitPummel) return false;
  if (visuals.shieldElectric !== sourceVisuals.shieldElectric) return false;
  if (visuals.shield !== sourceVisuals.shield || (visuals.shield === 0 && 1 / visuals.shield !== 1 / sourceVisuals.shield)) return false;
  if (visuals.shieldReflect !== sourceVisuals.shieldReflect || (visuals.shieldReflect === 0 && 1 / visuals.shieldReflect !== 1 / sourceVisuals.shieldReflect)) return false;
  if (visuals.manaDrained !== sourceVisuals.manaDrained || (visuals.manaDrained === 0 && 1 / visuals.manaDrained !== 1 / sourceVisuals.manaDrained)) return false;
  if (visuals.manaDenied !== sourceVisuals.manaDenied || (visuals.manaDenied === 0 && 1 / visuals.manaDenied !== 1 / sourceVisuals.manaDenied)) return false;

  const special = target.special;
  const sourceSpecial = source.special;
  if (special.action !== sourceSpecial.action || (special.action === 0 && 1 / special.action !== 1 / sourceSpecial.action)) return false;
  if (special.ex !== sourceSpecial.ex) return false;
  if (special.exArmorUsed !== sourceSpecial.exArmorUsed) return false;
  if (special.frame !== sourceSpecial.frame || (special.frame === 0 && 1 / special.frame !== 1 / sourceSpecial.frame)) return false;
  if (special.duration !== sourceSpecial.duration || (special.duration === 0 && 1 / special.duration !== 1 / sourceSpecial.duration)) return false;
  if (special.lockFrames !== sourceSpecial.lockFrames || (special.lockFrames === 0 && 1 / special.lockFrames !== 1 / sourceSpecial.lockFrames)) return false;
  if (special.fall !== sourceSpecial.fall) return false;
  const cooldowns = special.cooldowns;
  const sourceCooldowns = sourceSpecial.cooldowns;
  for (let i = 0; i < cooldowns.length; i++) {
    const cooldown = cooldowns[i] ?? 0;
    const other = sourceCooldowns[i] ?? 0;
    if (cooldown !== other || (cooldown === 0 && 1 / cooldown !== 1 / other)) return false;
  }
  if (special.direction !== sourceSpecial.direction || (special.direction === 0 && 1 / special.direction !== 1 / sourceSpecial.direction)) return false;
  if (special.hit !== sourceSpecial.hit) return false;
  for (let i = 0; i < PARTICIPANT_CAPACITY; i++) if (special.hitTargets[i] !== sourceSpecial.hitTargets[i]) return false;
  if (special.form !== sourceSpecial.form || (special.form === 0 && 1 / special.form !== 1 / sourceSpecial.form)) return false;
  if (special.aimX !== sourceSpecial.aimX || (special.aimX === 0 && 1 / special.aimX !== 1 / sourceSpecial.aimX)) return false;
  if (special.aimZ !== sourceSpecial.aimZ || (special.aimZ === 0 && 1 / special.aimZ !== 1 / sourceSpecial.aimZ)) return false;
  if (special.airtimeUses !== sourceSpecial.airtimeUses || (special.airtimeUses === 0 && 1 / special.airtimeUses !== 1 / sourceSpecial.airtimeUses)) return false;
  if (special.grabFrame !== sourceSpecial.grabFrame || (special.grabFrame === 0 && 1 / special.grabFrame !== 1 / sourceSpecial.grabFrame)) return false;
  if (special.guarded !== sourceSpecial.guarded) return false;

  if (target.projectiles.length !== source.projectiles.length) return false;
  for (let i = 0; i < target.projectiles.length; i++) {
    const mine = target.projectiles[i];
    const theirs = source.projectiles[i];
    if (mine !== theirs && (mine === undefined || theirs === undefined || !sameRecord(mine, theirs, 0))) return false;
  }

  const bear = target.bear;
  const sourceBear = source.bear;
  if (bear.exDamage !== sourceBear.exDamage) return false;
  if (bear.life !== sourceBear.life || (bear.life === 0 && 1 / bear.life !== 1 / sourceBear.life)) return false;
  if (bear.x !== sourceBear.x || (bear.x === 0 && 1 / bear.x !== 1 / sourceBear.x)) return false;
  if (bear.z !== sourceBear.z || (bear.z === 0 && 1 / bear.z !== 1 / sourceBear.z)) return false;
  if (bear.velocityX !== sourceBear.velocityX || (bear.velocityX === 0 && 1 / bear.velocityX !== 1 / sourceBear.velocityX)) return false;
  if (bear.velocityZ !== sourceBear.velocityZ || (bear.velocityZ === 0 && 1 / bear.velocityZ !== 1 / sourceBear.velocityZ)) return false;
  if (bear.swipeCooldown !== sourceBear.swipeCooldown || (bear.swipeCooldown === 0 && 1 / bear.swipeCooldown !== 1 / sourceBear.swipeCooldown)) return false;
  if (bear.hitSerial !== sourceBear.hitSerial || (bear.hitSerial === 0 && 1 / bear.hitSerial !== 1 / sourceBear.hitSerial)) return false;
  if (bear.surface !== sourceBear.surface || (bear.surface === 0 && sourceBear.surface === 0 && 1 / bear.surface !== 1 / sourceBear.surface)) return false;
  const trap = target.freezeTrap;
  const sourceTrap = source.freezeTrap;
  if (trap.exReach !== sourceTrap.exReach) return false;
  if (trap.life !== sourceTrap.life || (trap.life === 0 && 1 / trap.life !== 1 / sourceTrap.life)) return false;
  if (trap.arming !== sourceTrap.arming || (trap.arming === 0 && 1 / trap.arming !== 1 / sourceTrap.arming)) return false;
  if (trap.x !== sourceTrap.x || (trap.x === 0 && 1 / trap.x !== 1 / sourceTrap.x)) return false;
  if (trap.z !== sourceTrap.z || (trap.z === 0 && 1 / trap.z !== 1 / sourceTrap.z)) return false;
  if (trap.surface !== sourceTrap.surface || (trap.surface === 0 && sourceTrap.surface === 0 && 1 / trap.surface !== 1 / sourceTrap.surface)) return false;
  if (trap.serial !== sourceTrap.serial || (trap.serial === 0 && 1 / trap.serial !== 1 / sourceTrap.serial)) return false;
  if (trap.cooldown !== sourceTrap.cooldown || (trap.cooldown === 0 && 1 / trap.cooldown !== 1 / sourceTrap.cooldown)) return false;

  const dodge = target.dodge;
  const sourceDodge = source.dodge;
  if (dodge.airDodging !== sourceDodge.airDodging) return false;
  if (dodge.airFrame !== sourceDodge.airFrame || (dodge.airFrame === 0 && 1 / dodge.airFrame !== 1 / sourceDodge.airFrame)) return false;
  if (dodge.airUsed !== sourceDodge.airUsed) return false;
  if (dodge.airMotionFrames !== sourceDodge.airMotionFrames || (dodge.airMotionFrames === 0 && 1 / dodge.airMotionFrames !== 1 / sourceDodge.airMotionFrames)) return false;
  if (dodge.groundFrame !== sourceDodge.groundFrame || (dodge.groundFrame === 0 && 1 / dodge.groundFrame !== 1 / sourceDodge.groundFrame)) return false;
  if (dodge.groundDirection !== sourceDodge.groundDirection || (dodge.groundDirection === 0 && 1 / dodge.groundDirection !== 1 / sourceDodge.groundDirection)) return false;
  if (dodge.groundEntryFacing !== sourceDodge.groundEntryFacing || (dodge.groundEntryFacing === 0 && 1 / dodge.groundEntryFacing !== 1 / sourceDodge.groundEntryFacing)) return false;
  const landing = target.landing;
  const sourceLanding = source.landing;
  if (landing.lag !== sourceLanding.lag || (landing.lag === 0 && 1 / landing.lag !== 1 / sourceLanding.lag)) return false;
  const down = target.down;
  const sourceDown = source.down;
  if (down.state !== sourceDown.state || (down.state === 0 && 1 / down.state !== 1 / sourceDown.state)) return false;
  if (down.frame !== sourceDown.frame || (down.frame === 0 && 1 / down.frame !== 1 / sourceDown.frame)) return false;
  if (down.direction !== sourceDown.direction || (down.direction === 0 && 1 / down.direction !== 1 / sourceDown.direction)) return false;
  if (down.waitRemaining !== sourceDown.waitRemaining || (down.waitRemaining === 0 && 1 / down.waitRemaining !== 1 / sourceDown.waitRemaining)) return false;
  if (down.faceUp !== sourceDown.faceUp) return false;
  if (down.attackQueued !== sourceDown.attackQueued) return false;
  const tech = target.tech;
  const sourceTech = source.tech;
  if (tech.window !== sourceTech.window || (tech.window === 0 && 1 / tech.window !== 1 / sourceTech.window)) return false;
  if (tech.pressAge !== sourceTech.pressAge || (tech.pressAge === 0 && 1 / tech.pressAge !== 1 / sourceTech.pressAge)) return false;
  if (tech.previousPressAge !== sourceTech.previousPressAge || (tech.previousPressAge === 0 && 1 / tech.previousPressAge !== 1 / sourceTech.previousPressAge)) return false;
  if (tech.accumulatedPress !== sourceTech.accumulatedPress) return false;
  const recovery = target.surfaceRecovery;
  const sourceRecovery = source.surfaceRecovery;
  if (recovery.state !== sourceRecovery.state || (recovery.state === 0 && 1 / recovery.state !== 1 / sourceRecovery.state)) return false;
  if (recovery.frame !== sourceRecovery.frame || (recovery.frame === 0 && 1 / recovery.frame !== 1 / sourceRecovery.frame)) return false;
  if (recovery.velocityApplied !== sourceRecovery.velocityApplied) return false;
  if (recovery.wallJumpQueued !== sourceRecovery.wallJumpQueued) return false;
  if (recovery.wallJumpRepeat !== sourceRecovery.wallJumpRepeat || (recovery.wallJumpRepeat === 0 && 1 / recovery.wallJumpRepeat !== 1 / sourceRecovery.wallJumpRepeat)) return false;
  if (recovery.wallJumpAge !== sourceRecovery.wallJumpAge || (recovery.wallJumpAge === 0 && sourceRecovery.wallJumpAge === 0 && 1 / recovery.wallJumpAge !== 1 / sourceRecovery.wallJumpAge)) return false;
  if (recovery.wallJumpSide !== sourceRecovery.wallJumpSide || (recovery.wallJumpSide === 0 && 1 / recovery.wallJumpSide !== 1 / sourceRecovery.wallJumpSide)) return false;
  if (recovery.wallJumpsUsed !== sourceRecovery.wallJumpsUsed || (recovery.wallJumpsUsed === 0 && 1 / recovery.wallJumpsUsed !== 1 / sourceRecovery.wallJumpsUsed)) return false;
  if (recovery.reflectCooldown !== sourceRecovery.reflectCooldown || (recovery.reflectCooldown === 0 && 1 / recovery.reflectCooldown !== 1 / sourceRecovery.reflectCooldown)) return false;
  if (recovery.lastReflectedSurface !== sourceRecovery.lastReflectedSurface || (recovery.lastReflectedSurface === 0 && sourceRecovery.lastReflectedSurface === 0 && 1 / recovery.lastReflectedSurface !== 1 / sourceRecovery.lastReflectedSurface)) return false;
  if (recovery.contactSerial !== sourceRecovery.contactSerial || (recovery.contactSerial === 0 && 1 / recovery.contactSerial !== 1 / sourceRecovery.contactSerial)) return false;
  if (recovery.contactKind !== sourceRecovery.contactKind || (recovery.contactKind === 0 && 1 / recovery.contactKind !== 1 / sourceRecovery.contactKind)) return false;
  if (recovery.contactApproachSpeed !== sourceRecovery.contactApproachSpeed || (recovery.contactApproachSpeed === 0 && 1 / recovery.contactApproachSpeed !== 1 / sourceRecovery.contactApproachSpeed)) return false;
  if (recovery.contactX !== sourceRecovery.contactX || (recovery.contactX === 0 && 1 / recovery.contactX !== 1 / sourceRecovery.contactX)) return false;
  if (recovery.contactZ !== sourceRecovery.contactZ || (recovery.contactZ === 0 && 1 / recovery.contactZ !== 1 / sourceRecovery.contactZ)) return false;
  if (recovery.contactNormalX !== sourceRecovery.contactNormalX || (recovery.contactNormalX === 0 && 1 / recovery.contactNormalX !== 1 / sourceRecovery.contactNormalX)) return false;
  if (recovery.contactNormalZ !== sourceRecovery.contactNormalZ || (recovery.contactNormalZ === 0 && 1 / recovery.contactNormalZ !== 1 / sourceRecovery.contactNormalZ)) return false;
  const grab = target.grab;
  const sourceGrab = source.grab;
  if (grab.grabbedFrames !== sourceGrab.grabbedFrames || (grab.grabbedFrames === 0 && 1 / grab.grabbedFrames !== 1 / sourceGrab.grabbedFrames)) return false;
  if (grab.action !== sourceGrab.action || (grab.action === 0 && 1 / grab.action !== 1 / sourceGrab.action)) return false;
  if (grab.frame !== sourceGrab.frame || (grab.frame === 0 && 1 / grab.frame !== 1 / sourceGrab.frame)) return false;
  if (grab.serial !== sourceGrab.serial || (grab.serial === 0 && 1 / grab.serial !== 1 / sourceGrab.serial)) return false;
  if (grab.pummels !== sourceGrab.pummels || (grab.pummels === 0 && 1 / grab.pummels !== 1 / sourceGrab.pummels)) return false;
  if (grab.heldFrames !== sourceGrab.heldFrames || (grab.heldFrames === 0 && 1 / grab.heldFrames !== 1 / sourceGrab.heldFrames)) return false;
  if (grab.queuedThrow !== sourceGrab.queuedThrow || (grab.queuedThrow === 0 && 1 / grab.queuedThrow !== 1 / sourceGrab.queuedThrow)) return false;
  if (grab.mashX !== sourceGrab.mashX || (grab.mashX === 0 && 1 / grab.mashX !== 1 / sourceGrab.mashX)) return false;
  if (grab.mashZ !== sourceGrab.mashZ || (grab.mashZ === 0 && 1 / grab.mashZ !== 1 / sourceGrab.mashZ)) return false;
  if (grab.owner !== sourceGrab.owner) return false;
  if (grab.target !== sourceGrab.target) return false;
  const ledge = target.ledge;
  const sourceLedge = source.ledge;
  if (ledge.state !== sourceLedge.state || (ledge.state === 0 && 1 / ledge.state !== 1 / sourceLedge.state)) return false;
  if (ledge.side !== sourceLedge.side || (ledge.side === 0 && 1 / ledge.side !== 1 / sourceLedge.side)) return false;
  if (ledge.frame !== sourceLedge.frame || (ledge.frame === 0 && 1 / ledge.frame !== 1 / sourceLedge.frame)) return false;
  if (ledge.serial !== sourceLedge.serial || (ledge.serial === 0 && 1 / ledge.serial !== 1 / sourceLedge.serial)) return false;
  if (ledge.intangible !== sourceLedge.intangible || (ledge.intangible === 0 && 1 / ledge.intangible !== 1 / sourceLedge.intangible)) return false;
  if (ledge.regrab !== sourceLedge.regrab || (ledge.regrab === 0 && 1 / ledge.regrab !== 1 / sourceLedge.regrab)) return false;
  if (ledge.grabs !== sourceLedge.grabs || (ledge.grabs === 0 && 1 / ledge.grabs !== 1 / sourceLedge.grabs)) return false;
  const platform = target.platform;
  const sourcePlatform = source.platform;
  if (platform.move !== sourcePlatform.move || (platform.move === 0 && 1 / platform.move !== 1 / sourcePlatform.move)) return false;
  if (platform.frame !== sourcePlatform.frame || (platform.frame === 0 && 1 / platform.frame !== 1 / sourcePlatform.frame)) return false;
  if (platform.duration !== sourcePlatform.duration || (platform.duration === 0 && 1 / platform.duration !== 1 / sourcePlatform.duration)) return false;
  if (platform.deck !== sourcePlatform.deck || (platform.deck === 0 && sourcePlatform.deck === 0 && 1 / platform.deck !== 1 / sourcePlatform.deck)) return false;
  if (platform.fromX !== sourcePlatform.fromX || (platform.fromX === 0 && 1 / platform.fromX !== 1 / sourcePlatform.fromX)) return false;
  if (platform.toX !== sourcePlatform.toX || (platform.toX === 0 && 1 / platform.toX !== 1 / sourcePlatform.toX)) return false;
  if (platform.fromZ !== sourcePlatform.fromZ || (platform.fromZ === 0 && 1 / platform.fromZ !== 1 / sourcePlatform.fromZ)) return false;
  if (platform.toZ !== sourcePlatform.toZ || (platform.toZ === 0 && 1 / platform.toZ !== 1 / sourcePlatform.toZ)) return false;
  if (platform.rise !== sourcePlatform.rise || (platform.rise === 0 && 1 / platform.rise !== 1 / sourcePlatform.rise)) return false;
  if (platform.stand !== sourcePlatform.stand) return false;
  if (platform.shield !== sourcePlatform.shield) return false;
  if (platform.upFrames !== sourcePlatform.upFrames) return false;
  if (platform.landedFrames !== sourcePlatform.landedFrames) return false;
  if (platform.dodgeQueued !== sourcePlatform.dodgeQueued) return false;
  if (platform.dodgeX !== sourcePlatform.dodgeX || (platform.dodgeX === 0 && 1 / platform.dodgeX !== 1 / sourcePlatform.dodgeX)) return false;
  if (platform.dodgeZ !== sourcePlatform.dodgeZ || (platform.dodgeZ === 0 && 1 / platform.dodgeZ !== 1 / sourcePlatform.dodgeZ)) return false;
  if (platform.specialQueued !== sourcePlatform.specialQueued) return false;
  if (platform.specialX !== sourcePlatform.specialX || (platform.specialX === 0 && 1 / platform.specialX !== 1 / sourcePlatform.specialX)) return false;
  if (platform.specialZ !== sourcePlatform.specialZ || (platform.specialZ === 0 && 1 / platform.specialZ !== 1 / sourcePlatform.specialZ)) return false;
  const cannon = target.cannon;
  const sourceCannon = source.cannon;
  if (cannon.held !== sourceCannon.held || (cannon.held === 0 && sourceCannon.held === 0 && 1 / cannon.held !== 1 / sourceCannon.held)) return false;
  if (cannon.firing !== sourceCannon.firing || (cannon.firing === 0 && sourceCannon.firing === 0 && 1 / cannon.firing !== 1 / sourceCannon.firing)) return false;
  if (cannon.cooldown !== sourceCannon.cooldown || (cannon.cooldown === 0 && 1 / cannon.cooldown !== 1 / sourceCannon.cooldown)) return false;
  if (cannon.passing !== sourceCannon.passing) return false;
  const water = target.water;
  const sourceWater = source.water;
  if (water.inWater !== sourceWater.inWater) return false;
  if (water.frames !== sourceWater.frames || (water.frames === 0 && 1 / water.frames !== 1 / sourceWater.frames)) return false;
  if (water.entries !== sourceWater.entries || (water.entries === 0 && 1 / water.entries !== 1 / sourceWater.entries)) return false;
  if (water.hydraFrame !== sourceWater.hydraFrame || (water.hydraFrame === 0 && 1 / water.hydraFrame !== 1 / sourceWater.hydraFrame)) return false;
  if (water.hydraX !== sourceWater.hydraX || (water.hydraX === 0 && 1 / water.hydraX !== 1 / sourceWater.hydraX)) return false;
  if (water.hydraStrikeFrame !== sourceWater.hydraStrikeFrame) return false;
  const status = target.status;
  const sourceStatus = source.status;
  if (status.damage !== sourceStatus.damage || (status.damage === 0 && 1 / status.damage !== 1 / sourceStatus.damage)) return false;
  if (status.offscreenFrames !== sourceStatus.offscreenFrames || (status.offscreenFrames === 0 && 1 / status.offscreenFrames !== 1 / sourceStatus.offscreenFrames)) return false;
  if (status.stocks !== sourceStatus.stocks || (status.stocks === 0 && 1 / status.stocks !== 1 / sourceStatus.stocks)) return false;
  if (status.respawn !== sourceStatus.respawn || (status.respawn === 0 && 1 / status.respawn !== 1 / sourceStatus.respawn)) return false;
  if (status.out !== sourceStatus.out) return false;
  if (status.invincible !== sourceStatus.invincible || (status.invincible === 0 && 1 / status.invincible !== 1 / sourceStatus.invincible)) return false;
  if (status.frozenFrames !== sourceStatus.frozenFrames || (status.frozenFrames === 0 && 1 / status.frozenFrames !== 1 / sourceStatus.frozenFrames)) return false;
  if (status.freezeImmunityFrames !== sourceStatus.freezeImmunityFrames || (status.freezeImmunityFrames === 0 && 1 / status.freezeImmunityFrames !== 1 / sourceStatus.freezeImmunityFrames)) return false;
  if (status.armorFrames !== sourceStatus.armorFrames || (status.armorFrames === 0 && 1 / status.armorFrames !== 1 / sourceStatus.armorFrames)) return false;
  if (status.armorMaxDamage !== sourceStatus.armorMaxDamage || (status.armorMaxDamage === 0 && 1 / status.armorMaxDamage !== 1 / sourceStatus.armorMaxDamage)) return false;
  if (status.armorChills !== sourceStatus.armorChills) return false;
  if (status.condition !== sourceStatus.condition || (status.condition === 0 && 1 / status.condition !== 1 / sourceStatus.condition)) return false;
  if (status.conditionFrames !== sourceStatus.conditionFrames || (status.conditionFrames === 0 && 1 / status.conditionFrames !== 1 / sourceStatus.conditionFrames)) return false;
  if (status.conditionGroup !== sourceStatus.conditionGroup || (status.conditionGroup === 0 && 1 / status.conditionGroup !== 1 / sourceStatus.conditionGroup)) return false;
  if (status.conditionImmunityFrames !== sourceStatus.conditionImmunityFrames || (status.conditionImmunityFrames === 0 && 1 / status.conditionImmunityFrames !== 1 / sourceStatus.conditionImmunityFrames)) return false;
  for (let i = 0; i < HERO_STATUS_GROUPS; i++) if ((status.conditionImmunity[i] ?? 0) !== (sourceStatus.conditionImmunity[i] ?? 0)) return false;
  if (status.poisonFrames !== sourceStatus.poisonFrames || (status.poisonFrames === 0 && 1 / status.poisonFrames !== 1 / sourceStatus.poisonFrames)) return false;
  if (status.poisonEvery !== sourceStatus.poisonEvery || (status.poisonEvery === 0 && 1 / status.poisonEvery !== 1 / sourceStatus.poisonEvery)) return false;
  if (status.poisonDamage !== sourceStatus.poisonDamage || (status.poisonDamage === 0 && 1 / status.poisonDamage !== 1 / sourceStatus.poisonDamage)) return false;
  if (status.divineFrames !== sourceStatus.divineFrames || (status.divineFrames === 0 && 1 / status.divineFrames !== 1 / sourceStatus.divineFrames)) return false;
  if (status.buff !== sourceStatus.buff || (status.buff === 0 && 1 / status.buff !== 1 / sourceStatus.buff)) return false;
  if (status.buffFrames !== sourceStatus.buffFrames || (status.buffFrames === 0 && 1 / status.buffFrames !== 1 / sourceStatus.buffFrames)) return false;

  const mana = target.mana;
  const sourceMana = source.mana;
  if (mana.points !== sourceMana.points || (mana.points === 0 && 1 / mana.points !== 1 / sourceMana.points)) return false;


  if (target.pack.length !== source.pack.length || (target.pack.length === 0 && 1 / target.pack.length !== 1 / source.pack.length)) return false;
  for (let animal = 0; animal <= source.pack.length; animal++) {
    const placed = placedObject(target, animal);
    const sourcePlaced = placedObject(source, animal);
    if (placed.life !== sourcePlaced.life || (placed.life === 0 && 1 / placed.life !== 1 / sourcePlaced.life)) return false;
    if (placed.age !== sourcePlaced.age || (placed.age === 0 && 1 / placed.age !== 1 / sourcePlaced.age)) return false;
    if (placed.x !== sourcePlaced.x || (placed.x === 0 && 1 / placed.x !== 1 / sourcePlaced.x)) return false;
    if (placed.z !== sourcePlaced.z || (placed.z === 0 && 1 / placed.z !== 1 / sourcePlaced.z)) return false;
    if (placed.direction !== sourcePlaced.direction || (placed.direction === 0 && 1 / placed.direction !== 1 / sourcePlaced.direction)) return false;
    if (placed.durability !== sourcePlaced.durability || (placed.durability === 0 && 1 / placed.durability !== 1 / sourcePlaced.durability)) return false;
    if (placed.serial !== sourcePlaced.serial || (placed.serial === 0 && 1 / placed.serial !== 1 / sourcePlaced.serial)) return false;
    if (placed.spec !== sourcePlaced.spec) return false;
    for (let slot = 0; slot < PARTICIPANT_CAPACITY; slot++) if (placed.struck[slot] !== sourcePlaced.struck[slot]) return false;
    if (placed.specialStruck !== sourcePlaced.specialStruck || (placed.specialStruck === 0 && 1 / placed.specialStruck !== 1 / sourcePlaced.specialStruck)) return false;
    if (placed.mode !== sourcePlaced.mode || (placed.mode === 0 && 1 / placed.mode !== 1 / sourcePlaced.mode)) return false;
    if (placed.modeFrame !== sourcePlaced.modeFrame || (placed.modeFrame === 0 && 1 / placed.modeFrame !== 1 / sourcePlaced.modeFrame)) return false;
    if (placed.apart !== sourcePlaced.apart || (placed.apart === 0 && 1 / placed.apart !== 1 / sourcePlaced.apart)) return false;
    if (placed.bitten !== sourcePlaced.bitten || (placed.bitten === 0 && 1 / placed.bitten !== 1 / sourcePlaced.bitten)) return false;
    if (placed.surface !== sourcePlaced.surface || (placed.surface === 0 && sourcePlaced.surface === 0 && 1 / placed.surface !== 1 / sourcePlaced.surface)) return false;
  }
  return true;
}
