// Original authored sky models; generation is the foreign MDX file boundary.
import { join } from "node:path";
import { parseMDL, generateMDX } from "../animations/node_modules/war3-model";
import { STAGE_SKIES, stageSkyMdl, stageSkyModelFile, stageSkyTexture } from "../../ts/scripts/stageSky";
export async function packageSkies(output: string): Promise<string[]> {
  const imports: string[] = [], models: string[] = [];
  for (const sky of STAGE_SKIES) {
    const texture = stageSkyTexture(sky), mdl = stageSkyMdl(texture.name), name = stageSkyModelFile(mdl);
    await Bun.write(join(output, texture.name), texture.bytes);
    await Bun.write(join(output, name), new Uint8Array(generateMDX(parseMDL(mdl))));
    await Bun.write(join(output, `StageSky${sky.theme}.mdl`), mdl);
    imports.push(name, texture.name);
    models.push(`  ${sky.stage}: ${JSON.stringify(`war3mapImported\\${name}`)},`);
  }
  await Bun.write(join(import.meta.dir, "../../ts/src/game/assets/stageSkyInfo.ts"), `// Generated by tools/stage/package.ts; regenerate instead of editing.\n/** Original atmospheric skies; Nordrassil retains its stock aurora. */\nexport const STAGE_SKY_MODELS: Readonly<Record<number, string>> = {\n${models.join("\n")}\n};\n`);
  console.log(`Stage skies: ${STAGE_SKIES.length} original skies, 1024 triangles each, no particles or animation tracks`);
  return imports;
}
