import { afterAll, expect, test } from "bun:test";
import { installHeadless } from "wisp/scripts/wisp/headless";
import { SMASHCRAFT_HEADLESS } from "../scripts/wisp/headless";
import { PlacedObjectEffects } from "../src/game/render/placedObjectEffects";
import { Character } from "../src/game/sim/codes";
import { createFighter } from "../src/game/sim/fighter";
import { BEAR_PLACEMENT } from "../src/game/sim/heroes/beastmasterSpecials";
import { CompanionMode } from "../src/game/sim/heroSpecials";

const headless = installHeadless({ ...SMASHCRAFT_HEADLESS, localNatives: {} });
afterAll(headless.restore);

test("Bear command draws a large rear-up, four state labels, one roar and a bite-only impact", () => {
  const clients = headless.clients({ install() {}, start() {} });
  clients.start();
  const client = clients.clients[0];
  if (client === undefined) throw new Error("missing client");
  client.run(() => {
    const effects = new PlacedObjectEffects({ x: 0.0, y: 0.0, z: 0.0 });
    const fighter = createFighter(Character.beastmaster, 0.0, 1);
    const bear = fighter.placed;
    bear.spec = BEAR_PLACEMENT;
    bear.life = 600;
    bear.durability = 30.0;
    effects.present(fighter, 0);
    const body = () => client.effectPoses().find(pose => pose.model.includes("GrizzlyBear"));
    const followingScale = body()?.scale ?? 0.0;
    bear.mode = CompanionMode.lunge;
    bear.age = 100;
    bear.modeFrame = 1;
    effects.presentConfirmed(100, fighter, 0);
    effects.presentConfirmed(100, fighter, 0);
    effects.present(fighter, 0);
    expect(body()?.pitch).toBeLessThan(-0.8);
    expect(body()?.scale).toBeGreaterThan(followingScale * 1.2);
    expect(client.effectPoses().some(pose => pose.model.includes("RoarTarget") && pose.scale === 2.5 && pose.z > 0)).toBe(true);
    bear.modeFrame = 11;
    bear.age = 110;
    bear.bitten = 2;
    effects.presentConfirmed(110, fighter, 0);
    effects.present(fighter, 0);
    expect(body()?.animationElapsed).toBe(0.5);
    expect(client.effectPoses().some(pose => pose.model.includes("StampedeMissileDeath") && pose.scale === 1.5 && pose.z > 0)).toBe(true);
    bear.modeFrame = 15;
    bear.age = 114;
    effects.presentConfirmed(114, fighter, 0);
    effects.present(fighter, 0);
    const labels = client.log.filter(call => call.name === "SetTextTagText").map(call => call.args[1]);
    expect(labels).toEqual(["FOLLOWING", "CHARGING", "ATTACKING", "RESTING"]);
    const positions = client.log.filter(call => call.name === "SetTextTagPos");
    expect(positions.every(call => Number(call.args[3]) > bear.z + 100)).toBe(true);
    const sounds = client.log.filter(call => call.name === "CreateSoundFromLabel").map(call => call.args[0]);
    expect(sounds).toEqual(["BattleRoar", "MetalHeavySliceFlesh"]);
    bear.life = 0;
    effects.present(fighter, 0);
    expect(body()?.scale).toBe(0);
    expect(client.log.filter(call => call.name === "SetTextTagVisibility").at(-1)?.args[1]).toBe(false);
    effects.destroy();
  });
});
