import { afterAll, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Effect } from "effect";
import { setControllerLayout } from "../scripts/wisp/controllerLayout";
const scratch = mkdtempSync(join(tmpdir(), "smashcraft-layout-"));
afterAll(() => rmSync(scratch, { recursive: true, force: true }));
test("offline layout saves preserve tap jump and both trigger choices [spec docs/play.md] [invariant]", async () => {
  const server = createServer();
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const address = server.address();
  if (address === null || typeof address === "string") throw new Error("missing port");
  const port = address.port;
  await new Promise<void>((resolve) => server.close(() => resolve()));
  const file = join(scratch, "controller.json");
  const settings = { pad_preset: "melee", tap_jump: true, triggers: { left: "light", right: "full" } };
  writeFileSync(file, JSON.stringify(settings));
  expect(await Effect.runPromise(setControllerLayout("z-jump", file, port))).toBe("saved");
  expect(JSON.parse(readFileSync(file, "utf8"))).toEqual({ ...settings, pad_preset: "z-jump" });
  expect(await Effect.runPromise(setControllerLayout("tom", file, port))).toBe("saved");
  expect(JSON.parse(readFileSync(file, "utf8"))).toEqual({ ...settings, pad_preset: "tom" });
  expect(await Effect.runPromise(setControllerLayout("melee", file, port))).toBe("saved");
  expect(JSON.parse(readFileSync(file, "utf8"))).toEqual(settings);
});
