import { expect, test } from "bun:test";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Effect } from "effect";
import { makeRepro } from "wisp/scripts/wisp/commands/repro";
import { writtenPreloadFile } from "wisp/scripts/wisp/headlessInput";
import { reproLines } from "wisp/src/runtime/repro";
import { inspectRepro } from "../src/game/replay/moment";
import { savedInspectionFixture } from "../src/game/replay/moment.tests";
import { SMASHCRAFT_HEADLESS } from "../scripts/wisp/headless";

test("the repro command inspects a saved gameplay fixture and diffs its previous frame", async () => {
  const repro = savedInspectionFixture();
  const directory = join(import.meta.dir, "../build/repro-inspection");
  mkdirSync(directory, { recursive: true });
  const file = join(directory, "saved-game.txt");
  const out = join(directory, "state.json");
  const saved = writtenPreloadFile(reproLines(repro, repro.lines));
  writeFileSync(file, saved);
  await Effect.runPromise(makeRepro(async () => ({ map: SMASHCRAFT_HEADLESS, replay: join(import.meta.dir, "../src/game/replay/moment.ts"), tests: directory }))([file, "--frame", String(repro.frame), "--diff-frame", "previous", "--out", out]));
  const inspection = inspectRepro(repro, repro.frame);
  if (typeof inspection === "string") throw new Error(inspection);
  const output = JSON.parse(readFileSync(out, "utf8"));
  expect(output.state).toBe(inspection.state);
  expect(output.checksum).toBe(repro.checksum);
  expect(output.diff.from).toBe(repro.frame - 1);
  expect(output.diff.to).toBe(repro.frame);
  expect(output.diff.fields.length).toBeGreaterThan(0);
  expect(readFileSync(file, "utf8")).toBe(saved);
});
