// Generated by tools/animations/blademaster-clips.ts; regenerate instead of editing.
import { f32 } from "wisp/src/sim/f32";
import type { HeroClipTable } from "../sim/heroes/hero";
export const BLADEMASTER_AUTHORED_CLIPS = {
  jab: { index: 56, seconds: f32(0.283), aligned: true },
  jab2: { index: 57, seconds: f32(0.333), aligned: true },
  forwardTilt: { index: 58, seconds: f32(0.483), aligned: true },
  forwardTiltUp: { index: 59, seconds: f32(0.483), aligned: true },
  forwardTiltDown: { index: 60, seconds: f32(0.483), aligned: true },
  upTilt: { index: 61, seconds: f32(0.467), aligned: true },
  downTilt: { index: 62, seconds: f32(0.283), aligned: true },
  dashAttack: { index: 63, seconds: f32(0.567), aligned: true },
  forwardSmash: { index: 64, seconds: f32(0.85) },
  upSmash: { index: 65, seconds: f32(0.8) },
  downSmash: { index: 66, seconds: f32(0.833) },
  neutralAir: { index: 67, seconds: f32(0.533) },
  forwardAir: { index: 68, seconds: f32(0.567) },
  backAir: { index: 69, seconds: f32(0.55) },
  upAir: { index: 70, seconds: f32(0.45) },
  throwBack: { index: 71, seconds: f32(0.617) },
} as const satisfies HeroClipTable;

export const BLADEMASTER_AUTHORED_CLIP_NAMES = {
  jab: "Sword Gesture Jab Quick Cut",
  jab2: "Sword Gesture Jab Returning Cut",
  forwardTilt: "Sword Gesture Tilt Level Cut",
  forwardTiltUp: "Sword Gesture Tilt Rising Cut",
  forwardTiltDown: "Sword Gesture Tilt Falling Cut",
  upTilt: "Sword Gesture Tilt Overhead Arc",
  downTilt: "Sword Gesture Tilt Low Poke",
  dashAttack: "Sword Gesture Dash Lunging Cut",
  forwardSmash: "Sword Gesture Smash Shoulder Cleave",
  upSmash: "Sword Gesture Smash Sky Splitter",
  downSmash: "Sword Gesture Smash Front Rear Sweep",
  neutralAir: "Sword Gesture Air Crescent Slash",
  forwardAir: "Sword Gesture Air Forward Cleave",
  backAir: "Sword Gesture Air Turning Back Cut",
  upAir: "Sword Gesture Air Upward Pierce",
  throwBack: "Sword Gesture Throw Back Heave",
} as const;
