// Generated by `bun wisp view models` from the stock _de MDX emitter chunks.
export const DEFINITIVE_CUE_EMITTERS: { readonly [model: string]: boolean | undefined } = {
  "Abilities\\Spells\\Human\\Polymorph\\PolyMorphDoneGround.mdx": true,
  "Abilities\\Spells\\Items\\AIfb\\AIfbSpecialArt.mdx": true,
  "Abilities\\Spells\\Items\\VampiricPotion\\VampPotionCaster.mdx": false,
  "Abilities\\Spells\\Other\\BreathOfFire\\BreathOfFireMissile.mdx": true,
  "Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedTarget.mdx": true,
  "Abilities\\Spells\\Undead\\DarkRitual\\DarkRitualCaster.mdx": true,
  "Abilities\\Spells\\Undead\\DeathAndDecay\\DeathAndDecayTarget.mdx": true,
  "Abilities\\Weapons\\RedDragonBreath\\RedDragonMissile.mdx": true,
  "Objects\\Spawnmodels\\Undead\\UCancelDeath\\UCancelDeath.mdx": true,
};
