// Generated by `bun wisp view models` from the stock _de MDX emitter chunks.
export const DEFINITIVE_CUE_EMITTERS: { readonly [model: string]: boolean | undefined } = {
  "Abilities\\Spells\\Undead\\DarkRitual\\DarkRitualCaster.mdx": true,
  "Abilities\\Spells\\Undead\\DeathAndDecay\\DeathAndDecayTarget.mdx": true,
};
