// Generated by `bun wisp view motion --assets DIR`; regenerate instead of editing.
import { f32 } from "wisp/src/sim/f32";
/** Drawn foot travel in world units per second at 1x clip speed (#171). */
export const DRAWN_STRIDES: { readonly [character: number]: { readonly walk: { readonly clip: number; readonly model: string; readonly speed: number }; readonly run: { readonly clip: number; readonly model: string; readonly speed: number } } | undefined } = {
  0: { walk: { clip: 57, model: "war3mapImported\\ArcherFighter-350ce721514fbb3ad917c2ddacf0515ee416b55efa419d330c3c24caeeb5f4c9.mdx", speed: f32(134.829) }, run: { clip: 57, model: "war3mapImported\\ArcherFighter-350ce721514fbb3ad917c2ddacf0515ee416b55efa419d330c3c24caeeb5f4c9.mdx", speed: f32(134.829) } },
  1: { walk: { clip: 54, model: "war3mapImported\\RiflemanFighter-5eedc4053cb270e1875eedd9c11e13f8856f50d7c56a795af40a7f7ba7274817.mdx", speed: f32(149.997) }, run: { clip: 54, model: "war3mapImported\\RiflemanFighter-5eedc4053cb270e1875eedd9c11e13f8856f50d7c56a795af40a7f7ba7274817.mdx", speed: f32(149.997) } },
  2: { walk: { clip: 109, model: "war3mapImported\\DemonHunterFighter-fc19988055002962f7df7949dd5923783b3a289d47b17f96cabfcf99672092a7.mdx", speed: f32(143.651) }, run: { clip: 64, model: "war3mapImported\\DemonHunterFighter-fc19988055002962f7df7949dd5923783b3a289d47b17f96cabfcf99672092a7.mdx", speed: f32(278.357) } },
  3: { walk: { clip: 6, model: "units\\orc\\HeroBladeMaster\\HeroBladeMaster.mdl", speed: f32(209.537) }, run: { clip: 6, model: "units\\orc\\HeroBladeMaster\\HeroBladeMaster.mdl", speed: f32(209.537) } },
  4: { walk: { clip: 7, model: "units\\human\\HeroMountainKing\\HeroMountainKing.mdl", speed: f32(146.888) }, run: { clip: 7, model: "units\\human\\HeroMountainKing\\HeroMountainKing.mdl", speed: f32(146.888) } },
  5: { walk: { clip: 2, model: "Units\\NightElf\\HeroWarden\\HeroWarden.mdx", speed: f32(91.814) }, run: { clip: 2, model: "Units\\NightElf\\HeroWarden\\HeroWarden.mdx", speed: f32(91.814) } },
  6: { walk: { clip: 4, model: "units\\undead\\HeroLich\\HeroLich.mdl", speed: f32(250.000) }, run: { clip: 4, model: "units\\undead\\HeroLich\\HeroLich.mdl", speed: f32(250.000) } },
  7: { walk: { clip: 12, model: "units\\human\\HeroPaladin\\HeroPaladin.mdl", speed: f32(213.618) }, run: { clip: 12, model: "units\\human\\HeroPaladin\\HeroPaladin.mdl", speed: f32(213.618) } },
  8: { walk: { clip: 5, model: "units\\undead\\HeroDreadLord\\HeroDreadLord.mdl", speed: f32(153.999) }, run: { clip: 5, model: "units\\undead\\HeroDreadLord\\HeroDreadLord.mdl", speed: f32(153.999) } },
  9: { walk: { clip: 0, model: "units\\orc\\HeroShadowHunter\\HeroShadowHunter.mdl", speed: f32(303.549) }, run: { clip: 0, model: "units\\orc\\HeroShadowHunter\\HeroShadowHunter.mdl", speed: f32(303.549) } },
  10: { walk: { clip: 1, model: "units\\demon\\HeroPitLord\\HeroPitLord.mdl", speed: f32(136.792) }, run: { clip: 3, model: "units\\demon\\HeroPitLord\\HeroPitLord.mdl", speed: f32(540.598) } },
  11: { walk: { clip: 0, model: "units\\creeps\\BeastMaster\\BeastMaster.mdl", speed: f32(203.181) }, run: { clip: 0, model: "units\\creeps\\BeastMaster\\BeastMaster.mdl", speed: f32(203.181) } },
  12: { walk: { clip: 2, model: "war3mapImported\\LichKing2.mdx", speed: f32(129.361) }, run: { clip: 10, model: "war3mapImported\\LichKing2.mdx", speed: f32(265.067) } },
  13: { walk: { clip: 2, model: "units\\orc\\Thrall\\Thrall.mdl", speed: f32(213.345) }, run: { clip: 2, model: "units\\orc\\Thrall\\Thrall.mdl", speed: f32(213.345) } },
  19: { walk: { clip: 0, model: "units\\creeps\\HeroTinker\\HeroTinker.mdl", speed: f32(142.838) }, run: { clip: 0, model: "units\\creeps\\HeroTinker\\HeroTinker.mdl", speed: f32(142.838) } },
};
