// Generated by tools/animations/drill-clips.ts; regenerate instead of editing.
import { f32 } from "wisp/src/sim/f32";
import type { HeroClipTable } from "../sim/heroes/hero";
export const DRILL_CLIPS = {
  3: { downAir: { index: 40, seconds: f32(0.767), aligned: true } },
  5: { downAir: { index: 38, seconds: f32(0.45), aligned: true } },
  9: { downAir: { index: 40, seconds: f32(0.617), aligned: true } },
} as const satisfies Readonly<Record<number, HeroClipTable>>;
