// Generated by `bun scripts/fighterViewBounds.ts` from each look's drawn Stand body in model units (the camera applies characterModelScale); regenerate after a body or model change.
import { Character } from "../sim/codes";

export interface ViewBounds {
  readonly left: number;
  readonly right: number;
  readonly bottom: number;
  readonly top: number;
}

export const FIGHTER_VIEW_BOUNDS: Readonly<Record<Character, { readonly classic: ViewBounds; readonly definitive: ViewBounds }>> = {
  [Character.rifleman]: { classic: { left: -46, right: 68, bottom: -6, top: 127 }, definitive: { left: -46, right: 68, bottom: -6, top: 127 } },
  [Character.demonHunter]: { classic: { left: -124, right: 57, bottom: -7, top: 181 }, definitive: { left: -124, right: 57, bottom: -7, top: 181 } },
  [Character.blademaster]: { classic: { left: -128, right: 130, bottom: -3, top: 263 }, definitive: { left: -97, right: 139, bottom: -1, top: 210 } },
  [Character.mountainKing]: { classic: { left: -48, right: 92, bottom: -5, top: 170 }, definitive: { left: -40, right: 79, bottom: -1, top: 155 } },
  [Character.warden]: { classic: { left: -122, right: 88, bottom: -5, top: 164 }, definitive: { left: -96, right: 102, bottom: -5, top: 193 } },
  [Character.lich]: { classic: { left: -113, right: 64, bottom: -13, top: 181 }, definitive: { left: -122, right: 50, bottom: 27, top: 197 } },
  [Character.forsakenPaladin]: { classic: { left: -30, right: 87, bottom: -1, top: 111 }, definitive: { left: -30, right: 87, bottom: -1, top: 111 } },
  [Character.dreadlord]: { classic: { left: -132, right: 106, bottom: -15, top: 219 }, definitive: { left: -118, right: 71, bottom: -2, top: 222 } },
  [Character.shadowHunter]: { classic: { left: -143, right: 76, bottom: -6, top: 207 }, definitive: { left: -141, right: 100, bottom: -11, top: 175 } },
  [Character.pitLord]: { classic: { left: -164, right: 192, bottom: -8, top: 189 }, definitive: { left: -183, right: 272, bottom: -3, top: 267 } },
  [Character.beastmaster]: { classic: { left: -69, right: 102, bottom: -3, top: 167 }, definitive: { left: -45, right: 82, bottom: -1, top: 150 } },
  [Character.lichKing]: { classic: { left: -68, right: 143, bottom: -1, top: 211 }, definitive: { left: -68, right: 143, bottom: -1, top: 211 } },
  [Character.thrall]: { classic: { left: -109, right: 95, bottom: -3, top: 156 }, definitive: { left: -139, right: 122, bottom: -17, top: 168 } },
  [Character.jaina]: { classic: { left: -36, right: 30, bottom: -2, top: 119 }, definitive: { left: -43, right: 40, bottom: -1, top: 145 } },
  [Character.sylvanas]: { classic: { left: -72, right: 70, bottom: -1, top: 112 }, definitive: { left: -64, right: 37, bottom: -5, top: 115 } },
  [Character.cairne]: { classic: { left: -114, right: 110, bottom: -14, top: 257 }, definitive: { left: -110, right: 170, bottom: -32, top: 259 } },
  [Character.chen]: { classic: { left: -140, right: 86, bottom: 3, top: 172 }, definitive: { left: -87, right: 98, bottom: -3, top: 144 } },
  [Character.peon]: { classic: { left: -17, right: 50, bottom: -2, top: 88 }, definitive: { left: -42, right: 72, bottom: -1, top: 98 } },
  [Character.tinker]: { classic: { left: -59, right: 74, bottom: 0, top: 223 }, definitive: { left: -65, right: 48, bottom: -1, top: 187 } },
  [Character.kaelthas]: { classic: { left: -100, right: 58, bottom: -7, top: 140 }, definitive: { left: -109, right: 77, bottom: -8, top: 131 } },
  [Character.murloc]: { classic: { left: -39, right: 69, bottom: -13, top: 95 }, definitive: { left: -43, right: 67, bottom: -2, top: 88 } },
  [Character.grom]: { classic: { left: -133, right: 95, bottom: -4, top: 237 }, definitive: { left: -132, right: 99, bottom: 0, top: 197 } },
  [Character.anubarak]: { classic: { left: -135, right: 106, bottom: -4, top: 159 }, definitive: { left: -81, right: 122, bottom: 0, top: 153 } },
  [Character.malfurion]: { classic: { left: -68, right: 91, bottom: -1, top: 170 }, definitive: { left: -68, right: 91, bottom: -1, top: 170 } },
  [Character.medivh]: { classic: { left: -47, right: 25, bottom: -2, top: 144 }, definitive: { left: -58, right: 25, bottom: -15, top: 125 } },
  [Character.kobold]: { classic: { left: -54, right: 51, bottom: -6, top: 103 }, definitive: { left: -58, right: 59, bottom: -1, top: 134 } },
};
