
import { f32 } from "wisp/src/sim/f32";
import type { HeroClipTable } from "../sim/heroes/hero";
export const GRAB_CLIPS = {
  3: {
    grab: { index: 41, seconds: 1.0, aligned: true, },
    grabHold: { index: 42, seconds: 1.0, },
    grabbed: { index: 43, seconds: 1.0, },
    pummel: { index: 44, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 45, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 46, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 47, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 48, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 49, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 50, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 51, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 52, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 53, seconds: 1.0, contact: 0.5, },
  },
  4: {
    grab: { index: 53, seconds: 1.0, aligned: true, },
    grabHold: { index: 54, seconds: 1.0, },
    grabbed: { index: 55, seconds: 1.0, },
    pummel: { index: 56, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 57, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 58, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 59, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 60, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 61, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 62, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 63, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 64, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 65, seconds: 1.0, contact: 0.5, },
  },
  5: {
    grab: { index: 39, seconds: 1.0, aligned: true, },
    grabHold: { index: 40, seconds: 1.0, },
    grabbed: { index: 41, seconds: 1.0, },
    pummel: { index: 42, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 43, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 44, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 45, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 46, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 47, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 48, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 49, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 50, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 51, seconds: 1.0, contact: 0.5, },
  },
  6: {
    grab: { index: 36, seconds: 1.0, aligned: true, },
    grabHold: { index: 37, seconds: 1.0, },
    grabbed: { index: 38, seconds: 1.0, },
    pummel: { index: 39, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 40, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 41, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 42, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 43, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 44, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 45, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 46, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 47, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 48, seconds: 1.0, contact: 0.5, },
  },
  8: {
    grab: { index: 38, seconds: 1.0, aligned: true, },
    grabHold: { index: 39, seconds: 1.0, },
    grabbed: { index: 40, seconds: 1.0, },
    pummel: { index: 41, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 42, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 43, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 44, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 45, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 46, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 47, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 48, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 49, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 50, seconds: 1.0, contact: 0.5, },
  },
  9: {
    grab: { index: 41, seconds: 1.0, aligned: true, },
    grabHold: { index: 42, seconds: 1.0, },
    grabbed: { index: 43, seconds: 1.0, },
    pummel: { index: 44, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 45, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 46, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 47, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 48, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 49, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 50, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 51, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 52, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 53, seconds: 1.0, contact: 0.5, },
  },
  10: {
    grab: { index: 43, seconds: 1.0, aligned: true, },
    grabHold: { index: 44, seconds: 1.0, },
    grabbed: { index: 45, seconds: 1.0, },
    pummel: { index: 46, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 47, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 48, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 49, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 50, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 51, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 52, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 53, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 54, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 55, seconds: 1.0, contact: 0.5, },
  },
  11: {
    grab: { index: 36, seconds: 1.0, aligned: true, },
    grabHold: { index: 37, seconds: 1.0, },
    grabbed: { index: 38, seconds: 1.0, },
    pummel: { index: 39, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 40, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 41, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 42, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 43, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 44, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 45, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 46, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 47, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 48, seconds: 1.0, contact: 0.5, },
  },
  12: {
    grab: { index: 83, seconds: 1.0, aligned: true, },
    grabHold: { index: 84, seconds: 1.0, },
    grabbed: { index: 85, seconds: 1.0, },
    pummel: { index: 86, seconds: 1.0, contact: 0.5, },
    victimPummel: { index: 87, seconds: 1.0, contact: 0.5, },
    throwForward: { index: 88, seconds: 1.0, contact: 0.5, },
    victimThrowForward: { index: 89, seconds: 1.0, contact: 0.5, },
    throwBack: { index: 90, seconds: 1.0, contact: 0.5, },
    victimThrowBack: { index: 91, seconds: 1.0, contact: 0.5, },
    throwUp: { index: 92, seconds: 1.0, contact: 0.5, },
    victimThrowUp: { index: 93, seconds: 1.0, contact: 0.5, },
    throwDown: { index: 94, seconds: 1.0, contact: 0.5, },
    victimThrowDown: { index: 95, seconds: 1.0, contact: 0.5, },
  },
} as const satisfies Readonly<Record<number, HeroClipTable>>;
