import { assertEquals, assertFalse, assertNear, assertTrue, test } from "wisp/src/runtime/testing";
import { f32 } from "wisp/src/sim/f32";
import { createFrameControls } from "../match/controls";
import { createPacingAndPresentation } from "../match/pacingAndPresentation";
import { Phase, createMatchState } from "../match/rules";
import { captureReplaySnapshot, createReplaySnapshot, restoreReplaySnapshot } from "../replay/snapshot";
import { Character, ProjectileKind } from "../sim/codes";
import { PROJECTILE_CAPACITY, createFighter } from "../sim/fighter";
import { mutableProjectile } from "../sim/fighterProjectiles";
import { createRoster } from "../sim/roster";
import { projectedProjectile } from "./projectilePose";
import { LICH_KING_SPECIALS } from "../sim/heroes/lichKingSpecials";
import { heroProjectileRadius } from "../sim/projectiles";

test("Defile's rim follows its danger radius and distinguishes its warning from its armed pool across rollback [spec #174] [invariant]", () => {
  const fighter = createFighter(Character.lichKing, 0.0, 1);
  const projectile = mutableProjectile(fighter, 0);
  const spec = LICH_KING_SPECIALS.down.ground.projectiles?.[0];
  assertTrue(spec !== undefined);
  if (spec === undefined) return;
  projectile.kind = ProjectileKind.hero;
  projectile.spec = spec;
  projectile.life = spec.life;
  projectile.x = 79.0;
  projectile.z = 6.0;
  const warning = projectedProjectile(fighter, 0, true);
  assertTrue(warning.visible);
  assertFalse(warning.armed);
  assertEquals(warning.poolRadius, heroProjectileRadius(projectile, spec));
  projectile.life -= spec.activeFrom ?? 0;
  projectile.poolHits = 3;
  projectile.poolWait = (spec.pool?.every ?? 0) - 1;
  const grown = projectedProjectile(fighter, 0, true);
  assertTrue(grown.armed);
  assertEquals(grown.poolPulse, 1.0);
  projectile.poolWait -= 12;
  assertEquals(projectedProjectile(fighter, 0, true).poolPulse, 0.0);
  assertEquals(grown.poolRadius, heroProjectileRadius(projectile, spec));
  assertNear(grown.modelScale * (spec.modelRadius ?? 1.0), grown.poolRadius, f32(0.001));
  projectile.life = spec.life;
  projectile.poolHits = 0;
  const restored = projectedProjectile(fighter, 0, true);
  assertEquals(restored.poolRadius, warning.poolRadius);
  assertEquals(restored.armed, warning.armed);
  assertEquals(restored.poolPulse, 0.0);
});

test("a sparse restore replaces a speculative projectile and freeze state [invariant]", () => {
  const world = createRoster(9);
  world.fighters[0] = createFighter(Character.rifleman, -100.0, 1);
  const fighter = createFighter(Character.demonHunter, 100.0, -1);
  world.fighters[3] = fighter;
  const game = createMatchState();
  game.phase = Phase.match;
  const inputs = createFrameControls();
  const runtime = createPacingAndPresentation();
  const snapshot = createReplaySnapshot();
  const index = PROJECTILE_CAPACITY - 1;
  let last = mutableProjectile(fighter, index);
  last.life = 12;
  last.x = 73.0;
  last.z = 92.0;
  last.velocityX = -30.0;
  last.velocityZ = 10.0;
  last.kind = ProjectileKind.manaBurn;
  last.serial = 7;
  fighter.freezeTrap.life = 25;
  fighter.freezeTrap.arming = 4;
  fighter.freezeTrap.x = 81.0;
  fighter.freezeTrap.z = 3.0;
  fighter.status.frozenFrames = 11;
  captureReplaySnapshot(snapshot, world, game, inputs, runtime);
  const before = projectedProjectile(fighter, index, true);
  last = mutableProjectile(fighter, index);
  last.life = 0;
  last.x = 999.0;
  last.velocityX = 30.0;
  last.serial = 8;
  mutableProjectile(fighter, 0).life = 40;
  fighter.freezeTrap.life = 0;
  fighter.freezeTrap.arming = 0;
  fighter.freezeTrap.x = 999.0;
  fighter.status.frozenFrames = 0;
  assertFalse(projectedProjectile(fighter, index, true).visible);
  assertTrue(projectedProjectile(fighter, 0, true).visible);
  restoreReplaySnapshot(snapshot, world, game, inputs, runtime);
  const restored = projectedProjectile(fighter, index, true);
  assertTrue(restored.visible);
  assertEquals(restored.x, before.x);
  assertEquals(restored.z, before.z);
  assertEquals(restored.yaw, before.yaw);
  assertEquals(restored.pitch, before.pitch);
  assertFalse(projectedProjectile(fighter, 0, true).visible);
  assertEquals(fighter.projectiles[index]?.serial, 7);
  assertEquals(fighter.projectiles[index]?.kind, ProjectileKind.manaBurn);
  assertEquals(fighter.freezeTrap.life, 25);
  assertEquals(fighter.freezeTrap.arming, 4);
  assertEquals(fighter.freezeTrap.x, 81.0);
  assertEquals(fighter.freezeTrap.z, 3.0);
  assertEquals(fighter.status.frozenFrames, 11);
  assertEquals(world.mask, 9);
});
