import { assertEquals, assertFalse, assertTrue, test } from "wisp/src/runtime/testing";
import { createFrameControls } from "../match/controls";
import { createPacingAndPresentation } from "../match/pacingAndPresentation";
import { Phase, createMatchState } from "../match/rules";
import { captureReplaySnapshot, createReplaySnapshot, restoreReplaySnapshot } from "../replay/snapshot";
import { Character } from "../sim/codes";
import { SHIELD_MAX, createFighter } from "../sim/fighter";
import { createRoster } from "../sim/roster";
import { projectedShield } from "./shieldPose";

test("the shield follows its energy and hides on release, KO and outside play [spec docs/design/melee/defense.md]", () => {
  const fighter = createFighter(Character.rifleman, 83.0, 1);
  assertFalse(projectedShield(fighter, true).visible);
  fighter.shield.raised = true;
  fighter.motion.z = 27.0;
  fighter.shield.energy = SHIELD_MAX;
  const full = projectedShield(fighter, true);
  assertTrue(full.visible);
  assertEquals(full.x, 83.0);
  fighter.shield.energy = SHIELD_MAX / 2;
  const half = projectedShield(fighter, true);
  assertTrue(half.scale < full.scale);
  fighter.shield.energy = 0.0;
  const empty = projectedShield(fighter, true);
  assertTrue(empty.scale > 0.0 && empty.scale < half.scale);
  fighter.shield.raised = false;
  assertFalse(projectedShield(fighter, true).visible);
  fighter.shield.raised = true;
  fighter.status.out = true;
  assertFalse(projectedShield(fighter, true).visible);
  fighter.status.out = false;
  assertFalse(projectedShield(fighter, false).visible);
  assertFalse(projectedShield(undefined, true).visible);
});

test("a corrected shield projects the restored state of a sparse participant [invariant]", () => {
  const world = createRoster(9);
  world.fighters[0] = createFighter(Character.rifleman, -100.0, 1);
  const fighter = createFighter(Character.demonHunter, 100.0, -1);
  world.fighters[3] = fighter;
  const game = createMatchState();
  game.phase = Phase.match;
  const inputs = createFrameControls();
  const runtime = createPacingAndPresentation();
  const snapshot = createReplaySnapshot();
  captureReplaySnapshot(snapshot, world, game, inputs, runtime);
  fighter.shield.raised = true;
  fighter.motion.x = 211.0;
  fighter.motion.z = 17.0;
  fighter.shield.energy = 10.0;
  assertTrue(projectedShield(fighter, true).visible);
  restoreReplaySnapshot(snapshot, world, game, inputs, runtime);
  assertFalse(projectedShield(fighter, true).visible);
  fighter.shield.raised = true;
  fighter.shield.energy = SHIELD_MAX;
  captureReplaySnapshot(snapshot, world, game, inputs, runtime);
  fighter.motion.x = -333.0;
  fighter.shield.energy = 4.0;
  restoreReplaySnapshot(snapshot, world, game, inputs, runtime);
  const restored = projectedShield(fighter, true);
  assertTrue(restored.visible);
  assertEquals(restored.x, 100.0);
  const repeated = projectedShield(fighter, true);
  assertEquals(repeated.x, restored.x);
  assertEquals(repeated.z, restored.z);
  assertEquals(repeated.scale, restored.scale);
  assertEquals(fighter.shield.energy, SHIELD_MAX);
  assertEquals(world.mask, 9);
});

test("shield contact pulses through freeze and stun and returns to its held bubble [spec #82]", () => {
  const fighter = createFighter(Character.rifleman, 83.0, 1);
  fighter.shield.raised = true;
  const held = projectedShield(fighter, true);
  fighter.shield.stun = 5;
  fighter.shield.pushbackX = -10.0;
  fighter.launch.hitlag = 4;
  const contact = projectedShield(fighter, true);
  assertTrue(contact.scale > held.scale);
  assertEquals(contact.x < held.x, true, "the bubble recoils with its pushback");
  assertTrue(contact.blue < held.blue);
  fighter.launch.hitlag = 2;
  assertTrue(projectedShield(fighter, true).scale < held.scale);
  fighter.launch.hitlag = 0;
  const stunned = projectedShield(fighter, true);
  assertTrue(stunned.scale > held.scale);
  assertEquals(projectedShield(fighter, true).scale, stunned.scale);
  assertEquals(fighter.shield.stun, 5);
  fighter.shield.stun = 0;
  const recovered = projectedShield(fighter, true);
  assertEquals(recovered.scale, held.scale);
  assertEquals(recovered.x, held.x);
  assertEquals(recovered.blue, held.blue);
});
