// Generated by smashcraft:tools/animations/damage-blend-probe.ts. Diagnostic only.
export const DAMAGE_BLEND_PROBE_MODELS = [
  {
    "path": "war3mapImported\\ArcherBlend-45-50a2db97e3a5f2094315126ff4aa1c07e3f32a1f5e6dc87c40c4c15c4e7563ae.mdx",
    "sourceName": "Stand Ready",
    "sourceSeconds": 0.5625
  },
  {
    "path": "war3mapImported\\ArcherBlend-19-dc4eb9900d3d770634d58f89e334cad142b6de25f8f936df90be318d24642039.mdx",
    "sourceName": "Forward Tilt",
    "sourceSeconds": 0.5835000276565552
  }
] as const;
