// Generated by smashcraft:tools/animations/damage-blend-probe.ts. Diagnostic only.
export const DAMAGE_BLEND_PROBE_MODELS = [
  {
    "path": "war3mapImported\\RiflemanFighter-cdf101e3df707f406673755eaf1d2305f072148afc739dfe22e1a00cb25f3619.mdx",
    "sourceName": "Stand Ready",
    "sourceSeconds": 0.5625
  },
  {
    "path": "war3mapImported\\RiflemanFighter-cdf101e3df707f406673755eaf1d2305f072148afc739dfe22e1a00cb25f3619.mdx",
    "sourceName": "Forward Tilt",
    "sourceSeconds": 0.5835000276565552
  }
] as const;
