// Generated by smashcraft:tools/animations/damage-blend-probe.ts. Diagnostic only.
export const DAMAGE_BLEND_PROBE_MODELS = [
  {
    "path": "war3mapImported\\RiflemanFighter-9f110074e8b9fed718a9b7148dfdf5cf6a3d7a8a0652e6b7103993b7860cc5a5.mdx",
    "sourceName": "Stand Ready",
    "sourceSeconds": 0.5625
  },
  {
    "path": "war3mapImported\\RiflemanFighter-9f110074e8b9fed718a9b7148dfdf5cf6a3d7a8a0652e6b7103993b7860cc5a5.mdx",
    "sourceName": "Forward Tilt",
    "sourceSeconds": 0.5835000276565552
  }
] as const;
