





import { AttackPhase, AttackStyle, Character } from "../../src/game/sim/codes";
import { HERO_ROSTER } from "../../src/game/sim/heroes/registry";
import { type DrawnModel, type PoseFrame, sampleAttack } from "./hurtboxView";


const CHEST = 50.0;

const PEAK = 0.5;

const AERIAL_STYLES: readonly AttackStyle[] = [AttackStyle.neutralAir, AttackStyle.forwardAir, AttackStyle.backAir, AttackStyle.upAir, AttackStyle.downAir];

interface DrawnReach {

  readonly clip: number | undefined;

  readonly swing: number;

  readonly peakFrame: number;

  readonly firstActive: number;
  readonly lastActive: number;

  readonly forward: number;
}


function forwardOf(model: DrawnModel, frame: PoseFrame): number {
  if (frame.clip === undefined) return Number.NEGATIVE_INFINITY;
  const triangles = model.triangles(frame.clip, frame.seconds, frame.facing);
  let forward = Number.NEGATIVE_INFINITY;
  for (let i = 0; i < triangles.length; i += 2) forward = Math.max(forward, triangles[i] ?? 0);
  return forward;
}

function reachToward(model: DrawnModel, frame: PoseFrame, towardX: number, towardZ: number): number {
  if (frame.clip === undefined) return Number.NEGATIVE_INFINITY;
  const triangles = model.triangles(frame.clip, frame.seconds, frame.facing);
  let reach = Number.NEGATIVE_INFINITY;
  for (let i = 0; i < triangles.length; i += 2) {
    reach = Math.max(reach, (triangles[i] ?? 0) * towardX + ((triangles[i + 1] ?? 0) - CHEST) * towardZ);
  }
  return reach;
}


export function measureDrawnReach(model: DrawnModel, character: Character, style: AttackStyle): DrawnReach {
  const frames = sampleAttack(character, style, 1, AERIAL_STYLES.includes(style));
  const active = frames.filter((frame) => frame.phase === AttackPhase.active);
  const first = active.find((frame) => frame.strikes.length > 0);
  const strike = first?.strikes[0];
  if (first === undefined || strike === undefined) throw new Error(`${character}/${style}: no active strike`);
  const [x1, z1, x2, z2] = [strike.x1 - first.x, strike.z1 - first.z, strike.x2 - first.x, strike.z2 - first.z];
  const [farX, farZ] = Math.hypot(x2, z2 - CHEST) >= Math.hypot(x1, z1 - CHEST) ? [x2, z2] : [x1, z1];
  const length = Math.hypot(farX, farZ - CHEST) || 1;
  const reaches = frames.map((frame) => reachToward(model, frame, farX / length, (farZ - CHEST) / length));
  const most = Math.max(...reaches);
  const peak = reaches.findIndex((reach) => reach >= most - PEAK);
  return {
    clip: first.clip,

    swing: most - Math.min(...reaches.filter(Number.isFinite)),
    peakFrame: frames[peak]?.frame ?? -1,
    firstActive: first.frame,
    lastActive: active.at(-1)?.frame ?? first.frame,
    forward: Math.max(...active.map((frame) => forwardOf(model, frame))),
  };
}


const HERO_GROUND: readonly AttackStyle[] = [AttackStyle.jab, AttackStyle.jab2, AttackStyle.jab3, AttackStyle.forwardTilt, AttackStyle.forwardTiltUp, AttackStyle.forwardTiltDown, AttackStyle.upTilt, AttackStyle.downTilt, AttackStyle.dashAttack];


export const REACH_CHECKED: readonly { readonly character: Character; readonly styles: readonly AttackStyle[] }[] = [
  { character: Character.rifleman, styles: [AttackStyle.jab, AttackStyle.jab2, AttackStyle.forwardTilt, AttackStyle.forwardTiltUp, AttackStyle.forwardTiltDown, AttackStyle.upTilt, AttackStyle.downTilt, AttackStyle.dashAttack, AttackStyle.neutralAir, AttackStyle.upAir, AttackStyle.downAir] },
  { character: Character.demonHunter, styles: [AttackStyle.jab, AttackStyle.jab2, AttackStyle.jab3, AttackStyle.forwardTilt, AttackStyle.forwardTiltUp, AttackStyle.forwardTiltDown, AttackStyle.downTilt, AttackStyle.downSmash] },

  ...HERO_ROSTER.map((hero) => ({ character: hero.character, styles: hero.character === Character.lichKing
    ? [...HERO_GROUND, ...AERIAL_STYLES, AttackStyle.forwardSmash, AttackStyle.upSmash, AttackStyle.downSmash, AttackStyle.grab, AttackStyle.getupAttack, AttackStyle.ledgeAttack]
    : HERO_GROUND.filter((style) => hero.moves.normals[style] !== undefined) })),
];

export interface DrawnReachRow extends DrawnReach {
  readonly character: Character;
  readonly style: AttackStyle;

  readonly model: string;
}

export function drawnReachSource(rows: readonly DrawnReachRow[]): string {
  return [
    "// Generated by `bun wisp view reach --assets DIR` from the packaged fighter models; regenerate instead of editing.",
    "",
    "/** Per original-fighter move (#156): the model and clip measured, the drawn swing toward the strike and its peak and active frames. */",
    "export const DRAWN_REACH: readonly { readonly character: number; readonly style: number; readonly model: string; readonly clip: number; readonly swing: number; readonly peakFrame: number; readonly firstActive: number; readonly lastActive: number; readonly forward: number }[] = [",
    ...rows.map((row) => `  { character: ${row.character}, style: ${row.style}, model: ${JSON.stringify(row.model)}, clip: ${row.clip ?? -1}, swing: ${row.swing.toFixed(1)}, peakFrame: ${row.peakFrame}, firstActive: ${row.firstActive}, lastActive: ${row.lastActive}, forward: ${row.forward.toFixed(1)} },`),
    "];",
    "",
  ].join("\n");
}
