// Generated by `bun wisp view reach --assets DIR` from the packaged fighter models; regenerate instead of editing.

/** Per original-fighter move (#156): the model and clip measured, the drawn swing toward the strike and its peak and active frames. */
export const DRAWN_REACH: readonly { readonly character: number; readonly style: number; readonly model: string; readonly clip: number; readonly swing: number; readonly peakFrame: number; readonly firstActive: number; readonly lastActive: number }[] = [
  { character: 0, style: 0, model: "war3mapImported\\ArcherFighter-498a51614a2baecea63ee6538bdffa02f26e246236811d9501d90faf486045a5.mdx", clip: 7, swing: 76.0, peakFrame: 4, firstActive: 4, lastActive: 5 },
  { character: 0, style: 6, model: "war3mapImported\\ArcherFighter-498a51614a2baecea63ee6538bdffa02f26e246236811d9501d90faf486045a5.mdx", clip: 19, swing: 39.3, peakFrame: 5, firstActive: 5, lastActive: 6 },
  { character: 0, style: 9, model: "war3mapImported\\ArcherFighter-498a51614a2baecea63ee6538bdffa02f26e246236811d9501d90faf486045a5.mdx", clip: 21, swing: 42.3, peakFrame: 5, firstActive: 5, lastActive: 6 },
  { character: 0, style: 10, model: "war3mapImported\\ArcherFighter-498a51614a2baecea63ee6538bdffa02f26e246236811d9501d90faf486045a5.mdx", clip: 20, swing: 31.7, peakFrame: 5, firstActive: 5, lastActive: 6 },
  { character: 0, style: 7, model: "war3mapImported\\ArcherFighter-498a51614a2baecea63ee6538bdffa02f26e246236811d9501d90faf486045a5.mdx", clip: 51, swing: 79.6, peakFrame: 6, firstActive: 6, lastActive: 7 },
  { character: 0, style: 11, model: "war3mapImported\\ArcherFighter-498a51614a2baecea63ee6538bdffa02f26e246236811d9501d90faf486045a5.mdx", clip: 23, swing: 37.0, peakFrame: 16, firstActive: 16, lastActive: 18 },
  { character: 1, style: 12, model: "war3mapImported\\RiflemanFighter-2ac45d120233664d8b0f432a241ab61ccaceefb8bb053a39f101380e739fd973.mdx", clip: 3, swing: 77.6, peakFrame: 3, firstActive: 3, lastActive: 30 },
  { character: 1, style: 15, model: "war3mapImported\\RiflemanFighter-2ac45d120233664d8b0f432a241ab61ccaceefb8bb053a39f101380e739fd973.mdx", clip: 4, swing: 69.6, peakFrame: 5, firstActive: 5, lastActive: 7 },
  { character: 1, style: 16, model: "war3mapImported\\RiflemanFighter-2ac45d120233664d8b0f432a241ab61ccaceefb8bb053a39f101380e739fd973.mdx", clip: 1, swing: 59.0, peakFrame: 7, firstActive: 7, lastActive: 9 },
  { character: 2, style: 0, model: "war3mapImported\\DemonHunterFighter-fc19988055002962f7df7949dd5923783b3a289d47b17f96cabfcf99672092a7.mdx", clip: 9, swing: 68.0, peakFrame: 4, firstActive: 4, lastActive: 5 },
  { character: 2, style: 6, model: "war3mapImported\\DemonHunterFighter-fc19988055002962f7df7949dd5923783b3a289d47b17f96cabfcf99672092a7.mdx", clip: 35, swing: 76.2, peakFrame: 5, firstActive: 5, lastActive: 6 },
  { character: 2, style: 9, model: "war3mapImported\\DemonHunterFighter-fc19988055002962f7df7949dd5923783b3a289d47b17f96cabfcf99672092a7.mdx", clip: 37, swing: 76.4, peakFrame: 5, firstActive: 5, lastActive: 6 },
  { character: 2, style: 10, model: "war3mapImported\\DemonHunterFighter-fc19988055002962f7df7949dd5923783b3a289d47b17f96cabfcf99672092a7.mdx", clip: 36, swing: 36.4, peakFrame: 5, firstActive: 5, lastActive: 6 },
  { character: 2, style: 8, model: "war3mapImported\\DemonHunterFighter-fc19988055002962f7df7949dd5923783b3a289d47b17f96cabfcf99672092a7.mdx", clip: 27, swing: 55.1, peakFrame: 5, firstActive: 5, lastActive: 6 },
  { character: 2, style: 3, model: "war3mapImported\\DemonHunterFighter-fc19988055002962f7df7949dd5923783b3a289d47b17f96cabfcf99672092a7.mdx", clip: 24, swing: 64.3, peakFrame: 8, firstActive: 8, lastActive: 16 },
];
