// Measures, for every hero normal and special, the moment its clip strikes:
// the clip time where the drawn silhouette reaches farthest toward the move's
// first hit region (a special's first shot or placement when it has no
// region), skinned from the supplied hero model the clients draw. Written as
// src/game/presentation/heroStrikeMomentInfo.ts, which pose selection uses to
// land each swing on the move's first active frame (#144).
import { parseMDX } from "war3-model";
import { attackPose, clipFor, ownAttackClip } from "../../src/game/presentation/fighterClips";
import { SPECIAL_KEY } from "../../src/game/presentation/heroStrikeMomentKeys";
import { SPECIAL_SLOTS } from "../../src/game/presentation/projectileArt";
import { AttackStyle } from "../../src/game/sim/codes";
import { HERO_ROSTER } from "../../src/game/sim/heroes/registry";
import { DrawnModel } from "./hurtboxView";

/** The body centre a strike's direction is taken from: chest height of the reference. */
const CHEST = 50.0;
/** Steps of clip time the measurement samples, a sixtieth of a second each. */
const STEP = 1.0 / 60.0;
/** A later sample replaces the peak only when it reaches this much farther, so a held pose keeps its first moment. */
const FARTHER = 0.5;

export interface StrikeMoment {
  readonly character: number;
  /** An attack style, or SPECIAL_KEY plus a special slot. */
  readonly style: number;
  /** The clip index measured; a table change makes the moment stale. */
  readonly clip: number;
  /** Clip seconds of the farthest reach toward the strike. */
  readonly seconds: number;
  /** The whole sequence's length in seconds. */
  readonly end: number;
}

interface Sequence {
  readonly Interval: ArrayLike<number>;
}

/** The clip moment that reaches farthest from the chest toward (x, z). */
function measure(drawn: DrawnModel, character: number, style: number, clip: number, sequence: Sequence, x: number, z: number): StrikeMoment {
  const towardZ = z - CHEST;
  const length = Math.hypot(x, towardZ) || 1;
  const end = ((sequence.Interval[1] ?? 0) - (sequence.Interval[0] ?? 0)) / 1000;
  let best = -Infinity;
  let moment = 0;
  for (let time = 0; time <= end; time += STEP) {
    const triangles = drawn.triangles(clip, time, 1);
    let reach = -Infinity;
    for (let i = 0; i < triangles.length; i += 2) {
      reach = Math.max(reach, ((triangles[i] ?? 0) * x + ((triangles[i + 1] ?? 0) - CHEST) * towardZ) / length);
    }
    if (reach > best + FARTHER) {
      best = reach;
      moment = time;
    }
  }
  return { character, style, clip, seconds: Math.round(moment * 1000) / 1000, end: Math.round(end * 1000) / 1000 };
}

/** Every hero normal with a hit region and every special that strikes, shoots or places, measured on `modelBytes(hero.presentation.model)`. */
export async function measureStrikeMoments(modelBytes: (model: string) => Promise<ArrayBuffer>): Promise<StrikeMoment[]> {
  const moments: StrikeMoment[] = [];
  for (const hero of HERO_ROSTER) {
    const bytes = await modelBytes(hero.presentation.model);
    const sequences = parseMDX(bytes).Sequences;
    const drawn = new DrawnModel(bytes, 1.0);
    for (const style of Object.values(AttackStyle)) {
      const move = hero.moves.normals[style];
      const region = move?.regions[0];
      if (move === undefined || region === undefined || style === AttackStyle.grab) continue;
      const pose = attackPose(style);
      const clip = ownAttackClip(hero.character, style) ?? (pose === undefined ? undefined : clipFor(hero.character, pose));
      const sequence = clip === undefined ? undefined : sequences[clip.index];
      if (clip === undefined || sequence === undefined) continue;
      const { minX, maxX, minZ, maxZ } = region.hit;
      moments.push(measure(drawn, hero.character, style, clip.index, sequence, (minX + maxX) / 2, (minZ + maxZ) / 2));
    }
    const specials = hero.specials;
    if (specials === undefined) continue;
    SPECIAL_SLOTS.forEach((slot, index) => {
      const move = specials[slot].ground;
      const clip = clipFor(hero.character, `${slot}Special`);
      const sequence = sequences[clip.index];
      const region = move.regions?.[0]?.hit;
      const shot = move.projectiles?.[0];
      const toward = region !== undefined ? { x: (region.minX + region.maxX) / 2, z: (region.minZ + region.maxZ) / 2 }
        : shot !== undefined ? { x: shot.offsetX, z: shot.offsetZ }
        : move.placement !== undefined ? { x: move.placement.offsetX, z: CHEST } : undefined;
      if (sequence === undefined || toward === undefined) return;
      moments.push(measure(drawn, hero.character, SPECIAL_KEY + index, clip.index, sequence, toward.x, toward.z));
    });
  }
  return moments;
}

export function strikeMomentSource(moments: readonly StrikeMoment[]): string {
  return [
    "// Generated by `bun wisp view strikes` from the drawn hero models, including authored clips; regenerate instead of editing.",
    'import { f32 } from "wisp/src/sim/f32";',
    "",
    "/**",
    " * Per hero and attack style (or SPECIAL_KEY plus a special slot): the clip measured, the clip",
    " * seconds where it reaches farthest toward its strike and the sequence's length.",
    " */",
    "export const HERO_STRIKE_MOMENTS: { readonly [character: number]: { readonly [style: number]: { readonly clip: number; readonly seconds: number; readonly end: number } | undefined } | undefined } = {",
    ...[...new Set(moments.map(({ character }) => character))].map((character) => {
      const rows = moments.filter((moment) => moment.character === character).map(({ style, clip, seconds, end }) => `${style}: { clip: ${clip}, seconds: f32(${seconds.toFixed(3)}), end: f32(${end.toFixed(3)}) }`);
      return `  ${character}: { ${rows.join(", ")} },`;
    }),
    "};",
    "",
  ].join("\n");
}
