import type { ModelFacts } from "wisp/scripts/wisp/models";

export function whiteModelFactsSource(
  existing: Readonly<Record<string, ModelFacts>>,
  paths: readonly string[],
  white: Readonly<Record<string, ModelFacts>>,
): string {
  const rows = Object.entries(existing).filter(([path]) => !/^war3mapImported\\[A-Za-z]+White-[a-f0-9]{64}\.mdx$/.test(path));
  for (const path of paths) {
    const facts = white[path.replaceAll("\\", "/").toLowerCase()];
    if (facts === undefined) throw new Error(`Missing white model facts: ${path}`);
    rows.push([path, facts]);
  }
  rows.sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0);
  return [
    "// Generated by `bun wisp view models` and tools/animations/white-flash-models.ts; regenerate instead of editing.",
    'import type { ModelFacts } from "wisp/scripts/wisp/models";',
    "",
    "export const MODEL_FACTS: Readonly<Record<string, ModelFacts>> = {",
    ...rows.map(([path, facts]) => `  ${JSON.stringify(path)}: ${JSON.stringify(facts, (_key, value: unknown) => typeof value === "number" ? Math.round(value * 1000) / 1000 : value)},`),
    "};", "",
  ].join("\n");
}
