// Generated by tools/animations/white-flash-models.ts; regenerate instead of editing.
import type { ModelFacts } from "wisp/scripts/wisp/models";
export const WHITE_MODEL_FACTS: Readonly<Record<string, ModelFacts>> = {
  "war3mapimported/archerwhite-6783f3c31979c04ab1fad283d40f62a49f41cc77d3624d0dfcc7b63b8f0584aa.mdx": {
    "geosets": 3,
    "triangles": 441,
    "lights": 0,
    "bounds": {
      "min": [
        -87.03669738769531,
        -39.496299743652344,
        -34.04900360107422
      ],
      "max": [
        45.79249954223633,
        81.69499969482422,
        119.14099884033203
      ]
    },
    "emitters": []
  },
  "war3mapimported/riflemanwhite-d95ad99e0850a2d0378ef8fda176b07c296babeaf0d83911ed439fc08d4e1ebe.mdx": {
    "geosets": 4,
    "triangles": 455,
    "lights": 0,
    "bounds": {
      "min": [
        -73.08200073242188,
        -37.43429946899414,
        -13.734192848205566
      ],
      "max": [
        66.64360046386719,
        55.43191909790039,
        131.07400512695312
      ]
    },
    "emitters": []
  },
  "war3mapimported/illidanwhite-8610cc68d48737332900988a04923b19382458968aabda9ed8ea442573b3f265.mdx": {
    "geosets": 18,
    "triangles": 1295,
    "lights": 0,
    "bounds": {
      "min": [
        -204.4149932861328,
        -202.2220001220703,
        -99.90679931640625
      ],
      "max": [
        199.40199279785156,
        201.59500122070312,
        267.77301025390625
      ]
    },
    "emitters": []
  },
  "war3mapimported/blademasterwhite-0a65ac7805feb755af5399b0305debe9d7ab27baaebb2338a8f81034e3d4b604.mdx": {
    "geosets": 9,
    "triangles": 550,
    "lights": 0,
    "bounds": {
      "min": [
        -398.0740051269531,
        -378.6839904785156,
        -70.77629852294922
      ],
      "max": [
        376.4989929199219,
        399.2030029296875,
        1040.8699951171875
      ]
    },
    "emitters": []
  },
  "war3mapimported/mountainkingwhite-b377420d82f9992f7cac6c3a941f88eba74e4f8c44f7c5dabbded482badcfe90.mdx": {
    "geosets": 8,
    "triangles": 570,
    "lights": 0,
    "bounds": {
      "min": [
        -121.20800018310547,
        -115.34300231933594,
        -82.11190032958984
      ],
      "max": [
        142.7100067138672,
        116.38099670410156,
        564.8629760742188
      ]
    },
    "emitters": []
  },
  "war3mapimported/wardenwhite-34b81ee50c632c505b4205029b2fb0eb2dc21c965065362ad309679eb7ccf92e.mdx": {
    "geosets": 5,
    "triangles": 685,
    "lights": 0,
    "bounds": {
      "min": [
        -156.19500732421875,
        -144.2050018310547,
        -54.45240020751953
      ],
      "max": [
        143.6580047607422,
        141.60000610351562,
        442.06500244140625
      ]
    },
    "emitters": []
  },
  "war3mapimported/lichwhite-fe2b0745c45e0948cb717a98f5ebc921e45cb2656031de77b5734c3bb751fa76.mdx": {
    "geosets": 12,
    "triangles": 596,
    "lights": 0,
    "bounds": {
      "min": [
        -162.3159942626953,
        -165.9600067138672,
        -52.3577995300293
      ],
      "max": [
        168.93099975585938,
        165.28700256347656,
        218.0189971923828
      ]
    },
    "emitters": []
  },
  "war3mapimported/utherwhite-a7b30297345a9e36f45a8f13f8ac7f712400a41de3936cc0a837e12bb498d0ba.mdx": {
    "geosets": 5,
    "triangles": 3217,
    "lights": 0,
    "bounds": {
      "min": [
        -168.41700744628906,
        -140.38800048828125,
        -73.71690368652344
      ],
      "max": [
        167.3679962158203,
        167.92300415039062,
        516.6019897460938
      ]
    },
    "emitters": []
  },
  "war3mapimported/dreadlordwhite-e7d952d826707e5bc4f32fd1da71e3e5c05c363e38d811fdbb5568828d82b355.mdx": {
    "geosets": 12,
    "triangles": 806,
    "lights": 0,
    "bounds": {
      "min": [
        -465.8590087890625,
        -406.77099609375,
        -25.757400512695312
      ],
      "max": [
        465.4670104980469,
        456.28900146484375,
        746.1959838867188
      ]
    },
    "emitters": []
  },
  "war3mapimported/shadowhunterwhite-17bd7063543167cb21372111d1c17776584a6c184bb5356724c965f429f208ee.mdx": {
    "geosets": 7,
    "triangles": 539,
    "lights": 0,
    "bounds": {
      "min": [
        -257.0799865722656,
        -186.99099731445312,
        -124.97599792480469
      ],
      "max": [
        250.43299865722656,
        184.05999755859375,
        520.5850219726562
      ]
    },
    "emitters": []
  },
  "war3mapimported/pitlordwhite-52cb466d1ea4676eec19e954331c3244ffb579a7b73fae08cee459d2995327e0.mdx": {
    "geosets": 5,
    "triangles": 705,
    "lights": 0,
    "bounds": {
      "min": [
        -254.47000122070312,
        -258.81500244140625,
        -132.87399291992188
      ],
      "max": [
        288.1029968261719,
        196.4770050048828,
        688.5919799804688
      ]
    },
    "emitters": []
  },
  "war3mapimported/beastmasterwhite-81dcc9ec58560d83c063ab16287f838324c32619bbf5597c70bcdf7ec8cee591.mdx": {
    "geosets": 7,
    "triangles": 681,
    "lights": 0,
    "bounds": {
      "min": [
        -195.18899536132812,
        -197.4949951171875,
        -73.79879760742188
      ],
      "max": [
        217.75599670410156,
        186.94000244140625,
        763.3880004882812
      ]
    },
    "emitters": []
  },
  "war3mapimported/lichkingwhite-df9bb39f789d9db1acf411e0c77bf427467b2d8d5e2177a92c070df8e90a99d5.mdx": {
    "geosets": 7,
    "triangles": 1931,
    "lights": 0,
    "bounds": {
      "min": [
        -39.135101318359375,
        -64.08399963378906,
        0.4492189884185791
      ],
      "max": [
        215.11300659179688,
        44.51449966430664,
        161.04100036621094
      ]
    },
    "emitters": []
  },
  "war3mapimported/thrallwhite-f48c5827d242ea18ff7e70783f279a2135f6ba7edd18379315db5e8861f53d56.mdx": {
    "geosets": 3,
    "triangles": 557,
    "lights": 0,
    "bounds": {
      "min": [
        -207.31399536132812,
        -210.51800537109375,
        -74.03089904785156
      ],
      "max": [
        208.11500549316406,
        177.19700622558594,
        633.6190185546875
      ]
    },
    "emitters": []
  },
  "war3mapimported/jainaproudmoorewhite-d5220d66417c066bc591b1f5c759cfdda984282c17a7d07cfbef3ce8c994dcb4.mdx": {
    "geosets": 3,
    "triangles": 564,
    "lights": 0,
    "bounds": {
      "min": [
        -140.33799743652344,
        -132.1320037841797,
        -9.235360145568848
      ],
      "max": [
        123.25199890136719,
        131.45799255371094,
        342.8320007324219
      ]
    },
    "emitters": []
  },
  "war3mapimported/sylvanaswindrunnerwhite-8a02fe2068ca0ca51cfa49ef53d3a9b37086d6e5630bacf804be59ff57d7b530.mdx": {
    "geosets": 7,
    "triangles": 489,
    "lights": 0,
    "bounds": {
      "min": [
        -145.44700622558594,
        -111.19999694824219,
        -44.0005989074707
      ],
      "max": [
        119.04299926757812,
        114.08999633789062,
        500.8219909667969
      ]
    },
    "emitters": []
  },
  "war3mapimported/cairnebloodhoofwhite-6fc92f3376a01304a24ed9806e5bf459ca9132f597d30c060da2392414a2135e.mdx": {
    "geosets": 6,
    "triangles": 481,
    "lights": 0,
    "bounds": {
      "min": [
        -230.30599975585938,
        -255.20399475097656,
        -81.0114974975586
      ],
      "max": [
        232.87100219726562,
        283.1789855957031,
        464.3380126953125
      ]
    },
    "emitters": []
  },
  "war3mapimported/chenstormstoutwhite-33d0c250588260d20ebf7886d61f42f5de4a0abf19acfb2b9848eb97e7ae6fd4.mdx": {
    "geosets": 7,
    "triangles": 607,
    "lights": 0,
    "bounds": {
      "min": [
        -188.97000122070312,
        -167.5469970703125,
        -73.79879760742188
      ],
      "max": [
        319.62701416015625,
        242.29600524902344,
        751.739013671875
      ]
    },
    "emitters": []
  },
  "war3mapimported/peonwhite-e694edc1cde755471e9bac4ccc8e3b4b55df7116efcaa5600f52fbb95a17643f.mdx": {
    "geosets": 5,
    "triangles": 372,
    "lights": 0,
    "bounds": {
      "min": [
        -81.0353012084961,
        -76.47509765625,
        -29.07939910888672
      ],
      "max": [
        96.0802001953125,
        77.04409790039062,
        135.59800720214844
      ]
    },
    "emitters": []
  },
  "war3mapimported/goblintinkerwhite-294c635df5fed4534d22e5e2b84be78e91c2fdd9404adb4c6a51ac499cbc0614.mdx": {
    "geosets": 24,
    "triangles": 2412,
    "lights": 0,
    "bounds": {
      "min": [
        -272.2879943847656,
        -264.968994140625,
        -26.107999801635742
      ],
      "max": [
        256.92999267578125,
        264.24798583984375,
        366.3789978027344
      ]
    },
    "emitters": []
  },
  "war3mapimported/kaelthassunstriderwhite-e5cfc4b4750f950f917b61b2c4b83bec0b7aa0a0cebe94eadf06229952378d70.mdx": {
    "geosets": 9,
    "triangles": 603,
    "lights": 0,
    "bounds": {
      "min": [
        -208.4720001220703,
        -139.51699829101562,
        -16.336200714111328
      ],
      "max": [
        155.91799926757812,
        131.17999267578125,
        644.5029907226562
      ]
    },
    "emitters": []
  }
};
