// Generated by tools/animations/white-flash-models.ts; regenerate instead of editing.
import type { ModelFacts } from "wisp/scripts/wisp/models";
export const WHITE_MODEL_FACTS: Readonly<Record<string, ModelFacts>> = {
  "war3mapimported/archerwhite-5599494d2e3da37f1d285f54607c66988896edf63dba223cebe01d19cc71f7e9.mdx": {
    "geosets": 3,
    "triangles": 441,
    "lights": 0,
    "bounds": {
      "min": [
        -87.03669738769531,
        -39.496299743652344,
        -34.04900360107422
      ],
      "max": [
        45.79249954223633,
        81.69499969482422,
        119.14099884033203
      ]
    },
    "emitters": []
  },
  "war3mapimported/riflemanwhite-f74731bb86aca88ef047cc1362b6dcffa1b51519c750ed7670b8aeabdc49d3ef.mdx": {
    "geosets": 4,
    "triangles": 455,
    "lights": 0,
    "bounds": {
      "min": [
        -73.08200073242188,
        -37.43429946899414,
        -13.734192848205566
      ],
      "max": [
        66.64360046386719,
        55.43191909790039,
        131.07400512695312
      ]
    },
    "emitters": []
  },
  "war3mapimported/illidanwhite-764afe9ed3b75426cf4e3303c9475029cfdb6bc879a870231f7c1bd17735f8f3.mdx": {
    "geosets": 18,
    "triangles": 1295,
    "lights": 0,
    "bounds": {
      "min": [
        -204.4149932861328,
        -202.2220001220703,
        -99.90679931640625
      ],
      "max": [
        199.40199279785156,
        201.59500122070312,
        267.77301025390625
      ]
    },
    "emitters": []
  },
  "war3mapimported/blademasterwhite-260734cfb9577d4c643355feaa92ff6497a4acb2142df75dc7cd2070f830a9a2.mdx": {
    "geosets": 9,
    "triangles": 550,
    "lights": 0,
    "bounds": {
      "min": [
        -398.0740051269531,
        -378.6839904785156,
        -70.77629852294922
      ],
      "max": [
        376.4989929199219,
        399.2030029296875,
        1040.8699951171875
      ]
    },
    "emitters": []
  },
  "war3mapimported/mountainkingwhite-535afe7da7d2308248b3601c3ef9a3e800d8006a2f7cf0699a1bbe289c4217a2.mdx": {
    "geosets": 8,
    "triangles": 570,
    "lights": 0,
    "bounds": {
      "min": [
        -121.20800018310547,
        -115.34300231933594,
        -82.11190032958984
      ],
      "max": [
        142.7100067138672,
        116.38099670410156,
        564.8629760742188
      ]
    },
    "emitters": []
  },
  "war3mapimported/wardenwhite-0655f8acbce17a38b2d40c40e1543f67c5807e1f35683fb9d733068060cc0f3b.mdx": {
    "geosets": 5,
    "triangles": 685,
    "lights": 0,
    "bounds": {
      "min": [
        -156.19500732421875,
        -144.2050018310547,
        -54.45240020751953
      ],
      "max": [
        143.6580047607422,
        141.60000610351562,
        442.06500244140625
      ]
    },
    "emitters": []
  },
  "war3mapimported/lichwhite-ac76dec65d4c36d23ec87efeb8bc1708a5554f918c72e5be6ea15ad555d6a60f.mdx": {
    "geosets": 12,
    "triangles": 596,
    "lights": 0,
    "bounds": {
      "min": [
        -162.3159942626953,
        -165.9600067138672,
        -52.3577995300293
      ],
      "max": [
        168.93099975585938,
        165.28700256347656,
        218.0189971923828
      ]
    },
    "emitters": []
  },
  "war3mapimported/utherwhite-bf42f479f0154e8991a03f51546e4b37bd34ab7f112d35aeb573667d4bf6ce36.mdx": {
    "geosets": 3,
    "triangles": 454,
    "lights": 0,
    "bounds": {
      "min": [
        -168.41700744628906,
        -140.38800048828125,
        -73.71690368652344
      ],
      "max": [
        167.3679962158203,
        167.92300415039062,
        531.0700073242188
      ]
    },
    "emitters": []
  },
  "war3mapimported/dreadlordwhite-612f66de162e9c38c03245493ec19ec4f933958fa4b1cc69eaa3cf9bfe59e2f6.mdx": {
    "geosets": 12,
    "triangles": 806,
    "lights": 0,
    "bounds": {
      "min": [
        -465.8590087890625,
        -406.77099609375,
        -25.757400512695312
      ],
      "max": [
        465.4670104980469,
        456.28900146484375,
        746.1959838867188
      ]
    },
    "emitters": []
  },
  "war3mapimported/shadowhunterwhite-911856adeb89d4c9dd34a33330de5e65d782aa751307fa215df609fae5782903.mdx": {
    "geosets": 7,
    "triangles": 539,
    "lights": 0,
    "bounds": {
      "min": [
        -257.0799865722656,
        -186.99099731445312,
        -124.97599792480469
      ],
      "max": [
        250.43299865722656,
        184.05999755859375,
        520.5850219726562
      ]
    },
    "emitters": []
  },
  "war3mapimported/pitlordwhite-2c9b512a87d1640390a55bf3515a4855f9700603d287e71759280c8ef486d557.mdx": {
    "geosets": 5,
    "triangles": 705,
    "lights": 0,
    "bounds": {
      "min": [
        -254.47000122070312,
        -258.81500244140625,
        -132.87399291992188
      ],
      "max": [
        288.1029968261719,
        196.4770050048828,
        688.5919799804688
      ]
    },
    "emitters": []
  },
  "war3mapimported/beastmasterwhite-9faa3d568f7d520e0373b321827d7508b6148cbe6252ac62175ac4a2250625ac.mdx": {
    "geosets": 7,
    "triangles": 681,
    "lights": 0,
    "bounds": {
      "min": [
        -195.18899536132812,
        -197.4949951171875,
        -73.79879760742188
      ],
      "max": [
        217.75599670410156,
        186.94000244140625,
        763.3880004882812
      ]
    },
    "emitters": []
  },
  "war3mapimported/lichkingwhite-04ac205b2cdd4d50e1269f83269ac58e34b27148d5a353c78dcffcabfb6f58bb.mdx": {
    "geosets": 7,
    "triangles": 1931,
    "lights": 0,
    "bounds": {
      "min": [
        -39.135101318359375,
        -64.08399963378906,
        0.4492189884185791
      ],
      "max": [
        215.11300659179688,
        44.51449966430664,
        161.04100036621094
      ]
    },
    "emitters": []
  },
  "war3mapimported/thrallwhite-c78200f6c83811c8ced9d201e21e1eb87dd5a3ea8e4f36d128ab573593e6a332.mdx": {
    "geosets": 3,
    "triangles": 557,
    "lights": 0,
    "bounds": {
      "min": [
        -207.31399536132812,
        -210.51800537109375,
        -74.03089904785156
      ],
      "max": [
        208.11500549316406,
        177.19700622558594,
        633.6190185546875
      ]
    },
    "emitters": []
  }
};
