import { mutableProjectile } from "../sim/fighterProjectiles";
import { assertEquals, assertFalse, assertTrue, test } from "wisp/src/runtime/testing";
import { at } from "wisp/src/runtime/lookup";
import { Character } from "../sim/codes";
import { createFighter } from "../sim/fighter";
import { neutralControls } from "../sim/roster";
import { chooseDefense } from "./botDefense";
import { cpuSkill } from "./cpuSkill";

test("a delayed visible shot is defended at its predicted position without seeing a newer sample [invariant]", () => {
  const own = createFighter(Character.rifleman, 0.0, 1);
  const target = createFighter(Character.rifleman, 700.0, -1);
  own.motion.grounded = true;
  target.motion.grounded = true;
  const projectile = mutableProjectile(target, 0);
  projectile.life = 60;
  projectile.serial = 8;
  projectile.direction = -1;
  projectile.velocityX = -36.0;
  projectile.velocityZ = 0.0;
  projectile.x = 500.0;
  projectile.z = 75.0;
  const skill = { ...cpuSkill("wren", "expert"), reactionFrames: 0 };
  assertFalse(chooseDefense(own, target, 0, neutralControls(), skill));
  const predicted = neutralControls();
  assertTrue(chooseDefense(own, target, 0, predicted, skill, 12));
  assertTrue(predicted.shield);
  assertTrue(predicted.groundDodgePressed);
  assertEquals(projectile.x, 500.0);
  assertEquals(projectile.life, 60);
  projectile.x = 68.0;
  const current = neutralControls();
  assertTrue(chooseDefense(own, target, 0, current, skill));
  assertEquals(predicted.shield, current.shield);
  assertEquals(predicted.groundDodgePressed, current.groundDodgePressed);
  assertEquals(predicted.groundDodgeDirection, current.groundDodgeDirection);
});
